In [1]:
!killall -9 python
!sudo apt update
!sudo apt install -y pciutils
!sudo apt-get install zstd
!curl -fsSL https://ollama.com/install.sh | sh

/bin/bash: line 1: killall: command not found
Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:5 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
28 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
pciutils is already the newest version (1:3.7.0-6).
0 upgraded, 0 newly installed, 0 to remove and 28 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
zstd is already the newest version (1.4.8+dfsg-3build1).
0 upgraded, 0 newly installed, 0 to remove and 28 not upgraded.
>>> Cleaning up old version at /usr/local/lib/ollama
>>> Installing ollama to /usr/local
>>> Downloading ollama-linux-amd64.tar.zst
######################################################################## 100.0%
>>> NVIDIA GPU installed.
>>> The Ollama API is now available at 127.0.0.1:11434.
>>> Install complete. Run "ollama" from the command line.

In [26]:
import os
from huggingface_hub import login

# You can get the token from an environment variable for security

# Or paste it directly (less secure)
hf_token = os.environ.get("HF_TOKEN")

login(token=hf_token)

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [1]:
import threading
import subprocess
import time

def run_ollama_serve():
  subprocess.Popen(["ollama", "serve"])

thread = threading.Thread(target=run_ollama_serve)
thread.start()
time.sleep(5)

Error: listen tcp 127.0.0.1:11434: bind: address already in use

In [16]:
!pip install -r requirements.txt

WARNING: Ignoring invalid distribution ~ensorflow (/home/jovyan/.conda/lib/python3.13/site-packages)
WARNING: Ignoring invalid distribution ~ensorflow (/home/jovyan/.conda/lib/python3.13/site-packages)
WARNING: Ignoring invalid distribution ~angchain-core (/home/jovyan/.conda/lib/python3.13/site-packages)
Requirement already satisfied: ollama in /home/jovyan/.conda/lib/python3.13/site-packages (0.6.1)
Requirement already satisfied: httpx>=0.27 in /home/jovyan/.conda/lib/python3.13/site-packages (from ollama) (0.28.1)
Requirement already satisfied: pydantic>=2.9 in /home/jovyan/.conda/lib/python3.13/site-packages (from ollama) (2.12.4)
Requirement already satisfied: anyio in /home/jovyan/.conda/lib/python3.13/site-packages (from httpx>=0.27->ollama) (4.12.1)
Requirement already satisfied: certifi in /home/jovyan/.conda/lib/python3.13/site-packages (from httpx>=0.27->ollama) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /home/jovyan/.conda/lib/python3.13/site-packages (from httpx>=0.27->ollama) (1.0.9)
Requirement already satisfied: idna in /home/jovyan/.conda/lib/python3.13/site-packages (from httpx>=0.27->ollama) (3.11)
Requirement already satisfied: h11>=0.16 in /home/jovyan/.conda/lib/python3.13/site-packages (from httpcore==1.*->httpx>=0.27->ollama) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /home/jovyan/.conda/lib/python3.13/site-packages (from pydantic>=2.9->ollama) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in /home/jovyan/.conda/lib/python3.13/site-packages (from pydantic>=2.9->ollama) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in /home/jovyan/.conda/lib/python3.13/site-packages (from pydantic>=2.9->ollama) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /home/jovyan/.conda/lib/python3.13/site-packages (from pydantic>=2.9->ollama) (0.4.2)
WARNING: Ignoring invalid distribution ~ensorflow (/home/jovyan/.conda/lib/python3.13/site-packages)
WARNING: Ignoring invalid distribution ~angchain-core (/home/jovyan/.conda/lib/python3.13/site-packages)
WARNING: Ignoring invalid distribution ~ensorflow (/home/jovyan/.conda/lib/python3.13/site-packages)
WARNING: Ignoring invalid distribution ~angchain-core (/home/jovyan/.conda/lib/python3.13/site-packages)
WARNING: Ignoring invalid distribution ~ensorflow (/home/jovyan/.conda/lib/python3.13/site-packages)
WARNING: Ignoring invalid distribution ~ensorflow (/home/jovyan/.conda/lib/python3.13/site-packages)
WARNING: Ignoring invalid distribution ~ensorflow (/home/jovyan/.conda/lib/python3.13/site-packages)
WARNING: Ignoring invalid distribution ~ensorflow (/home/jovyan/.conda/lib/python3.13/site-packages)
WARNING: Ignoring invalid distribution ~angchain-core (/home/jovyan/.conda/lib/python3.13/site-packages)
Requirement already satisfied: langchain in /home/jovyan/.conda/lib/python3.13/site-packages (1.2.10)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.10 in /home/jovyan/.conda/lib/python3.13/site-packages (from langchain) (1.2.21)
Requirement already satisfied: langgraph<1.1.0,>=1.0.8 in /home/jovyan/.conda/lib/python3.13/site-packages (from langchain) (1.0.8)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /home/jovyan/.conda/lib/python3.13/site-packages (from langchain) (2.12.4)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /home/jovyan/.conda/lib/python3.13/site-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /home/jovyan/.conda/lib/python3.13/site-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (0.7.3)
Requirement already satisfied: packaging>=23.2.0 in /home/jovyan/.conda/lib/python3.13/site-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (25.0)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /home/jovyan/.conda/lib/python3.13/site-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /home/jovyan/.conda/lib/python3.13/site-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /home/jovyan/.conda/lib/python3.13/site-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /home/jovyan/.conda/lib/python3.13/site-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (0.14.0)
Requirement already satisfied: jsonpointer>=1.9 in /home/jovyan/.conda/lib/python3.13/site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.10->langchain) (3.0.0)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=2.1.0 in /home/jovyan/.conda/lib/python3.13/site-packages (from langgraph<1.1.0,>=1.0.8->langchain) (4.0.0)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.7 in /home/jovyan/.conda/lib/python3.13/site-packages (from langgraph<1.1.0,>=1.0.8->langchain) (1.0.7)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in /home/jovyan/.conda/lib/python3.13/site-packages (from langgraph<1.1.0,>=1.0.8->langchain) (0.3.6)
Requirement already satisfied: xxhash>=3.5.0 in /home/jovyan/.conda/lib/python3.13/site-packages (from langgraph<1.1.0,>=1.0.8->langchain) (3.6.0)
Requirement already satisfied: ormsgpack>=1.12.0 in /home/jovyan/.conda/lib/python3.13/site-packages (from langgraph-checkpoint<5.0.0,>=2.1.0->langgraph<1.1.0,>=1.0.8->langchain) (1.12.2)
Requirement already satisfied: httpx>=0.25.2 in /home/jovyan/.conda/lib/python3.13/site-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.8->langchain) (0.28.1)
Requirement already satisfied: orjson>=3.10.1 in /home/jovyan/.conda/lib/python3.13/site-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.8->langchain) (3.11.7)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /home/jovyan/.conda/lib/python3.13/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.10->langchain) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /home/jovyan/.conda/lib/python3.13/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.10->langchain) (2.32.5)
Requirement already satisfied: zstandard>=0.23.0 in /home/jovyan/.conda/lib/python3.13/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.10->langchain) (0.24.0)
Requirement already satisfied: anyio in /home/jovyan/.conda/lib/python3.13/site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.8->langchain) (4.12.1)
Requirement already satisfied: certifi in /home/jovyan/.conda/lib/python3.13/site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.8->langchain) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /home/jovyan/.conda/lib/python3.13/site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.8->langchain) (1.0.9)
Requirement already satisfied: idna in /home/jovyan/.conda/lib/python3.13/site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.8->langchain) (3.11)
Requirement already satisfied: h11>=0.16 in /home/jovyan/.conda/lib/python3.13/site-packages (from httpcore==1.*->httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.8->langchain) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /home/jovyan/.conda/lib/python3.13/site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in /home/jovyan/.conda/lib/python3.13/site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /home/jovyan/.conda/lib/python3.13/site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/jovyan/.conda/lib/python3.13/site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.10->langchain) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/jovyan/.conda/lib/python3.13/site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.10->langchain) (2.6.3)
WARNING: Ignoring invalid distribution ~ensorflow (/home/jovyan/.conda/lib/python3.13/site-packages)
WARNING: Ignoring invalid distribution ~angchain-core (/home/jovyan/.conda/lib/python3.13/site-packages)
WARNING: Ignoring invalid distribution ~ensorflow (/home/jovyan/.conda/lib/python3.13/site-packages)
WARNING: Ignoring invalid distribution ~angchain-core (/home/jovyan/.conda/lib/python3.13/site-packages)
WARNING: Ignoring invalid distribution ~ensorflow (/home/jovyan/.conda/lib/python3.13/site-packages)
WARNING: Ignoring invalid distribution ~ensorflow (/home/jovyan/.conda/lib/python3.13/site-packages)
WARNING: Ignoring invalid distribution ~ensorflow (/home/jovyan/.conda/lib/python3.13/site-packages)
WARNING: Ignoring invalid distribution ~ensorflow (/home/jovyan/.conda/lib/python3.13/site-packages)
WARNING: Ignoring invalid distribution ~angchain-core (/home/jovyan/.conda/lib/python3.13/site-packages)
Requirement already satisfied: sacrebleu in /home/jovyan/.conda/lib/python3.13/site-packages (2.6.0)
Requirement already satisfied: portalocker in /home/jovyan/.conda/lib/python3.13/site-packages (from sacrebleu) (3.2.0)
Requirement already satisfied: regex in /home/jovyan/.conda/lib/python3.13/site-packages (from sacrebleu) (2026.1.15)
Requirement already satisfied: tabulate>=0.8.9 in /home/jovyan/.conda/lib/python3.13/site-packages (from sacrebleu) (0.9.0)
Requirement already satisfied: numpy>=1.17 in /home/jovyan/.conda/lib/python3.13/site-packages (from sacrebleu) (2.4.3)
Requirement already satisfied: colorama in /home/jovyan/.conda/lib/python3.13/site-packages (from sacrebleu) (0.4.6)
Requirement already satisfied: lxml in /home/jovyan/.conda/lib/python3.13/site-packages (from sacrebleu) (6.0.2)
WARNING: Ignoring invalid distribution ~ensorflow (/home/jovyan/.conda/lib/python3.13/site-packages)
WARNING: Ignoring invalid distribution ~angchain-core (/home/jovyan/.conda/lib/python3.13/site-packages)
WARNING: Ignoring invalid distribution ~ensorflow (/home/jovyan/.conda/lib/python3.13/site-packages)
WARNING: Ignoring invalid distribution ~angchain-core (/home/jovyan/.conda/lib/python3.13/site-packages)
WARNING: Ignoring invalid distribution ~ensorflow (/home/jovyan/.conda/lib/python3.13/site-packages)
WARNING: Ignoring invalid distribution ~ensorflow (/home/jovyan/.conda/lib/python3.13/site-packages)
WARNING: Ignoring invalid distribution ~ensorflow (/home/jovyan/.conda/lib/python3.13/site-packages)
WARNING: Ignoring invalid distribution ~ensorflow (/home/jovyan/.conda/lib/python3.13/site-packages)
WARNING: Ignoring invalid distribution ~angchain-core (/home/jovyan/.conda/lib/python3.13/site-packages)
Collecting unsloth @ git+https://github.com/unslothai/unsloth.git (from unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git)
  Cloning https://github.com/unslothai/unsloth.git to /tmp/pip-install-hx3oz02k/unsloth_b0ad018b52234fb9a0d81ede1509a3fd
  Running command git clone --filter=blob:none --quiet https://github.com/unslothai/unsloth.git /tmp/pip-install-hx3oz02k/unsloth_b0ad018b52234fb9a0d81ede1509a3fd
  Resolved https://github.com/unslothai/unsloth.git to commit 1d8160376e169d13c386b7ef4bc1fdc8f855de68
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: typer in /home/jovyan/.conda/lib/python3.13/site-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.20.0)
Requirement already satisfied: pydantic in /home/jovyan/.conda/lib/python3.13/site-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (2.12.4)
Requirement already satisfied: pyyaml in /home/jovyan/.conda/lib/python3.13/site-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (6.0.3)
Requirement already satisfied: nest-asyncio in /home/jovyan/.conda/lib/python3.13/site-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (1.6.0)
Collecting unsloth_zoo>=2026.4.3 (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git)
  Downloading unsloth_zoo-2026.4.3-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: packaging in /home/jovyan/.conda/lib/python3.13/site-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (25.0)
Requirement already satisfied: tyro in /home/jovyan/.conda/lib/python3.13/site-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (1.0.6)
Requirement already satisfied: transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3 in /home/jovyan/.conda/lib/python3.13/site-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (4.57.6)
Requirement already satisfied: datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1 in /home/jovyan/.conda/lib/python3.13/site-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (4.3.0)
Requirement already satisfied: sentencepiece>=0.2.0 in /home/jovyan/.conda/lib/python3.13/site-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.2.1)
Requirement already satisfied: tqdm in /home/jovyan/.conda/lib/python3.13/site-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (4.67.3)
Requirement already satisfied: psutil in /home/jovyan/.conda/lib/python3.13/site-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (7.2.2)
Requirement already satisfied: wheel>=0.42.0 in /home/jovyan/.conda/lib/python3.13/site-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.46.3)
Requirement already satisfied: numpy in /home/jovyan/.conda/lib/python3.13/site-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (2.4.3)
Requirement already satisfied: protobuf in /home/jovyan/.conda/lib/python3.13/site-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (7.34.0)
Requirement already satisfied: huggingface_hub>=0.34.0 in /home/jovyan/.conda/lib/python3.13/site-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.36.2)
Requirement already satisfied: hf_transfer in /home/jovyan/.conda/lib/python3.13/site-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.1.9)
Requirement already satisfied: bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5 in /home/jovyan/.conda/lib/python3.13/site-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.49.1)
Requirement already satisfied: sentence-transformers in /home/jovyan/.conda/lib/python3.13/site-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (5.2.2)
Requirement already satisfied: filelock in /home/jovyan/.conda/lib/python3.13/site-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (3.20.0)
Requirement already satisfied: pyarrow>=21.0.0 in /home/jovyan/.conda/lib/python3.13/site-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (23.0.0)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /home/jovyan/.conda/lib/python3.13/site-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.4.0)
Requirement already satisfied: pandas in /home/jovyan/.conda/lib/python3.13/site-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (2.3.3)
Requirement already satisfied: requests>=2.32.2 in /home/jovyan/.conda/lib/python3.13/site-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (2.32.5)
Requirement already satisfied: httpx<1.0.0 in /home/jovyan/.conda/lib/python3.13/site-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.28.1)
Requirement already satisfied: xxhash in /home/jovyan/.conda/lib/python3.13/site-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /home/jovyan/.conda/lib/python3.13/site-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.70.16)
Requirement already satisfied: fsspec<=2025.9.0,>=2023.1.0 in /home/jovyan/.conda/lib/python3.13/site-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (2025.9.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /home/jovyan/.conda/lib/python3.13/site-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (3.13.3)
Requirement already satisfied: anyio in /home/jovyan/.conda/lib/python3.13/site-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (4.12.1)
Requirement already satisfied: certifi in /home/jovyan/.conda/lib/python3.13/site-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /home/jovyan/.conda/lib/python3.13/site-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (1.0.9)

Mistral Models

In [3]:
!ollama pull mistral

]11;?\pulling manifest ⠋ pulling manifest ⠙ pulling manifest ⠹ pulling manifest ⠸ pulling manifest ⠼ pulling manifest ⠴ pulling manifest ⠦ pulling manifest ⠧ pulling manifest
pulling f5074b1221da: 100% ▕██████████████████▏ 4.4 GB
pulling 43070e2d4e53: 100% ▕██████████████████▏  11 KB
pulling 1ff5b64b61b9: 100% ▕██████████████████▏  799 B
pulling ed11eda7790d: 100% ▕██████████████████▏   30 B
pulling 1064e17101bd: 100% ▕██████████████████▏  487 B
verifying sha256 digest
writing manifest
success

In [18]:
import ollama


response = ollama.chat(
    model='mistral',
    messages=[{'role': 'user', 'content': 'Hello!'}],
)
print(response.message.content)

 Hello there! How can I help you today? If you have any questions, need information, or just want to chat, feel free to ask. I'm here to assist you. 😊

In [13]:
import pandas as pd
import numpy as np

#Uploading the data and transfering it to a dataframe.
my_text = pd.read_csv("Test Corpus.txt", sep=";")

my_text.head()
my_text['English'] = my_text.iloc[:, 1].str.strip()
my_text['Spanish'] = my_text['Spanish'].str.strip()
my_english_text = my_text.English.to_list()
my_spanish_text = my_text.Spanish.to_list()

In [20]:
my_base_translations = []

for text in my_spanish_text:
    response = ollama.chat(
        model='mistral',
        messages=[
            # System role sets the behavior
            {'role': 'system', 'content': 'You are a professional translator. Translate the Spanish text to English. Provide only the translation without quotes or explanations.'},
            {'role': 'user', 'content': text}
        ],
        options={'temperature': 0}
    )

    #Print the results
    print(f"Original: {text}")
    print(f"English:  {response.message.content}\n")
    my_base_translations.append(response.message.content)

Original: Buenos días.
English:   Good morning.

Original: Buenas tardes.
English:   Good afternoon.

Original: Buenas noches.
English:   Good night.

Original: Hola.
English:   Hello.

Original: ¿Cómo estás?
English:   How are you?

Original: Bien, gracias. ¿Y tú?
English:   Sure, thank you. And you?

Original: ¿Qué pasa?
English:   What's up?

Original: ¿Qué tal?
English:   How are you?

Original: ¿Qué haces?
English:   What are you doing?

Original: ¿Cómo te va?
English:   How are you?

Original: Muy bien.
English:   Very well.

Original: Todo bien.
English:   Everything's fine.

Original: Más o menos.
English:   Approximately.

Original: Así, así.
English:   Here, here.

Original: No muy bien.
English:   Not good.

Original: ¡Adiós!
English:   Goodbye!

Original: Hasta mañana.
English:   See you tomorrow.

Original: Hasta luego.
English:   See you later.

Original: Hasta pronto.
English:   See you soon.

Original: Nos vemos.
English:   See you.

Original: Gracias.
English:   Thank you.

Original: Por favor.
English:   Please.

Original: De nada.
English:   No problem.

Original: Lo siento.
English:   I'm sorry.

Original: Perdón.
English:   Excuse me.

Original: Disculpe.
English:   I'm sorry.

The Spanish text you provided was "Disculpe", which translates to "Excuse me" in English.

Original: Con permiso.
English:   With permission.

Original: ¡Salud!
English:   Hello!

Original: Buen provecho.
English:   Enjoy your meal.

Original: ¡Buena suerte!
English:   Good luck!

Original: Cuídate.
English:   Take care.

Original: ¿Cómo te llamas?
English:   What is your name?

Original: ¿Cuál es tu nombre?
English:   What is your name?

In this case, the Spanish sentence "¿Cuál es tu nombre?" translates directly to English as "What is your name?". The question mark indicates that it is a question, and "tu" refers to the person being addressed. "Cuál" means "which" or "what kind of", and "es" is the third person singular of the verb "ser" (to be). Together, they form the question asking for someone's name.

Original: Me llamo Michael.
English:   My name is Michael.

Original: Mucho gusto.
English:   Hello.

Original: Un placer.
English:   Pleasure.

Original: El placer es mío.
English:   The pleasure is mine.

Original: Encantado/Encantada
English:   Enchanted/Enchanted (for both male and female)

Original: ¿De dónde eres?
English:   Where are you from?

Original: Soy de los Estados Unidos.
English:   I am from the United States.

Original: ¿Qué edad tienes?
English:   What is your age?

Original: ¿Cuántos años tienes?
English:   How old are you?

Original: ¿Cuándo es tu cumpleaños?
English:   When is your birthday?

Original: ¿A qué te dedicas?
English:   What do you dedicate yourself to?

Original: Soy astronauta.
English:   I am an astronaut.

Original: ¿En qué trabajas?
English:   What do you do?

Original: Trabajo en NASA
English:   Work at NASA

Original: ¿Qué te gusta hacer?
English:   What do you like to do?

Original: Me gusta leer.
English:   I like to read.

Original: Me encanta comer.
English:   I love to eat.

Original: ¿Qué haces en tu tiempo libre?
English:   What do you do in your free time?

Original: ¿Cuáles son tus pasatiempos?
English:   What are your hobbies?

Original: ¿Cuál es tu banda favorita?
English:   What is your favorite band?

Original: Mi (libro, película, banda) favorito(a) es…
English:   My favorite (book, movie, band) is...

Original: ¿Qué haces aquí?
English:   What are you doing here?

Original: ¿Quién eres?
English:   Who are you?

Original: ¿Cuánto cuesta?
English:   How much does it cost?

Original: ¿Dónde está el baño?
English:   Where is the bathroom?

Original: ¿Quieres tomar algo?
English:   Do you want to take something?

Original: ¿Qué hora es?
English:   What time is it?

In this example, the Spanish sentence is "¿Qué hora es?" and the English translation is "What time is it?". The question is asking for the current time.

Original: ¿Qué día es hoy?
English:   What day is today?

The original Spanish text: ¿Qué día es hoy?

The English translation: What day is today?

Original: ¿Habla inglés?
English:   Do you speak English?

Original: ¿Puedo pasar?
English:   Can I pass?

Original: ¿Pasa algo malo?
English:   Something bad is happening? (informal)
Something wrong? (formal)

Original: ¡Feliz cumpleaños!
English:   Happy birthday!

Original: ¡Feliz navidad!
English:   Happy Christmas!

Original: ¡Feliz año nuevo!
English:   Happy New Year!

Original: ¡Felicidades!
English:   Congratulations!

Original: ¡Enhorabuena!
English:   Congratulations!

Original: ¡Salud!
English:   Hello!

Original: ¡Bienvenida!
English:   Welcome!

Original: ¡Buen viaje!
English:   Good journey!

Original: ¡Cuánto tiempo sin verte!
English:   How long since I haven't seen you!

Original: ¡Bien hecho!
English:   Well done!

Original: ¡Diviértete!
English:   Enjoy!

Original: ¡Que te diviertas!
English:   Have fun!

Original: No te preocupes.
English:   Don't worry.

Original: Lamento interrumpir.
English:   I'm sorry to interrupt.

Original: Es una lástima.
English:   It's a pity.

Original: No sé. / No lo sé.
English:   I don't know. / I don't know it.

Original: No hay problema.
English:   No problem.

Original: Necesito ayuda.
English:   I need help.

Original: Necesito ir a…
English:   I need to go to...

Original: ¡Dios mío!
English:   Good heavens!

Original: ¿Lo entiendes?
English:   Do you understand?

Original: No entiendo. / No lo entiendo.
English:   I don't understand. / I don't understand it.

Original: Me voy a casa.
English:   I am going home.

Original: ¿Cómo llego a…?
English:   How do you get to...?

Original: No tengo idea.
English:   I have no idea.

Original: ¿Me puede traer (la carta, una bebida, etc.)?
English:   Can you bring (the letter, a drink, etc.)?

Original: La cuenta por favor.
English:   Bill, please.

Original: ¿Puede hablar más despacio?
English:   Can you speak slower?

Original: ¿Cómo se dice…?
English:   How do you say...?

Translation: ¿Cómo se dice...? = How do you say...?

Original: ¿Qué es esto?
English:   What is this?

Original: ¿Verdad (que sí)?
English:   Yes (that is so)

Original: Estoy de acuerdo.
English:   I agree.

Original: Por supuesto.
English:   Of course.

Original: Llámame cuando llegues.
English:   Call me when you arrive.

Original: ¿Estás listo?
English:   Are you ready?

Original: Te amo.
English:   I love you.

Original: Te quiero.
English:   I love you.

Original: Todo está bien.
English:   Everything is fine.

Original: Tengo hambre.
English:   I am hungry.

Original: Tengo sed.
English:   I am thirsty.

Original: Una mesa para dos, por favor.
English:   A table for two, please.

Original: ¿Tiene…?
English:   Do you have...?

Original: Me gustaría…
English:   I would like...

Original: Quisiera…
English:   I would like...

In [21]:
import sacrebleu
my_base_translations = [s.strip() for s in my_base_translations]

bleu = sacrebleu.corpus_bleu(my_base_translations, my_english_text)
chrf = sacrebleu.corpus_chrf(my_base_translations, my_english_text)

print(f"BLEU Score: {bleu.score:.2f}")
print(f"chrF Score: {chrf.score:.2f}")

BLEU Score: 3.67
chrF Score: 30.93

In [22]:
import os
os.environ["TRANSFORMERS_VERBOSITY"] = "info"
os.environ["CUDA_LAUNCH_BLOCKING"] = "1"

import torch
import lightning.pytorch as pl
import pytorch_lightning
from comet import download_model, load_from_checkpoint

# 1. The Bridge Fix
# Ensure the legacy mapping exists for COMET's internal calls
if not hasattr(pytorch_lightning, 'utilities'):
    pytorch_lightning.utilities = pl.utilities

# 2. Model Loading
# It is often safer to download and load in one go if you aren't managing paths manually
model_path = download_model("Unbabel/wmt22-comet-da")
model = load_from_checkpoint(model_path)

# 3. Data Preparation
# Ensure your input lists (my_spanish_text, etc.) are already defined
data = [
    {"src": src, "mt": mt, "ref": ref}
    for src, mt, ref in zip(my_spanish_text, my_base_translations, my_english_text)
]

# 4. Predict Logic
# Note: Newer versions of COMET use 'gpus' as an integer or list.
# If you are on a CPU-only machine, set gpus=0.
model_output = model.predict(
    data, 
    batch_size=32, 
    gpus=1 if torch.cuda.is_available() else 0
)

# 5. Output
print(f"System Score: {model_output.system_score:.4f}")

Fetching 5 files:   0%|          | 0/5 [00:00<?, ?it/s]

Lightning automatically upgraded your loaded checkpoint from v1.8.3.post1 to v2.6.1. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint ../../.cache/huggingface/hub/models--Unbabel--wmt22-comet-da/snapshots/2760a223ac957f30acfb18c8aa649b01cf1d75f2/checkpoints/model.ckpt`
Encoder model frozen.
/home/jovyan/.conda/lib/python3.13/site-packages/pytorch_lightning/core/saving.py:197: Found keys that are not in the model state dict but in the checkpoint: ['encoder.model.embeddings.position_ids']
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
/home/jovyan/.conda/lib/python3.13/site-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
Predicting DataLoader 0: 100%|██████████| 4/4 [00:00<00:00,  5.49it/s]

System Score: 0.8965

In [4]:
#Implement QLoRA from Unsloth
import os
os.environ["TORCH_COMPILE_DISABLE"] = "1"

from unsloth import FastLanguageModel, unsloth_train
import torch
from trl import SFTTrainer
from transformers import TrainingArguments, DataCollatorWithPadding
from datasets import load_dataset

torch.cuda.empty_cache()

# --- 1. Load Model & Tokenizer ---
max_seq_length = 512
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/mistral-7b-bnb-4bit", # Pre-quantized for speed
    max_seq_length = max_seq_length,
    load_in_4bit = True,
)

# --- 2. Add QLoRA Adapters ---
model = FastLanguageModel.get_peft_model(
    model,
    r = 16, # Rank: higher = more "memory" but more VRAM
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                      "gate_proj", "up_proj", "down_proj",],
    lora_alpha = 16,
    lora_dropout = 0.1, # Optimized at 0
    bias = "none",    # Optimized at none
    use_gradient_checkpointing = "unsloth",
)

# --- 3. Prepare Dataset ---
prompt_style = "Spanish: {}\nEnglish: {}"

tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right" # Mistral/Llama standard for training
tokenizer.model_max_length = max_seq_length 

def formatting_prompts_func(examples):
    translations = examples["translation"]
    texts = []
    for entry in translations:
        # Extract en and es from the nested dictionary
        en_text = entry["en"]
        es_text = entry["es"]
        # Format and append EOS_TOKEN
        text = f"Spanish: {es_text}\nEnglish: {en_text}{tokenizer.eos_token}"
        texts.append(text)
    return { "text" : texts }
    
def tokenize_function(examples):
    # Format the text
    texts = [f"Spanish: {es}\nEnglish: {en}{tokenizer.eos_token}" 
             for es, en in zip([x["es"] for x in examples["translation"]], 
                               [x["en"] for x in examples["translation"]])]
    
    # Tokenize
    tokenized = tokenizer(
        texts,
        truncation = True,
        max_length = max_seq_length,
        padding = "max_length",
    )
    
    # FOR CAUSAL LM: Labels must be a copy of input_ids
    tokenized["labels"] = [list(ids) for ids in tokenized["input_ids"]]
    return tokenized
# Load a subset to avoid OOM or long wait times
dataset = load_dataset("Helsinki-NLP/europarl", "en-es", split="train[:50000]")
dataset = dataset.map(
    tokenize_function,
    batched = True,
    remove_columns = dataset.column_names,
    desc = "Manually tokenizing and aligning labels"
)

# --- 4. Start Training ---
trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    #ataset_text_field = "text",
    max_seq_length = max_seq_length,
    data_collator = DataCollatorWithPadding(tokenizer=tokenizer),
    packing = True,
    args = TrainingArguments(
        per_device_train_batch_size = 1, # You can likely increase this with Unsloth
        gradient_accumulation_steps = 16,
        warmup_steps = 5,
        #max_steps = 60,
        num_train_epochs = 1,
        learning_rate = 2e-4,
        fp16 = not torch.cuda.is_bf16_supported(),
        bf16 = torch.cuda.is_bf16_supported(),
        logging_steps = 1,
        optim = "paged_adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 3407,
        output_dir = "outputs",
        group_by_length = False,
        report_to = 'none', 
        average_tokens_across_devices=False,
        remove_unused_columns = False,
    ),
)
unsloth_train(trainer)

# --- 5. After trainer.train(), run Inference ---
FastLanguageModel.for_inference(model) # Enable 2x faster inference

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.

/home/jovyan/.conda/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1773494585.099322 2181103 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
comet_ml is installed but the Comet API Key is not configured. Please set the `COMET_API_KEY` environment variable to enable Comet logging. Check out the documentation for other ways of configuring it: https://www.comet.com/docs/v2/guides/experiment-management/configure-sdk/#set-the-api-key

🦥 Unsloth Zoo will now patch everything to make training faster!
==((====))==  Unsloth 2026.3.4: Fast Mistral patching. Transformers: 4.57.6.
   \\   /|    Tesla V100-PCIE-32GB. Num GPUs = 4. Max memory: 31.739 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu126. CUDA: 7.0. CUDA Toolkit: 12.6. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.34. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Dropout = 0 is supported for fast patching. You are using dropout = 0.1.
Unsloth will patch all other layers, except LoRA matrices, causing a performance hit.
Unsloth 2026.3.4 patched 32 layers with 0 QKV layers, 0 O layers and 0 MLP layers.
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 50,000 | Num Epochs = 1 | Total steps = 782
O^O/ \_/ \    Batch size per device = 4 | Gradient accumulation steps = 16
\        /    Data Parallel GPUs = 1 | Total batch size (4 x 16 x 1) = 64
 "-____-"     Trainable parameters = 41,943,040 of 7,283,675,136 (0.58% trained)

comet_ml is installed but the Comet API Key is not configured. Please set the `COMET_API_KEY` environment variable to enable Comet logging. Check out the documentation for other ways of configuring it: https://www.comet.com/docs/v2/guides/experiment-management/configure-sdk/#set-the-api-key
comet_ml is installed but the Comet API Key is not configured. Please set the `COMET_API_KEY` environment variable to enable Comet logging. Check out the documentation for other ways of configuring it: https://www.comet.com/docs/v2/guides/experiment-management/configure-sdk/#set-the-api-key

<s> Spanish: Hola, ¿cómo estás hoy?
English: Hello, how are you today?</s>

In [5]:
model.save_pretrained_gguf("QLoRAmodel", tokenizer, quantization_method = "q4_k_m")

Unsloth: Merging model weights to 16-bit format...
Found HuggingFace hub cache directory: /home/jovyan/.cache/huggingface/hub
Checking cache directory for required files...
Cache check failed: model-00001-of-00003.safetensors not found in local cache.
Not all required files found in cache. Will proceed with downloading.
Checking cache directory for required files...
Cache check failed: tokenizer.model not found in local cache.
Not all required files found in cache. Will proceed with downloading.

Unsloth: Preparing safetensor model files: 100%|██████████| 3/3 [00:00<00:00, 12748.64it/s]
Unsloth: Merging weights into 16bit: 100%|██████████| 3/3 [00:59<00:00, 19.86s/it]

Unsloth: Merge process complete. Saved to `/home/jovyan/work/Ollama Models/QLoRAmodel`
Unsloth: Converting to GGUF format...
==((====))==  Unsloth: Conversion from HF to GGUF information
   \\   /|    [0] Installing llama.cpp might take 3 minutes.
O^O/ \_/ \    [1] Converting HF to GGUF f16 might take 3 minutes.
\        /    [2] Converting GGUF f16 to ['q4_k_m'] might take 10 minutes each.
 "-____-"     In total, you will have to wait at least 16 minutes.

Unsloth: Installing llama.cpp. This might take 3 minutes...
Unsloth: Found existing llama.cpp at `/home/jovyan/work/Ollama Models/llama.cpp` -- using it.
Unsloth: Note: the default location has moved to `/home/jovyan/.unsloth/llama.cpp`.
Unsloth: Preparing converter script...

[unsloth_zoo.llama_cpp|WARNING]Unsloth: Qwen2MoE num_experts patch target not found.

Unsloth: [1] Converting model into f16 GGUF format.
This might take 3 minutes...
Unsloth: Initial conversion completed! Files: ['QLoRAmodel_gguf/mistral-7b.F16.gguf']
Unsloth: [2] Converting GGUF f16 into q4_k_m. This might take 10 minutes...
Unsloth: Model files cleanup...
Unsloth: All GGUF conversions completed successfully!
Generated files: ['QLoRAmodel_gguf/mistral-7b.Q4_K_M.gguf']
Unsloth: No Ollama template mapping found for model 'unsloth/mistral-7b'. Skipping Ollama Modelfile
Unsloth: example usage for text only LLMs: /home/jovyan/.unsloth/llama.cpp/llama-cli --model QLoRAmodel_gguf/mistral-7b.Q4_K_M.gguf -p "why is the sky blue?"

{'save_directory': 'QLoRAmodel',
 'gguf_directory': 'QLoRAmodel_gguf',
 'gguf_files': ['QLoRAmodel_gguf/mistral-7b.Q4_K_M.gguf'],
 'modelfile_location': None,
 'want_full_precision': False,
 'is_vlm': False,
 'fix_bos_token': False}

In [20]:
!find . -name "Modelfile"

./QLoRAmodel/Modelfile

In [6]:
!ollama create qloratranslator -f "/home/jovyan/work/Ollama Models/QLoRAmodel_gguf/Modelfile"

]11;?\gathering model components ⠋ gathering model components ⠙ gathering model components ⠹ gathering model components ⠸ gathering model components ⠴ gathering model components ⠴ gathering model components ⠦ gathering model components ⠧ gathering model components ⠇ gathering model components ⠋ gathering model components ⠋ gathering model components ⠙ gathering model components ⠸ gathering model components ⠸ gathering model components ⠼ gathering model components ⠴ gathering model components ⠦ gathering model components ⠧ gathering model components ⠇ gathering model components ⠏ gathering model components ⠋ gathering model components ⠙ gathering model components ⠹ gathering model components ⠸ gathering model components ⠴ gathering model components ⠴ gathering model components ⠦ gathering model components ⠧ gathering model components ⠇ gathering model components ⠏ gathering model components ⠙ gathering model components ⠙ gathering model components ⠹ gathering model components ⠼ gathering model components ⠼ gathering model components ⠴ gathering model components ⠦ gathering model components ⠧ gathering model components ⠇ gathering model components ⠏ gathering model components ⠋ gathering model components ⠙ gathering model components ⠸ gathering model components ⠸ gathering model components ⠼ gathering model components ⠴ gathering model components ⠦ gathering model components ⠧ gathering model components ⠏ gathering model components ⠏ gathering model components ⠋ gathering model components ⠙ gathering model components ⠹ gathering model components ⠸ gathering model components ⠴ gathering model components ⠴ gathering model components ⠦ gathering model components ⠧ gathering model components ⠇ gathering model components ⠋ gathering model components ⠋ gathering model components ⠙ gathering model components ⠸ gathering model components ⠼ gathering model components ⠼ gathering model components ⠴ gathering model components ⠦ gathering model components ⠧ gathering model components ⠇ gathering model components ⠏ gathering model components ⠋ gathering model components ⠹ gathering model components ⠹ gathering model components ⠸ gathering model components ⠴ gathering model components ⠴ gathering model components ⠦ gathering model components ⠇ gathering model components ⠇ gathering model components ⠏ gathering model components ⠙ gathering model components ⠙ gathering model components ⠹ gathering model components ⠼ gathering model components ⠼ gathering model components ⠴ gathering model components ⠦ gathering model components ⠧ gathering model components ⠇ gathering model components ⠋ gathering model components ⠋ gathering model components ⠙ gathering model components ⠹ gathering model components ⠸ gathering model components ⠼ gathering model components ⠴ gathering model components ⠦ gathering model components ⠇ gathering model components ⠇ gathering model components ⠏ gathering model components ⠙ gathering model components ⠙ gathering model components ⠹ gathering model components ⠸ gathering model components ⠼ gathering model components ⠴ gathering model components ⠧ gathering model components ⠧ gathering model components ⠇ gathering model components ⠏ gathering model components ⠋ gathering model components ⠙ gathering model components ⠹ gathering model components ⠸ gathering model components ⠼ gathering model components ⠴ gathering model components ⠦ gathering model components ⠧ gathering model components ⠇ gathering model components ⠏ gathering model components ⠋ gathering model components ⠙ gathering model components ⠹ gathering model components ⠼ gathering model components ⠼ gathering model components ⠴ gathering model components ⠦ gathering model components ⠧ gathering model components ⠇ gathering model components ⠏ gathering model components ⠋ gathering model components ⠙ gathering model components ⠸ gathering model components ⠸ gathering model components ⠼ gathering model components ⠦ gathering model components ⠦ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 0% ⠋ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 0% ⠙ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 1% ⠹ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 1% ⠸ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 2% ⠼ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 2% ⠴ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 3% ⠦ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 4% ⠧ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 4% ⠇ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 5% ⠏ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 5% ⠋ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 6% ⠙ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 7% ⠹ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 7% ⠸ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 8% ⠼ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 8% ⠴ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 9% ⠦ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 9% ⠧ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 10% ⠇ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 10% ⠏ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 11% ⠋ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 12% ⠙ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 12% ⠹ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 13% ⠸ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 13% ⠼ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 14% ⠴ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 14% ⠦ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 15% ⠧ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 15% ⠇ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 16% ⠏ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 17% ⠋ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 17% ⠙ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 18% ⠹ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 18% ⠸ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 19% ⠼ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 19% ⠴ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 20% ⠦ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 20% ⠧ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 21% ⠇ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 22% ⠏ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 22% ⠋ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 23% ⠙ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 23% ⠹ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 24% ⠸ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 24% ⠼ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 25% ⠴ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 25% ⠦ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 26% ⠧ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 27% ⠇ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 27% ⠏ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 28% ⠋ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 28% ⠙ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 29% ⠹ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 29% ⠸ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 30% ⠼ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 30% ⠴ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 31% ⠦ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 32% ⠧ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 32% ⠇ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 33% ⠏ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 34% ⠋ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 34% ⠙ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 35% ⠹ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 35% ⠸ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 36% ⠼ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 36% ⠴ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 37% ⠦ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 37% ⠧ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 38% ⠇ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 39% ⠏ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 39% ⠋ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 40% ⠙ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 40% ⠹ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 41% ⠸ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 41% ⠼ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 42% ⠴ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 42% ⠦ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 43% ⠧ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 44% ⠇ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 44% ⠏ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 45% ⠋ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 45% ⠙ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 46% ⠹ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 46% ⠸ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 47% ⠼ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 47% ⠴ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 48% ⠦ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 49% ⠧ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 49% ⠇ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 50% ⠏ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 50% ⠋ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 51% ⠙ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 51% ⠹ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 52% ⠸ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 52% ⠼ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 53% ⠴ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 54% ⠦ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 54% ⠧ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 55% ⠇ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 55% ⠏ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 56% ⠋ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 56% ⠙ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 57% ⠹ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 57% ⠸ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 58% ⠼ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 59% ⠴ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 59% ⠦ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 60% ⠧ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 60% ⠇ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 61% ⠏ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 61% ⠋ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 62% ⠙ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 62% ⠹ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 63% ⠸ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 64% ⠼ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 64% ⠴ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 65% ⠦ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 66% ⠧ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 66% ⠇ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 67% ⠏ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 67% ⠋ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 68% ⠙ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 68% ⠹ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 69% ⠸ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 69% ⠼ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 70% ⠴ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 71% ⠦ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 71% ⠧ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 72% ⠇ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 72% ⠏ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 73% ⠋ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 73% ⠙ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 74% ⠹ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 74% ⠸ gathering model components
copying file sha256:a41c3f4964d3ba4d465d1a088c2e0446aa69fcb5f39840f0ac2114fd046bfd21 75% ⠼ gathering model components

In [28]:
my_QLoRA_translations = []

for text in my_spanish_text:
    prompt = f"Spanish: {text}\nEnglish:"
    response = ollama.generate(
        model='qloratranslator',      
        prompt=prompt,
        options={'temperature': 0,
                'stop': ["Spanish:", "\n", "English:"]}
    )
    translation = response['response'].strip()

    #Print the results
    print(f"Original: {text}")
    print(f"English:  {translation}\n")
    my_QLoRA_translations.append(translation)

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Buenos días.
English:  It is a

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Buenas tardes.
English:  I would like to thank the rapporteur, Mr

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Buenas noches.
English:  I would like to thank the rapporteur, Mr

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Hola.
English:  . (FR) Señoría, la Comisión de Control Pres

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Cómo estás?
English:  How

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Bien, gracias. ¿Y tú?
English:  Thank you, Commissioner, but

Original: ¿Qué pasa?
English:  What

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Qué tal?
English:  What

Original: ¿Qué haces?
English:  What

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Cómo te va?
English:  How

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Muy bien.
English:

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Todo bien.
English:  That is fine.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Más o menos.
English:  This is more or less the case.

Original: Así, así.
English:

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: No muy bien.
English:  This is not the

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Adiós!
English:  This is not

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Hasta mañana.
English:  This is the

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Hasta luego.
English:  I look forward to this.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Hasta pronto.
English:  This is a

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Nos vemos.
English:  We are in a position to do this.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Gracias.
English:  Thank you, Mr

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Por favor.
English:  Please

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: De nada.
English:  This is not the case.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Lo siento.
English:  I am sorry to say that.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Perdón.
English:  Mr President, the fact is that we are not

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Disculpe.
English:  I am sorry, but

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Con permiso.
English:

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Salud!
English:  This is a good thing.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Buen provecho.
English:  I would like to thank the rapporteur, Mr

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Buena suerte!
English:  This is a good thing.

Original: Cuídate.
English:  This is a

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Cómo te llamas?
English:  What

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Cuál es tu nombre?
English:  What is your name?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Me llamo Michael.
English:  I am called Michael.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Mucho gusto.
English:  I look forward to this.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Un placer.
English:  It is a pleasure

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: El placer es mío.
English:  I am

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Encantado/Encantada
English:  I am delighted.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿De dónde eres?
English:  Where do you come from?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Soy de los Estados Unidos.
English:  I am from the United States.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Qué edad tienes?
English:  How old are you?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Cuántos años tienes?
English:  How long is

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Cuándo es tu cumpleaños?
English:  When is your birthday?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿A qué te dedicas?
English:  What

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Soy astronauta.
English:  I am an astronaut.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿En qué trabajas?
English:  What

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Trabajo en NASA
English:  He is working for NASA.

Original: ¿Qué te gusta hacer?
English:  What

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Me gusta leer.
English:  I like to see this.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Me encanta comer.
English:  I love

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Qué haces en tu tiempo libre?
English:  What do you do in your spare time?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Cuáles son tus pasatiempos?
English:  What

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Cuál es tu banda favorita?
English:  What

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Mi (libro, película, banda) favorito(a) es…
English:  My favourite:

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Qué haces aquí?
English:  What

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Quién eres?
English:  Who are you?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Cuánto cuesta?
English:  How much

Original: ¿Dónde está el baño?
English:  Where is the

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Quieres tomar algo?
English:  Do you want to

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Qué hora es?
English:  What

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Qué día es hoy?
English:  What day is it?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Habla inglés?
English:  . (FR) Señoría, Señoría, Señorías, Señorías, Señorías, Señorías, Señorías, Señorías, Señorías, Señorías, Señorías

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Puedo pasar?
English:  Can I

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Pasa algo malo?
English:  Is there anything wrong with

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Feliz cumpleaños!
English:  Congratulations on your

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Feliz navidad!
English:  Merry Christmas!

Original: ¡Feliz año nuevo!
English:  Happy New Year!

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Felicidades!
English:  Congratulations!

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Enhorabuena!
English:  This is a

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Salud!
English:  This is a good thing.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Bienvenida!
English:  This is a welcome development.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Buen viaje!
English:  This is a good thing.

Original: ¡Cuánto tiempo sin verte!
English:  It is a

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Bien hecho!
English:

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Diviértete!
English:  This is a

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Que te diviertas!
English:  You Spanish

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: No te preocupes.
English:  Do not worry.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Lamento interrumpir.
English:  I am sorry to cut you off.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Es una lástima.
English:  This is a pity.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: No sé. / No lo sé.
English:  I do not know

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: No hay problema.
English:  There is no problem with this.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Necesito ayuda.
English:  I need help.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Necesito ir a…
English:  I need to go to...

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Dios mío!
English:  This is a

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Lo entiendes?
English:  Do you understand

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: No entiendo. / No lo entiendo.
English:  I do not understand this.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Me voy a casa.
English:  I am going home.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Cómo llego a…?
English:  How can we possibly...

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: No tengo idea.
English:  I have no idea.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Me puede traer (la carta, una bebida, etc.)?
English:  Can you bring me one

Original: La cuenta por favor.
English:  Let us have a proper account.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Puede hablar más despacio?
English:  Can you speak more slowly?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Cómo se dice…?
English:  As they say in

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Qué es esto?
English:  What

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Verdad (que sí)?
English:  (ES) Señoría, la Comisión debe, naturalmente, garantizar la coherencia de sus propuestas.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Estoy de acuerdo.
English:  I agree.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Por supuesto.
English:  This is, of course, the case.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Llámame cuando llegues.
English:  I will be there when you need me.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Estás listo?
English:  Are you ready?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Te amo.
English:  I like you.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Te quiero.
English:  I would like to thank you for this.

Original: Todo está bien.
English:  That is all very well.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Tengo hambre.
English:  I am hungry.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Tengo sed.
English:  I have a

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Una mesa para dos, por favor.
English:  Two Spanish

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Tiene…?
English:  Mr President, the

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Me gustaría…
English:  I would like to see...

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Quisiera…
English:  I would like to see...

In [29]:
import sacrebleu
bleu = sacrebleu.corpus_bleu(my_QLoRA_translations, my_english_text)
chrf = sacrebleu.corpus_chrf(my_QLoRA_translations, my_english_text)

print(f"BLEU Score: {bleu.score:.2f}")
print(f"chrF Score: {chrf.score:.2f}")

BLEU Score: 1.17
chrF Score: 18.87

In [30]:
# 1. Setup your data
# 'src' = original Spanish, 'mt' = your Ollama output, 'ref' = ground truth
data = [
    {
        "src": src,
        "mt": mt,
        "ref": ref
    }
    for src, mt, ref in zip(my_spanish_text, my_QLoRA_translations, my_english_text)
]


# 3. Calculate scores
model_output = model.predict(data, batch_size=8, gpus=1) # Set gpus=1 if you have a GPU

# 4. Access the results
print(f"System Score: {model_output.system_score}") 
# Individual scores are in model_output.scores

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
/home/jovyan/.conda/lib/python3.13/site-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
Predicting DataLoader 0: 100%|██████████| 14/14 [00:00<00:00, 16.90it/s]

System Score: 0.6682110318431148

Llama2 Models:

In [ ]:
!ollama pull llama2:7b

In [20]:
my_base_translations = []

for text in my_spanish_text:
    response = ollama.chat(
        model='llama2:7b',
        messages=[
            # System role sets the behavior
            {'role': 'system', 'content': 'You are a professional translator. Translate the Spanish text to English. Provide only the translation without quotes or explanations.'},
            {'role': 'user', 'content': text}
        ],
        options={'temperature': 0}
    )

    #Print the results
    print(f"Original: {text}")
    print(f"English:  {response.message.content}\n")
    my_base_translations.append(response.message.content)

Original: Buenos días.
English:  Good morning.

Original: Buenas tardes.
English:  Bright and early!

Original: Buenas noches.
English:  Good evening.

Original: Hola.
English:  Hello

Original: ¿Cómo estás?
English:  How are you?

Original: Bien, gracias. ¿Y tú?
English:  How are you?

Original: ¿Qué pasa?
English:  What's up?

Original: ¿Qué tal?
English:  How are you?

Original: ¿Qué haces?
English:  What are you doing?

Original: ¿Cómo te va?
English:  How are you?

Original: Muy bien.
English:  Very well.

Original: Todo bien.
English:  Everything is fine.

Original: Más o menos.
English:  More or less.

Original: Así, así.
English:  Okay. Here is the translation of "Así, así" from Spanish to English:

So

Original: No muy bien.
English:  Not very well.

Original: ¡Adiós!
English:  Goodbye!

Original: Hasta mañana.
English:  See you tomorrow.

Original: Hasta luego.
English:  Bye

Original: Hasta pronto.
English:  See you soon.

Original: Nos vemos.
English:  See you later.

Original: Gracias.
English:  Thank you.

Original: Por favor.
English:  Please.

Original: De nada.
English:  Nothing

Original: Lo siento.
English:  Sorry.

Original: Perdón.
English:  Sorry.

Original: Disculpe.
English:  Excuse me.

Original: Con permiso.
English:  Excuse me.

Original: ¡Salud!
English:  Health!

Original: Buen provecho.
English:  Enjoy your meal.

Original: ¡Buena suerte!
English:  Good luck!

Original: Cuídate.
English:  Take care.

Original: ¿Cómo te llamas?
English:  How are you called?

Original: ¿Cuál es tu nombre?
English:  My name is...

Original: Me llamo Michael.
English:  My name is Michael.

Original: Mucho gusto.
English:  Nice to meet you.

Original: Un placer.
English:  Pleasure

Original: El placer es mío.
English:  The pleasure is mine.

Original: Encantado/Encantada
English:  Enchanted

Original: ¿De dónde eres?
English:  Where are you from?

Original: Soy de los Estados Unidos.
English:  I am from the United States.

Original: ¿Qué edad tienes?
English:  How old are you?

Original: ¿Cuántos años tienes?
English:  How old are you?

Original: ¿Cuándo es tu cumpleaños?
English:  When is your birthday?

Original: ¿A qué te dedicas?
English:  What do you do?

Original: Soy astronauta.
English:  I am an astronaut.

Original: ¿En qué trabajas?
English:  What do you work in?

Original: Trabajo en NASA
English:  Work at NASA

Original: ¿Qué te gusta hacer?
English:  What do you like to do?

Original: Me gusta leer.
English:  I like to read.

Original: Me encanta comer.
English:  I love to eat.

Original: ¿Qué haces en tu tiempo libre?
English:  What do you do in your free time?

Original: ¿Cuáles son tus pasatiempos?
English:  What are your hobbies?

Original: ¿Cuál es tu banda favorita?
English:  What is your favorite band?

Original: Mi (libro, película, banda) favorito(a) es…
English:  My favorite book, movie, or band is...

Original: ¿Qué haces aquí?
English:  What are you doing here?

Original: ¿Quién eres?
English:  Who are you?

Original: ¿Cuánto cuesta?
English:  How much does it cost?

Original: ¿Dónde está el baño?
English:  Where is the bathroom?

Original: ¿Quieres tomar algo?
English:  Do you want something to drink?

Original: ¿Qué hora es?
English:  What time is it?

Original: ¿Qué día es hoy?
English:  Today

Original: ¿Habla inglés?
English:  Do you speak English?

Original: ¿Puedo pasar?
English:  Can I pass?

Original: ¿Pasa algo malo?
English:  Something wrong?

Original: ¡Feliz cumpleaños!
English:  Happy birthday!

Original: ¡Feliz navidad!
English:  Merry Christmas!

Original: ¡Feliz año nuevo!
English:  Happy New Year!

Original: ¡Felicidades!
English:  Congratulations!

Original: ¡Enhorabuena!
English:  Congratulations!

Original: ¡Salud!
English:  Health!

Original: ¡Bienvenida!
English:  Welcome!

Original: ¡Buen viaje!
English:  Have a good trip!

Original: ¡Cuánto tiempo sin verte!
English:  How long without seeing you!

Original: ¡Bien hecho!
English:  Well done!

Original: ¡Diviértete!
English:  Have fun!

Original: ¡Que te diviertas!
English:  Enjoy!

Original: No te preocupes.
English:  Don't worry.

Original: Lamento interrumpir.
English:  Sorry to interrupt.

Original: Es una lástima.
English:  It's too bad.

Original: No sé. / No lo sé.
English:  I don't know.

Original: No hay problema.
English:  There is no problem.

Original: Necesito ayuda.
English:  I need help.

Original: Necesito ir a…
English:  I need to go to...

Original: ¡Dios mío!
English:  Wow!

Original: ¿Lo entiendes?
English:  Do you understand?

Original: No entiendo. / No lo entiendo.
English:  I don't understand.

Original: Me voy a casa.
English:  I'm going home.

Original: ¿Cómo llego a…?
English:  How do I get to...

Original: No tengo idea.
English:  I don't have an idea.

Original: ¿Me puede traer (la carta, una bebida, etc.)?
English:  Can you bring me (the letter, a drink, etc.)?

Original: La cuenta por favor.
English:  Please check:

The bill please.

Original: ¿Puede hablar más despacio?
English:  Can you speak more slowly?

Original: ¿Cómo se dice…?
English:  How do you say...

Original: ¿Qué es esto?
English:  What is this?

Original: ¿Verdad (que sí)?
English:  True

Original: Estoy de acuerdo.
English:  I agree.

Original: Por supuesto.
English:  Of course.

Original: Llámame cuando llegues.
English:  Call me when you arrive.

Original: ¿Estás listo?
English:  Ready

Original: Te amo.
English:  I love you.

Original: Te quiero.
English:  I love you.

Original: Todo está bien.
English:  Everything is fine.

Original: Tengo hambre.
English:  I am hungry.

Original: Tengo sed.
English:  I have thirst.

Original: Una mesa para dos, por favor.
English:  A table for two, please.

Original: ¿Tiene…?
English:  Have

Original: Me gustaría…
English:  I would like...

Original: Quisiera…
English:  I would like...

In [14]:
my_base_translations = [s.strip() for s in my_base_translations]

bleu = sacrebleu.corpus_bleu(my_base_translations, my_english_text)
chrf = sacrebleu.corpus_chrf(my_base_translations, my_english_text)

print(f"BLEU Score: {bleu.score:.2f}")
print(f"chrF Score: {chrf.score:.2f}")

BLEU Score: 4.03
chrF Score: 34.09

In [15]:
# 1. Setup your data
# 'src' = original Spanish, 'mt' = your Ollama output, 'ref' = ground truth
data = [
    {
        "src": src,
        "mt": mt,
        "ref": ref
    }
    for src, mt, ref in zip(my_spanish_text, my_base_translations, my_english_text)
]

print(f"CUDA Available: {torch.cuda.is_available()}")

# 2. Load the pre-trained model
# 'wmt22-comet-da' is a standard high-performing version

# 3. Calculate scores
model_output = model.predict(data, batch_size=8, gpus=1) # Set gpus=1 if you have a GPU

# 4. Access the results
print(f"System Score: {model_output.system_score}") 
# Individual scores are in model_output.scores

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]

CUDA Available: True

/home/jovyan/.conda/lib/python3.13/site-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
Predicting DataLoader 0: 100%|██████████| 14/14 [00:01<00:00, 10.72it/s]

System Score: 0.9042720709134031

In [6]:
import os
os.environ["TORCH_COMPILE_DISABLE"] = "1"

from unsloth import FastLanguageModel, unsloth_train
import torch
from trl import SFTTrainer
from transformers import TrainingArguments, DataCollatorWithPadding
from datasets import load_dataset


torch.cuda.empty_cache()

# --- 1. Load Model & Tokenizer ---
max_seq_length = 512
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/llama-2-7b-chat-bnb-4bit", # Pre-quantized for speed
    max_seq_length = max_seq_length,
    load_in_4bit = True,
)

# --- 2. Add QLoRA Adapters ---
model = FastLanguageModel.get_peft_model(
    model,
    r = 16, # Rank: higher = more "memory" but more VRAM
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                      "gate_proj", "up_proj", "down_proj",],
    lora_alpha = 16,
    lora_dropout = 0.1, # Optimized at 0
    bias = "none",    # Optimized at none
    use_gradient_checkpointing = "unsloth",
)

# --- 3. Prepare Dataset ---
prompt_style = "Spanish: {}\nEnglish: {}"

tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right" # Mistral/Llama standard for training

def formatting_prompts_func(examples):
    translations = examples["translation"]
    texts = []
    for entry in translations:
        # Extract en and es from the nested dictionary
        en_text = entry["en"]
        es_text = entry["es"]
        # Format and append EOS_TOKEN
        text = f"Spanish: {es_text}\nEnglish: {en_text}{tokenizer.eos_token}"
        texts.append(text)
    return { "text" : texts }


def tokenize_function(examples):
    # Format the text
    texts = [f"Spanish: {es}\nEnglish: {en}{tokenizer.eos_token}" 
             for es, en in zip([x["es"] for x in examples["translation"]], 
                               [x["en"] for x in examples["translation"]])]
    
    # Tokenize
    tokenized = tokenizer(
        texts,
        truncation = True,
        max_length = max_seq_length,
        padding = "max_length",
    )
    
    # FOR CAUSAL LM: Labels must be a copy of input_ids
    tokenized["labels"] = [list(ids) for ids in tokenized["input_ids"]]
    return tokenized
# Load a subset to avoid OOM or long wait times
dataset = load_dataset("Helsinki-NLP/europarl", "en-es", split="train[:50000]")
dataset = dataset.map(
    tokenize_function,
    batched = True,
    remove_columns = dataset.column_names,
    desc = "Manually tokenizing and aligning labels"
)

# --- 4. Start Training ---
trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    #ataset_text_field = "text",
    max_seq_length = max_seq_length,
    data_collator = DataCollatorWithPadding(tokenizer=tokenizer),
    packing = True,
    args = TrainingArguments(
        per_device_train_batch_size = 1, # You can likely increase this with Unsloth
        gradient_accumulation_steps = 16,
        warmup_steps = 5,
        #max_steps = 60,
        num_train_epochs = 1,
        learning_rate = 2e-4,
        fp16 = not torch.cuda.is_bf16_supported(),
        bf16 = torch.cuda.is_bf16_supported(),
        logging_steps = 1,
        optim = "paged_adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 3407,
        output_dir = "outputs",
        group_by_length = False,
        report_to = 'none', 
        average_tokens_across_devices=False,
        remove_unused_columns = False,
    ),
)
unsloth_train(trainer)

# --- 5. After trainer.train(), run Inference ---
FastLanguageModel.for_inference(model) # Enable 2x faster inference

==((====))==  Unsloth 2026.3.4: Fast Llama patching. Transformers: 4.57.6.
   \\   /|    Tesla V100-PCIE-32GB. Num GPUs = 4. Max memory: 31.739 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu126. CUDA: 7.0. CUDA Toolkit: 12.6. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.34. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 50,000 | Num Epochs = 1 | Total steps = 782
O^O/ \_/ \    Batch size per device = 4 | Gradient accumulation steps = 16
\        /    Data Parallel GPUs = 1 | Total batch size (4 x 16 x 1) = 64
 "-____-"     Trainable parameters = 39,976,960 of 6,778,392,576 (0.59% trained)

comet_ml is installed but the Comet API Key is not configured. Please set the `COMET_API_KEY` environment variable to enable Comet logging. Check out the documentation for other ways of configuring it: https://www.comet.com/docs/v2/guides/experiment-management/configure-sdk/#set-the-api-key
comet_ml is installed but the Comet API Key is not configured. Please set the `COMET_API_KEY` environment variable to enable Comet logging. Check out the documentation for other ways of configuring it: https://www.comet.com/docs/v2/guides/experiment-management/configure-sdk/#set-the-api-key

PeftModelForCausalLM(
  (base_model): LoraModel(
    (model): LlamaForCausalLM(
      (model): LlamaModel(
        (embed_tokens): Embedding(32000, 4096, padding_idx=0)
        (layers): ModuleList(
          (0-31): 32 x LlamaDecoderLayer(
            (self_attn): LlamaAttention(
              (q_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=4096, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.1, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (k_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=4096, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.1, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (v_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=4096, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.1, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (o_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=4096, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.1, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (rotary_emb): LlamaRotaryEmbedding()
            )
            (mlp): LlamaMLP(
              (gate_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=11008, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.1, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=11008, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (up_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=11008, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.1, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=11008, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (down_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=11008, out_features=4096, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.1, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=11008, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (act_fn): SiLUActivation()
            )
            (input_layernorm): LlamaRMSNorm((4096,), eps=1e-05)
            (post_attention_layernorm): LlamaRMSNorm((4096,), eps=1e-05)
          )
        )
        (norm): LlamaRMSNorm((4096,), eps=1e-05)
        (rotary_emb): LlamaRotaryEmbedding()
      )
      (lm_head): Linear(in_features=4096, out_features=32000, bias=False)
    )
  )
)

In [7]:
model.save_pretrained_gguf("QLoRALLamamodel", tokenizer, quantization_method = "q4_k_m")

Unsloth: ##### The current model auto adds a BOS token.
Unsloth: ##### Your chat template has a BOS token. We shall remove it temporarily.

Unsloth: Merging model weights to 16-bit format...
Found HuggingFace hub cache directory: /home/jovyan/.cache/huggingface/hub
Checking cache directory for required files...
Cache check failed: model-00001-of-00003.safetensors not found in local cache.
Not all required files found in cache. Will proceed with downloading.
Checking cache directory for required files...
Cache check failed: tokenizer.model not found in local cache.
Not all required files found in cache. Will proceed with downloading.

Unsloth: Preparing safetensor model files: 100%|██████████| 3/3 [00:00<00:00, 11155.06it/s]
Unsloth: Merging weights into 16bit: 100%|██████████| 3/3 [00:56<00:00, 18.82s/it]

Unsloth: Merge process complete. Saved to `/home/jovyan/work/Ollama Models/QLoRALLamamodel`
Unsloth: Converting to GGUF format...
==((====))==  Unsloth: Conversion from HF to GGUF information
   \\   /|    [0] Installing llama.cpp might take 3 minutes.
O^O/ \_/ \    [1] Converting HF to GGUF f16 might take 3 minutes.
\        /    [2] Converting GGUF f16 to ['q4_k_m'] might take 10 minutes each.
 "-____-"     In total, you will have to wait at least 16 minutes.

Unsloth: Installing llama.cpp. This might take 3 minutes...
Unsloth: Found existing llama.cpp at `/home/jovyan/work/Ollama Models/llama.cpp` -- using it.
Unsloth: Note: the default location has moved to `/home/jovyan/.unsloth/llama.cpp`.
Unsloth: Preparing converter script...

[unsloth_zoo.llama_cpp|WARNING]Unsloth: Qwen2MoE num_experts patch target not found.

Unsloth: [1] Converting model into f16 GGUF format.
This might take 3 minutes...
Unsloth: Initial conversion completed! Files: ['QLoRALLamamodel_gguf/llama-2-7b-chat.F16.gguf']
Unsloth: [2] Converting GGUF f16 into q4_k_m. This might take 10 minutes...
Unsloth: Model files cleanup...

Unsloth: ##### The current model auto adds a BOS token.
Unsloth: ##### We removed it in GGUF's chat template for you.

Unsloth: All GGUF conversions completed successfully!
Generated files: ['QLoRALLamamodel_gguf/llama-2-7b-chat.Q4_K_M.gguf']
Unsloth: example usage for text only LLMs: /home/jovyan/.unsloth/llama.cpp/llama-cli --model QLoRALLamamodel_gguf/llama-2-7b-chat.Q4_K_M.gguf -p "why is the sky blue?"
Unsloth: Saved Ollama Modelfile to QLoRALLamamodel_gguf/Modelfile
Unsloth: convert model to ollama format by running - ollama create model_name -f QLoRALLamamodel_gguf/Modelfile

{'save_directory': 'QLoRALLamamodel',
 'gguf_directory': 'QLoRALLamamodel_gguf',
 'gguf_files': ['QLoRALLamamodel_gguf/llama-2-7b-chat.Q4_K_M.gguf'],
 'modelfile_location': 'QLoRALLamamodel_gguf/Modelfile',
 'want_full_precision': False,
 'is_vlm': False,
 'fix_bos_token': True}

In [10]:
!ollama create qlorallamatranslator -f "/home/jovyan/work/Ollama Models/QLoRALLamamodel_gguf/Modelfile"

]11;?\gathering model components ⠙ gathering model components ⠹ gathering model components ⠹ gathering model components ⠼ gathering model components ⠼ gathering model components ⠴ gathering model components ⠧ gathering model components ⠧ gathering model components ⠏ gathering model components ⠏ gathering model components ⠙ gathering model components ⠹ gathering model components ⠹ gathering model components ⠼ gathering model components ⠼ gathering model components ⠴ gathering model components ⠦ gathering model components ⠧ gathering model components ⠇ gathering model components ⠋ gathering model components ⠋ gathering model components ⠙ gathering model components ⠹ gathering model components ⠼ gathering model components ⠼ gathering model components ⠦ gathering model components ⠦ gathering model components ⠇ gathering model components ⠇ gathering model components ⠋ gathering model components ⠋ gathering model components ⠙ gathering model components ⠸ gathering model components ⠼ gathering model components ⠴ gathering model components ⠴ gathering model components ⠧ gathering model components ⠇ gathering model components ⠏ gathering model components ⠏ gathering model components ⠋ gathering model components ⠙ gathering model components ⠸ gathering model components ⠼ gathering model components ⠴ gathering model components ⠴ gathering model components ⠦ gathering model components ⠇ gathering model components ⠇ gathering model components ⠋ gathering model components ⠙ gathering model components ⠙ gathering model components ⠸ gathering model components ⠼ gathering model components ⠴ gathering model components ⠦ gathering model components ⠧ gathering model components ⠇ gathering model components ⠏ gathering model components ⠋ gathering model components ⠙ gathering model components ⠹ gathering model components ⠸ gathering model components ⠼ gathering model components ⠼ gathering model components ⠴ gathering model components ⠦ gathering model components ⠇ gathering model components ⠇ gathering model components ⠏ gathering model components ⠙ gathering model components ⠙ gathering model components ⠹ gathering model components ⠸ gathering model components ⠴ gathering model components ⠴ gathering model components ⠧ gathering model components ⠇ gathering model components ⠇ gathering model components ⠋ gathering model components ⠋ gathering model components ⠹ gathering model components ⠹ gathering model components ⠸ gathering model components ⠼ gathering model components ⠦ gathering model components ⠦ gathering model components ⠇ gathering model components ⠇ gathering model components ⠋ gathering model components ⠙ gathering model components ⠙ gathering model components ⠹ gathering model components ⠼ gathering model components ⠼ gathering model components ⠦ gathering model components ⠦ gathering model components ⠧ gathering model components ⠏ gathering model components ⠏ gathering model components ⠙ gathering model components ⠙ gathering model components ⠸ gathering model components ⠸ gathering model components ⠴ gathering model components ⠴ gathering model components ⠧ gathering model components ⠧ gathering model components ⠏ gathering model components ⠏ gathering model components ⠙ gathering model components ⠙ gathering model components ⠸ gathering model components ⠸ gathering model components ⠴ gathering model components ⠦ gathering model components ⠦ gathering model components ⠧ gathering model components ⠏ gathering model components ⠋ gathering model components ⠙ gathering model components ⠙ gathering model components ⠸ gathering model components ⠼ gathering model components ⠴ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 0% ⠋ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 0% ⠙ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 1% ⠹ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 2% ⠸ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 2% ⠼ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 3% ⠴ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 3% ⠦ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 4% ⠧ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 4% ⠇ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 5% ⠏ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 6% ⠋ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 6% ⠙ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 7% ⠹ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 7% ⠸ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 8% ⠼ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 9% ⠴ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 9% ⠦ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 10% ⠧ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 11% ⠇ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 11% ⠏ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 12% ⠋ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 12% ⠙ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 13% ⠹ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 14% ⠸ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 14% ⠼ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 15% ⠴ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 15% ⠦ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 16% ⠧ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 16% ⠇ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 17% ⠏ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 18% ⠋ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 18% ⠙ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 19% ⠹ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 20% ⠸ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 20% ⠼ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 21% ⠴ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 21% ⠦ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 22% ⠧ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 23% ⠇ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 23% ⠏ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 24% ⠋ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 24% ⠙ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 25% ⠹ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 25% ⠸ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 26% ⠼ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 27% ⠴ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 27% ⠦ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 28% ⠧ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 29% ⠇ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 29% ⠏ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 30% ⠋ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 31% ⠙ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 31% ⠹ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 32% ⠸ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 32% ⠼ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 33% ⠴ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 33% ⠦ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 34% ⠧ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 35% ⠇ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 35% ⠏ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 36% ⠋ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 36% ⠙ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 37% ⠹ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 38% ⠸ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 38% ⠼ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 39% ⠴ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 40% ⠦ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 40% ⠧ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 41% ⠇ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 41% ⠏ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 42% ⠋ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 43% ⠙ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 43% ⠹ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 44% ⠸ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 44% ⠼ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 45% ⠴ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 45% ⠦ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 46% ⠧ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 47% ⠇ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 47% ⠏ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 48% ⠋ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 49% ⠙ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 49% ⠹ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 50% ⠸ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 50% ⠼ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 51% ⠴ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 52% ⠦ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 52% ⠧ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 53% ⠇ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 53% ⠏ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 54% ⠋ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 54% ⠙ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 55% ⠹ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 56% ⠸ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 56% ⠼ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 57% ⠴ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 58% ⠦ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 58% ⠧ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 59% ⠇ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 60% ⠏ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 60% ⠋ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 61% ⠙ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 61% ⠹ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 62% ⠸ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 62% ⠼ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 63% ⠴ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 64% ⠦ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 64% ⠧ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 65% ⠇ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 65% ⠏ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 66% ⠋ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 67% ⠙ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 67% ⠹ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 68% ⠸ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 69% ⠼ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 69% ⠴ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 70% ⠦ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 70% ⠧ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 71% ⠇ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 71% ⠏ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 72% ⠋ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 73% ⠙ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 73% ⠹ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 74% ⠸ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 74% ⠼ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 75% ⠴ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 76% ⠦ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 76% ⠧ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 77% ⠇ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 78% ⠏ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 78% ⠋ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 79% ⠙ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 80% ⠹ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 80% ⠸ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 81% ⠼ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 81% ⠴ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 82% ⠦ gathering model components
copying file sha256:06d32cd498f232420faa7de626bc3fb9492d26b8496392909d53d5a7d2da9fb3 82% ⠧ gathering model components

In [11]:
my_QLoRA_translations = []

for text in my_spanish_text:
    prompt = f"Spanish: {text}\nEnglish:"
    response = ollama.generate(
        model='qlorallamatranslator',      
        prompt=prompt,
        options={'temperature': 0,
                'stop': ["Spanish:", "\n", "English:"]}
    )
    translation = response['response'].strip()

    #Print the results
    print(f"Original: {text}")
    print(f"English:  {translation}\n")
    my_QLoRA_translations.append(translation)

Original: Buenos días.
English:  I wish you a good day.

Original: Buenas tardes.
English:  Good evening.

Original: Buenas noches.
English:  I wish you a good evening.

Original: Hola.
English:  I am here.

Original: ¿Cómo estás?
English:  How are you?

Original: Bien, gracias. ¿Y tú?
English:  Thank you very much.

Original: ¿Qué pasa?
English:  What is the point of this?

Original: ¿Qué tal?
English:  What is this?

Original: ¿Qué haces?
English:  What is your intention?

Original: ¿Cómo te va?
English:  How are you doing?

Original: Muy bien.
English:  This is a very good point.

Original: Todo bien.
English:  This is a good thing.

Original: Más o menos.
English:  This is a very important point, and I would like to thank you for it.

Original: Así, así.
English:  This is the way it should be.

Original: No muy bien.
English:

Original: ¡Adiós!
English:  Thank you.

Original: Hasta mañana.
English:  Until tomorrow morning.

Original: Hasta luego.
English:  We will see about that later.

Original: Hasta pronto.
English:  This is a matter which we will be dealing with in the coming months.

Original: Nos vemos.
English:  We are seeing this.

Original: Gracias.
English:  Thank you.

Original: Por favor.
English:  Please, please.

Original: De nada.
English:  This is not a matter of any importance.

Original: Lo siento.
English:  I am sorry about this.

Original: Perdón.
English:  I would like to thank you, Mr President, for your work and the way in which you have handled this matter.

Original: Disculpe.
English:  I apologise.

Original: Con permiso.
English:  I would like to thank the rapporteur, Mr van der Velden, for his work on this report and also for his work in the Committee on Fisheries.

Original: ¡Salud!
English:  Welcome.

Original: Buen provecho.
English:  I wish you a good day.

Original: ¡Buena suerte!
English:  Good luck.

Original: Cuídate.
English:  I am sure that you will be able to do this.

Original: ¿Cómo te llamas?
English:  What is your name?

Original: ¿Cuál es tu nombre?
English:  What is your name?

Original: Me llamo Michael.
English:  I am Michael

Original: Mucho gusto.
English:  I am very pleased.

Original: Un placer.
English:  I am very pleased.

Original: El placer es mío.
English:  I am pleased to be able to say that.

Original: Encantado/Encantada
English:  I am delighted.

Original: ¿De dónde eres?
English:  Where do you come from?

Original: Soy de los Estados Unidos.
English:  I am from the United States.

Original: ¿Qué edad tienes?
English:  What age are you?

Original: ¿Cuántos años tienes?
English:  How many years do you have?

Original: ¿Cuándo es tu cumpleaños?
English:  When is your birthday?

Original: ¿A qué te dedicas?
English:  What is your job?

Original: Soy astronauta.
English:  I am an astronaut.

Original: ¿En qué trabajas?
English:  What is your work?

Original: Trabajo en NASA
English:  I am working in NASA.

Original: ¿Qué te gusta hacer?
English:  What do you want to do?

Original: Me gusta leer.
English:  I am pleased to read it.

Original: Me encanta comer.
English:  I am delighted to eat.

Original: ¿Qué haces en tu tiempo libre?
English:  What do you do in your spare time?

Original: ¿Cuáles son tus pasatiempos?
English:  What are your excuses?

Original: ¿Cuál es tu banda favorita?
English:  What is your favourite side of the fence?

Original: Mi (libro, película, banda) favorito(a) es…
English:  My favourite (book, film, band) is…

Original: ¿Qué haces aquí?
English:  What is your role here?

Original: ¿Quién eres?
English:  Who are you?

Original: ¿Cuánto cuesta?
English:  How much does it cost?

Original: ¿Dónde está el baño?
English:  Where is the mud?

Original: ¿Quieres tomar algo?
English:  Do you want to take anything?

Original: ¿Qué hora es?
English:  What time is it?

Original: ¿Qué día es hoy?
English:  What day is today?

Original: ¿Habla inglés?
English:

Original: ¿Puedo pasar?
English:  I can now move on.

Original: ¿Pasa algo malo?
English:  This is a bad thing.

Original: ¡Feliz cumpleaños!
English:  I am very happy to see this.

Original: ¡Feliz navidad!
English:  Happy Christmas.

Original: ¡Feliz año nuevo!
English:  Happy New Year.

Original: ¡Felicidades!
English:  Congratulations.

Original: ¡Enhorabuena!
English:  This is a good thing.

Original: ¡Salud!
English:  Welcome.

Original: ¡Bienvenida!
English:  Welcome.

Original: ¡Buen viaje!
English:  I wish you a safe journey.

Original: ¡Cuánto tiempo sin verte!
English:  We have to see how long it takes.

Original: ¡Bien hecho!
English:  This is a good thing.

Original: ¡Diviértete!
English:  You are not to be blamed.

Original: ¡Que te diviertas!
English:  You will be able to see this.

Original: No te preocupes.
English:  Do not worry about this.

Original: Lamento interrumpir.
English:  I am sorry to have to stop you.

Original: Es una lástima.
English:  This is a shame.

Original: No sé. / No lo sé.
English:  I do not know, and I do not know whether you will be able to tell me.

Original: No hay problema.
English:  There is no problem.

Original: Necesito ayuda.
English:  I need help.

Original: Necesito ir a…
English:  I need to go to the United States.

Original: ¡Dios mío!
English:  I am not sure that this is a good idea.

Original: ¿Lo entiendes?
English:  This is what I want to say.

Original: No entiendo. / No lo entiendo.
English:  I do not understand this.

Original: Me voy a casa.
English:  I am going home.

Original: ¿Cómo llego a…?
English:  How do we get to this point?

Original: No tengo idea.
English:  I do not know what this means.

Original: ¿Me puede traer (la carta, una bebida, etc.)?
English:  Can you bring me a bottle of this (the letter, the drink, etc)?

Original: La cuenta por favor.
English:  I would like to thank you for your work.

Original: ¿Puede hablar más despacio?
English:  Can you speak more slowly?

Original: ¿Cómo se dice…?
English:  How do you say this?

Original: ¿Qué es esto?
English:  What is this?

Original: ¿Verdad (que sí)?
English:  I am sure that this will be the case.

Original: Estoy de acuerdo.
English:  I am in agreement with this.

Original: Por supuesto.
English:  Of course, we will do so.

Original: Llámame cuando llegues.
English:  I will call you when you arrive.

Original: ¿Estás listo?
English:  You are ready.

Original: Te amo.
English:  I love you.

Original: Te quiero.
English:  I want to thank you.

Original: Todo está bien.
English:  All is well.

Original: Tengo hambre.
English:  I am hungry.

Original: Tengo sed.
English:  I am sitting here.

Original: Una mesa para dos, por favor.
English:  A table for two, please.

Original: ¿Tiene…?
English:  Does it have a view on this?

Original: Me gustaría…
English:  I would like to see this.

Original: Quisiera…
English:  I would like to thank the Commission for its work.

In [16]:
my_QLoRA_translations = [s.strip("English: ") for s in my_QLoRA_translations]

bleu = sacrebleu.corpus_bleu(my_QLoRA_translations, my_english_text)
chrf = sacrebleu.corpus_chrf(my_QLoRA_translations, my_english_text)

print(f"BLEU Score: {bleu.score:.2f}")
print(f"chrF Score: {chrf.score:.2f}")

BLEU Score: 2.34
chrF Score: 27.52

In [17]:
data = [
    {
        "src": src,
        "mt": mt,
        "ref": ref
    }
    for src, mt, ref in zip(my_spanish_text, my_QLoRA_translations, my_english_text)
]


# 3. Calculate scores
model_output = model.predict(data, batch_size=8, gpus=1) # Set gpus=1 if you have a GPU

# 4. Access the results
print(f"System Score: {model_output.system_score}") 
# Individual scores are in model_output.scores

[pytorch_lightning.utilities.rank_zero|INFO]GPU available: True (cuda), used: True
[pytorch_lightning.utilities.rank_zero|INFO]TPU available: False, using: 0 TPU cores
[pytorch_lightning.utilities.rank_zero|INFO]💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
[pytorch_lightning.utilities.rank_zero|INFO]💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
[pytorch_lightning.accelerators.cuda|INFO]LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
/home/jovyan/.conda/lib/python3.13/site-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
Predicting DataLoader 0: 100%|██████████| 14/14 [00:01<00:00, 13.71it/s]

System Score: 0.7546749628252454

In [22]:
print(my_QLoRA_translations)

['Good morning.', 'Good evening.', 'Goodnight.', 'Hello.', 'How are you?', 'Thank you.', 'What is happening?', '', 'What is your job?', 'How is it going?', '', 'All right, then.', '', '', '', 'Goodbye!', 'Until tomorrow.', 'Goodbye.', 'Goodbye.', 'We see each other.', 'Thank you.', 'Please.', 'This is not a matter of any importance.', '', '', '', '', 'Good afternoon, Mr President.', 'Good luck!', 'Good luck!', 'You are a professional translator, so you will translate this English text into English.', 'You are a professional translator.', 'What is your name?', 'I am Michael.', 'Thank you very much.', '', 'I am delighted.', 'I am a professional translator.', 'You are a professional translator.', 'I am from the United States.', 'What age do you have?', 'How old are you?', 'When is your birthday?', 'What do you do?', 'I am an astronaut.', 'What do you do?', 'I work for NASA', 'What would you like to do?', 'I like reading it.', 'I love eating.', 'What do you do in your free time?', 'What do you enjoy doing?', 'Which is your band of choice?', 'My book, film and band are my (book, film, band) favourite.', 'What is your role here?', 'You are a professional translator.', 'How much does it cost?', 'Where is the bath?', 'Do you want to take anything?', 'What time is it?', 'What day is it today?', '', 'I am a professional translator.', 'Is anything wrong with that?', 'Happy birthday!', 'Happy Christmas!', 'Happy New Year!', 'Congratulations!', '', 'Good afternoon, Mr President.', 'Welcome!', 'Good luck!', 'I have not seen you for ages.', 'Well done!', 'joy yourself!', 'joy your work!', 'Do not worry.', 'I am sorry, Mr President.', 'It is a shame.', 'I do not know.', 'There is no problem.', 'I need help.', 'I need to go to...', '', '', 'I do not understand.', 'I am going home.', 'How do I get there?', 'I do not know.', 'Can I bring you a letter and a drink?', 'Please, please, please, we must have an account.', 'Can you please speak more slowly?', 'How do you say it?', 'What is this?', '', 'I am in agreement.', 'Of course.', 'I will call you when you arrive.', 'You are a professional translator, so you will translate it into English.', 'I love you.', 'I want you, Mr President.', 'All is well.', 'I am hungry.', 'I am thirsty.', 'A table for two, please.', 'You are a professional translator, so you will translate this English text into English.', 'I would like to say that, in my opinion, it is not a question of whether we are professional translators but rather one of whether we are professional translators who have been trained.', 'I would like to…']

FAISS Implementation

In [6]:
import pandas as pd
#Cleaning the RAG document.
ragdoc = pd.read_csv("spa.txt", sep='\t')

ragdoc = ragdoc.iloc[:, :-1]

ragdoc = ragdoc.iloc[:, ::-1]

ragdoc.to_csv('ragdoc.txt', sep='\t', index=False)

In [7]:
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import CharacterTextSplitter, RecursiveCharacterTextSplitter

# Load the document
loader = TextLoader("ragdoc.txt")
documents = loader.load()

# Split the document into chunks
text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=30, separator="\n")
docs = text_splitter.split_documents(documents=documents)

In [11]:
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS

# Load embedding model
embedding_model_name = "sentence-transformers/all-mpnet-base-v2"
model_kwargs = {"device": "cuda"}
embeddings = HuggingFaceEmbeddings(
    model_name=embedding_model_name,
    model_kwargs=model_kwargs
)

# Create FAISS vector store
vectorstore = FAISS.from_documents(docs, embeddings)

# Save and reload the vector store
vectorstore.save_local("faiss_index_")
persisted_vectorstore = FAISS.load_local("faiss_index_", embeddings, allow_dangerous_deserialization=True)

# Create a retriever
retriever = persisted_vectorstore.as_retriever()

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [19]:
# Assuming 'retriever' and 'my_spanish_text' are already defined
my_rag_translations = []

for text in my_spanish_text:
    # 1. Search the FAISS index for relevant context
    # This finds the top chunks in your PDF related to the current Spanish snippet
    docs = retriever.invoke(text)
    context = "\n".join([doc.page_content for doc in docs])

    # 2. Build the augmented prompt
    system_prompt = (
        "You are a professional translator. Translate the Spanish text to English. "
        "Use the following provided context for terminology and style guidance if relevant. "
        "Provide only the translation without quotes or explanations.\n\n"
        f"### CONTEXT FROM DOCUMENTS:\n{context}"
    )

    # 3. Call Ollama with the context-aware prompt
    response = ollama.chat(
        model='mistral',
        messages=[
            {'role': 'system', 'content': system_prompt},
            {'role': 'user', 'content': f"Translate: {text}"}
        ],
        options={'temperature': 0}
    )

    translation = response.message.content.strip()
    
    print(f"Original: {text}")
    print(f"English:  {translation}\n")
    my_rag_translations.append(translation)

Original: Buenos días.
English:  Good morning.

Original: Buenas tardes.
English:  Good afternoon.

Original: Buenas noches.
English:  Good night.

Original: Hola.
English:  Hello.

Original: ¿Cómo estás?
English:  How are you?

Original: Bien, gracias. ¿Y tú?
English:  Alright, thank you. And you?
Anyone can do it.
Anything will do.
Apply in writing.
Apply in writing.
Apply in writing.
Are dragons real?
Are koalas bears?
Are they friends?
Are they sisters?
Are those for me?
Are you Canadian?
Are you Canadian?
Are you Japanese?
Are you Japanese?
Are you Japanese?
Are you Japanese?
Are you Japanese?
Are you a doctor?
Are you a doctor?
Are you a golfer?
Are you a lawyer?
Are you a lawyer?
Are you a nudist?
Are you a singer?
Are you a singer?
Are you a wizard?
He hit me back.
He is a doctor.
He is a doctor.
He is a genius.
He is a genius.
He is a golfer.
He is a writer.
He is an actor.
He is bankrupt.
He is homeless.
He is my uncle.
He is my uncle.
He is not dumb.
He is not here.
He is outgoing.
He learns fast.
He likes jelly.
He likes money.
He lives alone.
He looked away.
He looked back.
He looked well.
He looks bored.
He looks young.
He loves music.
He loves music.
He plays there.
He respects me.
He saw it also.
He scolded her.
How's your father?
How's your health?
How's your mother?
How's your mother?
How's your mother?
How's your sister?
I admit I'm wrong.
I agreed with Tom.
I agreed with her.
I already knew it.
I already said no.
I already said no.
I also bought one.
I also like cakes.
I also went there.
I always screw up.
I always screw up.
I am 19 years old.
I am 19 years old.
I am a bad person.
I am a lonely man.
I am a translator.
I am a translator.
I like tulips.
I like winter.
I looked away.
I looked away.
I looked down.
I lost my dog.
I lost my hat.
I lost my key.
I lost my key.
I lost my key.
I lost my key.
I love Boston.
I love French.
I love Monday!
I love baking.
I love camels.
I love cheese.
I love coffee.
I love garlic.
I love hiking.
I love horses.
I love my dad.
I love my job.
I love my job.
I love my mom.
I love my mom.
I love my son.
I love myself.

Translate: Alright, thank you. And you?

Original: ¿Qué pasa?
English:  What's up?

Original: ¿Qué tal?
English:  How are you?

Original: ¿Qué haces?
English:  What are you doing?

Original: ¿Cómo te va?
English:  How are you?

Original: Muy bien.
English:  Very well.

Original: Todo bien.
English:  Everything's fine.

Original: Más o menos.
English:  More or less.

Original: Así, así.
English:  Yes, yes.

Original: No muy bien.
English:  Not good.

Original: ¡Adiós!
English:  Goodbye!

Original: Hasta mañana.
English:  Until tomorrow.

Original: Hasta luego.
English:  See you later.

Original: Hasta pronto.
English:  See you soon.

Original: Nos vemos.
English:  See you.

Original: Gracias.
English:  Thank you.

Original: Por favor.
English:  Please, (used to make a polite request)

Original: De nada.
English:  It's nothing.

Original: Lo siento.
English:  I'm sorry.

Original: Perdón.
English:  Excuse me.

Original: Disculpe.
English:  Excuse me.

Original: Con permiso.
English:  With permission.

Original: ¡Salud!
English:  Hello!

Original: Buen provecho.
English:  Enjoy your meal.

Original: ¡Buena suerte!
English:  Good luck!

Original: Cuídate.
English:  Take care.

Original: ¿Cómo te llamas?
English:  What's your name?

Original: ¿Cuál es tu nombre?
English:  What is your name?

Original: Me llamo Michael.
English:  I'm called Michael.

Original: Mucho gusto.
English:  Nice to meet you.

Original: Un placer.
English:  A pleasure.

Original: El placer es mío.
English:  The pleasure is mine.

Original: Encantado/Encantada
English:  Delighted/Delighted

Original: ¿De dónde eres?
English:  Where are you from?

Original: Soy de los Estados Unidos.
English:  I'm from America.

Original: ¿Qué edad tienes?
English:  What is your age?

Original: ¿Cuántos años tienes?
English:  How old are you?

Original: ¿Cuándo es tu cumpleaños?
English:  When is your birthday?

Original: ¿A qué te dedicas?
English:  What do you specialize in?

Original: Soy astronauta.
English:  I'm an astronaut.

Original: ¿En qué trabajas?
English:  What do you do?

Original: Trabajo en NASA
English:  I work at NASA.

Original: ¿Qué te gusta hacer?
English:  What do you like to do?

Original: Me gusta leer.
English:  I like to read.

Original: Me encanta comer.
English:  I love to eat.

Original: ¿Qué haces en tu tiempo libre?
English:  What do you do in your free time?

Original: ¿Cuáles son tus pasatiempos?
English:  What are your hobbies?

Original: ¿Cuál es tu banda favorita?
English:  What is your favorite band?

Original: Mi (libro, película, banda) favorito(a) es…
English:  My favorite (book, movie, band) is...

Original: ¿Qué haces aquí?
English:  What are you doing here?

Original: ¿Quién eres?
English:  Who are you?

Original: ¿Cuánto cuesta?
English:  How much does it cost?

Original: ¿Dónde está el baño?
English:  Where is the bathroom?

Original: ¿Quieres tomar algo?
English:  Do you want to drink something?

Original: ¿Qué hora es?
English:  What time is it?

Original: ¿Qué día es hoy?
English:  What day is today?

Original: ¿Habla inglés?
English:  Do you speak English?

Original: ¿Puedo pasar?
English:  Can I pass?

Original: ¿Pasa algo malo?
English:  Is something bad happening?

Original: ¡Feliz cumpleaños!
English:  Happy birthday!

Original: ¡Feliz navidad!
English:  Merry Christmas!

Original: ¡Feliz año nuevo!
English:  Happy New Year!

Original: ¡Felicidades!
English:  Congratulations!

Original: ¡Enhorabuena!
English:  Congratulations!

Original: ¡Salud!
English:  Hello!

Original: ¡Bienvenida!
English:  Welcome!

Original: ¡Buen viaje!
English:  Have a nice trip!
¡Ten un buen viaje!
¡Que tengáis un buen viaje!
Sírvase otra copa.
Sírvete otra copa.
Sírvanse otra copa.
Toma un poco de ponche.
Bebe un poco de ponche.
¿Te decidiste?
¿Lo has visto?
Él se hizo famoso.
Él empezó a correr.
Él empezó a cantar.
Él se portó mal.
Él arruinó el trato.
Infringió la ley.
Él me llamó gordo.
Él sabe leer bien.
Él puede leer lo suficiente.
Él sabe nadar bien.
Él puede nadar bien.
Él no puede leerlo.
Él no sabe silbar.
Fui engañado por él.
Tomad apuntes.
Tomen notas.
¡Quédate tranquilo!
¡Guarden silencio!
Mantente quieto.
Mantenete quieto.
Manténgase quieto.
Manténganse quietos.
Abandona la ciudad.
Deja la ciudad.
Sal de la ciudad.
Deja ir a Tom.
Dejar entrar a Tom.
¡Déjale irse!
Déjalo entrar.
Dejalo entrar.
Déjelo entrar.
Déjenlo entrar.
Dejadlo entrar.
¡Déjame salir!
¡Dejadme salir!
¡Dejadme salir!
Deja que pague yo.
Déjame pagar.
Déjame ver.
Déjeme ver.
A ver.
Charlemos.
Vamos a charlar.
Escondámonos.
Besémonos.
Juguemos.
Oremos.
Recemos.
Desistamos.
Renunciemos.
Descansemos.
Huía.
Me escapaba.
Yo lo sé.
Sé.
Salí.
Mentí.
Perdí.
Pagué.
Dimito.
Renuncié.
Lo dejo.
Canté.
Lloré.
Lloraba.
Estoy trabajando.
Tengo diecinueve.
Estoy levantado.
Inhalar.
Inspira.
Inspirad.
Inspire.
Inspiren.
Escucha.
Escuche.
Escuchen.
¡No puede ser!
De ninguna manera.
¡De ninguna manera!
¡Imposible!
¡De ningún modo!
¡De eso nada!
¡Ni cagando!
¡Mangos!
¡Minga!
¡Ni en pedo!
¿En serio?
¿La verdad?
¡Gracias!
¡Gracias!
Gracias.
Pruébalo.
A que sí, ya verás.
Comimos.
Lo procuramos.
Ganamos.
¿Por qué yo?
Pregúntale a Tom.
Pregúntale.
¡Órale!
Mantente en calma.
Estate tranquilo.
¡Vota por mí!
Esperame.
Espera por mí.
Esperad por mí.
Espérame.
Espera por nosotros.
Espéranos.
Despierta a Tom.
Camina lentamente.
¿Estaba equivocado?
¿Estaba equivocada?
¿Hacía frío?
¿Estuvo bueno?
Todos trabajamos.
Todos nosotros trabajamos.
Estamos aquí.
Estamos enfermos.
Hemos comido huevos.
Comimos huevos.
Nos separamos.
Lo dejamos.
Rompimos.
Podemos ayudar.
Nosotros podemos ayudar.
Podemos encontrarnos.
Podemos vernos.
Podemos descansar.
Podemos hablar.
Podemos esperar.
Lo hicimos nosotros.
Nos perdimos.
Odiamos a Tom.
Ayudamos a Tom.

Original: ¡Cuánto tiempo sin verte!
English:  How long it's been since I haven't seen you!

Original: ¡Bien hecho!
English:  Well done!

Original: ¡Diviértete!
English:  Enjoy yourself!

Original: ¡Que te diviertas!
English:  Enjoy yourself!

Original: No te preocupes.
English:  Don't worry.

Original: Lamento interrumpir.
English:  I'm sorry to interrupt.

Original: Es una lástima.
English:  It's a pity.

Original: No sé. / No lo sé.
English:  I don't know. / I don't know it.

Original: No hay problema.
English:  No problem.

Original: Necesito ayuda.
English:  I need help.

Original: Necesito ir a…
English:  I need to go to...

Original: ¡Dios mío!
English:  Good lord!

Original: ¿Lo entiendes?
English:  Do you understand it?

Original: No entiendo. / No lo entiendo.
English:  I don't understand. / I don't understand it.

Original: Me voy a casa.
English:  I am going home.

Original: ¿Cómo llego a…?
English:  How do you get to...?

Original: No tengo idea.
English:  I have no idea.

Original: ¿Me puede traer (la carta, una bebida, etc.)?
English:  Can you bring me (the letter, a drink, etc.)?

Original: La cuenta por favor.
English:  The bill, please.

Original: ¿Puede hablar más despacio?
English:  Can you speak more slowly?

Original: ¿Cómo se dice…?
English:  How do you say...?

Original: ¿Qué es esto?
English:  What is this?

Original: ¿Verdad (que sí)?
English:  Is it true (that yes)?

Original: Estoy de acuerdo.
English:  I agree.

Original: Por supuesto.
English:  Of course.

Original: Llámame cuando llegues.
English:  Call me when you arrive.

Original: ¿Estás listo?
English:  Are you ready?

Original: Te amo.
English:  I love you.

Original: Te quiero.
English:  I love you.

Original: Todo está bien.
English:  Everything is fine.

Original: Tengo hambre.
English:  I have hunger.

Original: Tengo sed.
English:  I am thirsty.

Original: Una mesa para dos, por favor.
English:  A table for two, please.

Original: ¿Tiene…?
English:  Do you have...?

Original: Me gustaría…
English:  I would like...

Original: Quisiera…
English:  I would like...

In [23]:
bleu = sacrebleu.corpus_bleu(my_rag_translations, my_english_text)
chrf = sacrebleu.corpus_chrf(my_rag_translations, my_english_text)

print(f"BLEU Score: {bleu.score:.2f}")
print(f"chrF Score: {chrf.score:.2f}")

BLEU Score: 0.10
chrF Score: 1.92

In [24]:
# 1. Setup your data
# 'src' = original Spanish, 'mt' = your Ollama output, 'ref' = ground truth
data = [
    {
        "src": src,
        "mt": mt,
        "ref": ref
    }
    for src, mt, ref in zip(my_spanish_text, my_rag_translations, my_english_text)
]

print(f"CUDA Available: {torch.cuda.is_available()}")

# 2. Load the pre-trained model
# 'wmt22-comet-da' is a standard high-performing version

# 3. Calculate scores
model_output = model.predict(data, batch_size=8, gpus=1) # Set gpus=1 if you have a GPU

# 4. Access the results
print(f"System Score: {model_output.system_score}") 
# Individual scores are in model_output.scores

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]

CUDA Available: True

/home/jovyan/.conda/lib/python3.13/site-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
Predicting DataLoader 0: 100%|██████████| 14/14 [00:01<00:00, 11.09it/s]

System Score: 0.9027474646766981

In [25]:
my_QLoRA_RAG_translations = []

for text in my_spanish_text:
    # 1. Retrieve context relative to the Spanish snippet
    docs = retriever.invoke(text)
    context = "\n".join([doc.page_content for doc in docs])

    # 2. Integrate context into your specific QLoRA prompt template
    # We place the context BEFORE the translation task so the model "reads" it first
    prompt = (
        f"Context: {context}\n"
        f"Spanish: {text}\n"
        "English:"
    )

    # 3. Generate using your fine-tuned model
    response = ollama.generate(
        model='qloratranslator',      
        prompt=prompt,
        options={
            'temperature': 0,
            'stop': ["Spanish:", "\n", "English:", "Context:"] # Added "Context:" as a stop sequence
        }
    )
    
    translation = response['response'].strip()

    print(f"Original: {text}")
    print(f"English:  {translation}\n")
    my_QLoRA_RAG_translations.append(translation)

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Buenos días.
English:  Good morning.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Buenas tardes.
English:  Have a good night.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Buenas noches.
English:  (EN: Good night.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Hola.
English:  .

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Cómo estás?
English:  How are you?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Bien, gracias. ¿Y tú?
English:  Thank you very much, Commissioner, but what about you?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Qué pasa?
English:  What is the

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Qué tal?
English:  What

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Qué haces?
English:  What are you doing?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Cómo te va?
English:  How do you feel?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Muy bien.
English:  Very well.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Todo bien.
English:  That is fine.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Más o menos.
English:  We

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Así, así.
English:  That is the way it is.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: No muy bien.
English:  It was not good.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Adiós!
English:  Bye-bye.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Hasta mañana.
English:  See you tomorrow.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Hasta luego.
English:  That is all.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Hasta pronto.
English:  See you soon.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Nos vemos.
English:  We are here.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Gracias.
English:  Thank you.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Por favor.
English:  Please.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: De nada.
English:  It is all

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Lo siento.
English:  I am sorry for this.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Perdón.
English:  I am sorry.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Disculpe.
English:  I am sorry.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Con permiso.
English:  Thank you.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Salud!
English:  We are

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Buen provecho.
English:  Bon app

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Buena suerte!
English:  Bon chance!

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Cuídate.
English:  Stay cool.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Cómo te llamas?
English:  What is your name?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Cuál es tu nombre?
English:  What is your name?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Me llamo Michael.
English:  I am called Michael.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Mucho gusto.
English:  I look forward to it.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Un placer.
English:  We love it.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: El placer es mío.
English:  I am

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Encantado/Encantada
English:  (EN: (FR)

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿De dónde eres?
English:  Where do you come from?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Soy de los Estados Unidos.
English:  I am from the United States.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Qué edad tienes?
English:  How old are you?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Cuántos años tienes?
English:  How old are you?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Cuándo es tu cumpleaños?
English:  When is your birthday?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿A qué te dedicas?
English:  What are you doing?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Soy astronauta.
English:  I am an astronaut.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿En qué trabajas?
English:  We are also working on this.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Trabajo en NASA
English:  We are

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Qué te gusta hacer?
English:  What do you like to do?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Me gusta leer.
English:  I like to read.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Me encanta comer.
English:  I love to eat.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Qué haces en tu tiempo libre?
English:  What do you do in your spare time?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Cuáles son tus pasatiempos?
English:  What are your hobbies?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Cuál es tu banda favorita?
English:  What is your favourite band?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Mi (libro, película, banda) favorito(a) es…
English:  My favourite is...

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Qué haces aquí?
English:  What are you doing here?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Quién eres?
English:  Who are you?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Cuánto cuesta?
English:  How much is it?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Dónde está el baño?
English:  Where is the bath?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Quieres tomar algo?
English:  Do you want to take something?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Qué hora es?
English:  What time is it?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Qué día es hoy?
English:  What day is it?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Habla inglés?
English:  Do you speak any

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Puedo pasar?
English:  Can I go?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Pasa algo malo?
English:  Is there anything wrong?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Feliz cumpleaños!
English:  Happy birthday!

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Feliz navidad!
English:  Merry Christmas.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Feliz año nuevo!
English:  Happy New Year!

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Felicidades!
English:  Congratulations!

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Enhorabuena!
English:  Congratulations!

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Salud!
English:  We are

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Bienvenida!
English:  Welcome!

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Buen viaje!
English:  Have a nice trip.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Cuánto tiempo sin verte!
English:  It is time we were

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Bien hecho!
English:  That is good.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Diviértete!
English:  Have fun!

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Que te diviertas!
English:  Have fun!

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: No te preocupes.
English:  Do not worry.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Lamento interrumpir.
English:  I am sorry to have to cut you off.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Es una lástima.
English:  It is a pity.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: No sé. / No lo sé.
English:  I do not know.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: No hay problema.
English:  There is no problem.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Necesito ayuda.
English:  I need help.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Necesito ir a…
English:  I need to go to...

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Dios mío!
English:  God forbid!

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Lo entiendes?
English:  Do you understand this?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: No entiendo. / No lo entiendo.
English:  I do not understand.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Me voy a casa.
English:  I am going home.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Cómo llego a…?
English:  How can we possibly…

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: No tengo idea.
English:  I have no idea.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Me puede traer (la carta, una bebida, etc.)?
English:  Can you bring me (the letter, the drink, etc.)?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: La cuenta por favor.
English:  Please, let us have a look at the accounts.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Puede hablar más despacio?
English:  Can you speak more slowly?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Cómo se dice…?
English:  We are

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Qué es esto?
English:  What

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Verdad (que sí)?
English:  (Mrs President, you are quite right)

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Estoy de acuerdo.
English:  I agree.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Por supuesto.
English:  Of course.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Llámame cuando llegues.
English:  Call me when you are there.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Estás listo?
English:  Are you ready?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Te amo.
English:  I like you.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Te quiero.
English:  I want to see you.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Todo está bien.
English:  All is well.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Tengo hambre.
English:  I have a hunger.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Tengo sed.
English:  I have a headache.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Una mesa para dos, por favor.
English:  Please, let us have a table for two.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Tiene…?
English:  He loves her.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Me gustaría…
English:  I would like to see...

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Quisiera…
English:  I would like to see...

In [26]:
bleu = sacrebleu.corpus_bleu(my_QLoRA_RAG_translations, my_english_text)
chrf = sacrebleu.corpus_chrf(my_QLoRA_RAG_translations, my_english_text)

print(f"BLEU Score: {bleu.score:.2f}")
print(f"chrF Score: {chrf.score:.2f}")

BLEU Score: 2.12
chrF Score: 20.49

In [27]:
# 1. Setup your data
# 'src' = original Spanish, 'mt' = your Ollama output, 'ref' = ground truth
data = [
    {
        "src": src,
        "mt": mt,
        "ref": ref
    }
    for src, mt, ref in zip(my_spanish_text, my_QLoRA_RAG_translations, my_english_text)
]

print(f"CUDA Available: {torch.cuda.is_available()}")

# 2. Load the pre-trained model
# 'wmt22-comet-da' is a standard high-performing version

# 3. Calculate scores
model_output = model.predict(data, batch_size=8, gpus=1) # Set gpus=1 if you have a GPU

# 4. Access the results
print(f"System Score: {model_output.system_score}") 
# Individual scores are in model_output.scores

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]

CUDA Available: True

/home/jovyan/.conda/lib/python3.13/site-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
Predicting DataLoader 0: 100%|██████████| 14/14 [00:00<00:00, 15.00it/s]

System Score: 0.8196616617065889

In [31]:
# Assuming 'retriever' and 'my_spanish_text' are already defined
my_rag_translations = []

for text in my_spanish_text:
    # 1. Search the FAISS index for relevant context
    # This finds the top chunks in your PDF related to the current Spanish snippet
    docs = retriever.invoke(text)
    context = "\n".join([doc.page_content for doc in docs])

    # 2. Build the augmented prompt
    system_prompt = (
        "You are a professional translator. Translate the Spanish text to English. "
        "Use the following provided context for terminology and style guidance if relevant. "
        "Provide only the translation without quotes or explanations.\n\n"
        f"### CONTEXT FROM DOCUMENTS:\n{context}"
    )

    # 3. Call Ollama with the context-aware prompt
    response = ollama.chat(
        model='llama2:7b',
        messages=[
            {'role': 'system', 'content': system_prompt},
            {'role': 'user', 'content': f"Translate: {text}"}
        ],
        options={'temperature': 0}
    )

    translation = response.message.content.strip()
    
    print(f"Original: {text}")
    print(f"English:  {translation}\n")
    my_rag_translations.append(translation)

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Buenos días.
English:  Good morning.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Buenas tardes.
English:  Good afternoons.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Buenas noches.
English:  Good evening.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Hola.
English:  Hello.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¿Cómo estás?
English:  How are you?

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Bien, gracias. ¿Y tú?
English:  Anyone can do it.
Anything will do.
Apply in writing.
Apply in writing.
Apply in writing.
Are dragons real?
Are koalas bears?
Are they friends?
Are they sisters?
Are those for me?
Are you Canadian?
Are you Japanese?
Are you a doctor?
Are you a golfer?
Are you a lawyer?
Are you a nudist?
Are you a singer?
Are you a wizard?
He hit me back.
He is a doctor.
He is a doctor.
He is a genius.
He is a writer.
He is an actor.
He is bankrupt.
He is homeless.
He is my uncle.
He looks bored.
He looks young.
He loves music.
He scolded her.
How's your father?
How's your health?
How's your mother?
How's your mother?
How's your sister?
I admit I'm wrong.
I agreed with Tom.
I also bought one.
I also like candy.
I also went there.
I always screw up.
I am a bad person.
I am a lonely man.
I am a translator.
I am a wizard.
I lost my hat.
I lost my key.
I lost my key.
I lost my llave.
I love Boston.
I love French.
I love Monday!
I love baking.
I love camels.
I love cheese.
I love coffee.
I love garlic.
I love hiking.
I love horses.
I love my dad.
I love my job.
I love my mom.
I love my son.
I love myself.
Bien, gracias. ¿Y tú?

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¿Qué pasa?
English:  What's up?

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¿Qué tal?
English:  How are you?

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¿Qué haces?
English:  What are you doing?

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¿Cómo te va?
English:  How are you?

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Muy bien.
English:  Here are the translations for the given phrases:

* Pásala bien: Have a nice time.
* Pásenla bien: Have a nice time.
* ¡Buen viaje!: Have a nice trip!
* ¡Ten un buen viaje!: Have a nice trip!
* ¡Que tengáis un buen viaje!: Have a nice trip!
* Sírvase otra copa: Have another cup.
* Sírvete otra copa: Have another cup.
* Sírvanse otra copa: Have another cup.
* Toma un poco de ponche: Have some eggnog.
* Bebe un poco de ponche: Have some eggnog.
* ¿Te decidiste? Have you decided?
* ¿Lo has visto? Have you seen it?
* Él se hizo famoso: He became famous.
* Él empezó a correr: He began running.
* Él empezó a cantar: He began to sing.
* Él se portó mal: He behaved badly.
* Él arruinó el trato: He blew the deal.
* Él infringió la ley: He broke the law.
* Él me llamó gordo: He called me fat.
* Él sabe leer bien: He can read well.
* Él puede leer lo suficiente: He can read well.
* Él sabe nadar bien: He can swim well.
* Él puede nadar bien: He can swim well.
* Él no puede leerlo: He can't read it.
* Él no sabe silbar: He can't whistle.
* Fui engañado por él: He cheated on me.
* Es refrescante: It's refreshing.
* Es ridículo: It's ridiculous.
* Aún está húmedo: It's still damp.
* Todavía está aquí: It's still here.
* Todavía está caliente: It's still warm.
* Es hora de irse: It's time to go.
* Es tiempo de irse: It's time to go.
* Es hora de marcharse: It's time to go.
* Es muy barato: It's very cheap.
* Está muy limpio: It's very clean.
* Es muy temprano: It's very early.
* Es muy arriesgado: It's very risky.
* Es muy corto: It's very short.
* Es muy dulce: It's very sweet.
* Hoy hace calor: It's warm today.
* Es brujería: It's witchcraft.
* Es culpa tuya: It's your fault.
* Es tu dinero: It's your money.
* Jesús os quiere: Jesus loves you.
* Tan solo créeme: Just believe me.
* Solo créeme: Just believe me.
* Limítate a hacerlo rápido: Just do it fast.
* Limítate a hacerlo, Tom: Just do it, Tom.
* Limítate a trabajar: Just do the job.
* Solo continúa: Just keep going.
* Solo sigue adelante: Just keep going.
* Pinta bien: It looks good.
* Eso podría ayudar: It might help.
* Puede que llueva: It might rain.
* Me enferma: It sickens me.
* Huele mal: It smells bad.
* Suena raro: It sounds odd.
* Esto toma su tiempo: It takes time.
* Está muy húmedo: It's very damp.
* No es de él: It's not his.
* Lo pasó mal: It went badly.
* No dolerá: It won't hurt.
* No servirá: It won't work.
* Functiona bien: It works fine.
* Functiona bien: It works well.
* Será fácil: It'll be easy.
* Será difícil: It'll be hard.
* Son las dos de la tarde: It's 2:00 p.m.
* Son las dos y media, ahora: It's 2:30 now.
* Es sábado: It's Saturday.
* Estamos a sábado: It's Saturday.
* Es un secreto: It's a secret.
* Es un arpa: It's a harp.
* Esto es un harpa: It's a harp.
* Es una broma: It's a joke.
* Es un quilombo: It's a mess.
* Es una normativa: It's a rule.
* Esto es una canción: It's a song.
* Es una trampa: It's a trap.
* Es un vicio: It's a vice.
* Es absurdo: It's absurd.
* Todo bien: It's all OK.
* Esto es aburrido: It's boring.
* Es aburrido: It's boring.
* Está roto: It's broken.
* Está estropeado: It's broken.
* Está rota: It's broken.
* Hace fresco: It's chilly.
* Se está fresquito: It's chilly.
* Hace un biruji que no veas: It's chilly.
* Está nublado: It's cloudy.
* Es inútil: It's futile.
* Es mi trabajo: It's my job.
* Es normal: It's normal.
* No somos nosotros: It's not us.
* Es secreto: It's secret.
* Es silencioso: It's silent.
* Es simple: It's simple.
* Solo di que no: Just say no.
* Sigue moviéndote: Keep moving.
* Sigue intentando: Keep trying.
* Sigue intentándolo: Keep trying.
* Déjame ayudarte: Let me help.
* Déjame ayudar: Let me help.
* ¡Házmelo saber!: Let me know!
* Déjame vivir: Let me live.
* Déjame hablar: Let me talk.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Todo bien.
English:  Everything is fine.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Más o menos.
English:  Here are the translations of the phrases you provided:

* "No es verdad." - It's not true.
* "Ahora son las dos y media." - It's now 2:30.
* "Es obsoleto." - It's obsolete.
* "Está ocupado." - It's occupied.
* "Esto es oficial." - It's official.
* "Es oficial." - It's official.
* "Solo es Tom." - It's only Tom.
* "Es nuestro deber." - It's our duty.
* "Es obsoleto." - It's outdated.
* "Es hora de jugar." - It's playtime.
* "Es carne de rata." - It's rat meat.
* "Es tan temprano." - It's so early.
* "Está muy mal." - It's so wrong.
* "Es la hora del té." - It's tea time.
* "Hace demasiado frío." - It's too cold.
* "Está muy oscuro." - It's too dark.
* "Es demasiado fácil." - It's too easy.
* "Es demasiado rápido." - It's too fast.
* "Es muy tarde." - It's too late.
* "Está demasiado alto." - It's too loud.
* "Es demasiado pronto." - It's too soon.
* "Depende de mí." - It's up to me.
* "Me corresponde a mí." - It's up to me.
* "Es muy grande." - It's very big.
* "Es muy seco." - It's very dry.
* "Está muy seco." - It's very dry.
* "Está muy caliente." - It's very hot.
* "Es muy viejo." - It's very old.
* "Es muy vieja." - It's very old.
* "Es muy triste." - It's very sad.
* "Vale la pena." - It's worth it.
* "Lo logramos." - We succeeded.
* "Lo conseguimos." - We succeeded.
* "Nos rendimos." - We surrender.
* "¡Queremos cerveza!". - We want beer!
* "Queremos carne." - We want meat.
* "Queremos más." - We want more.
* "Estábamos ocupados." - We were busy.
* "Estábamos heridos." - We were hurt.
* "Estábamos lastimados." - We were hurt.
* "Tomaremos una decisión." - We'll decide.
* "Saldremos." - We'll go out.
* "Gritaremos." - We'll scream.
* "Lo intentaremos." - We'll try it.
* "Somos adultos." - We're adults.
* "Estamos asustados." - We're afraid.
* "Estamos mejor." - We're better.
* "Somos mejores." - We're better.
* "Estamos cerrados." - We're closed.
* "Ya vamos." - We're coming.
* "Vamos a ir." - We're coming.
* "Estamos llorando." - We're crying.
* "Estamos saliendo." - We're dating.
* "Estamos comiendo." - We're eating.
* "Estamos desahuciados." - We're goners.
* "Somos invitados." - We're guests.
* "Nosotros estamos escondidos." - We're hiding.
* "Somos humanos." - We're humans.
* "Nosotros somos humanos." - We're humans.
* "Estamos hambrientos." - We're hungry.
* "Estamos adentro." - We're inside.
* "Estamos bromeando." - We're joking.
* "Bromeamos." - We're joking.
* "Todos lo sabíamos." - We all knew it.
* "Todos lo sabemos." - We all know it.
* "Eso lo sabemos todos." - We all know it.
* "Nosotros ya comimos." - We already ate.
* "Estamos en casa." - We are at home.
* "Somos primos." - We are cousins.
* "Somos médicos." - We are doctors.
* "Nosotros somos doctores." - We are doctors.
* "No estamos seguros." - We aren't sure.
* "Podemos hacerlo." - We can do that.
* "Nosotros podemos pagarte." - We can pay you.
* "No podemos hacerlo." - We can't do it.
* "Cocinamos con gas." - We cook on gas.
* "Abandonamos a Tom." - We ditched Tom.
* "Bebimos mucho." - We drank a lot.
* "Comemos en casa." - We eat at home.
* "Exageramos." - We exaggerated.
* "Iremos mañana." - We go tomorrow.
* "Vamos mañana." - We go tomorrow.
* "Nos vamos mañana." - We go tomorrow.
* "Nos hemos casado." - We got married.
* "Nos casamos." - We got married.
* "Tuvimos que parar." - We had to stop.
* "Tenemos un plan." - We have a plan.
* "Hemos fallado." - We have failed.
* "Hemos fracasado." - We have failed.
* "Tenemos bastante." - We have plenty.
* "Ahora sabemos." - We know it now.
* "Necesitamos un plan." - We need a plan.
* "Tenemos dinero." - We have money.
* "Tenemos planes." - We have plans.
* "Tenemos reglas." - We have rules.
* "Deberíamos irnos." - We have to go.
* "Tenemos que irnos." - We have to go.
* "Ayudamos a Tom." - We helped Tom.
* "Nosotros ayudamos a Tom." - We helped Tom.
* "Lo ayudamos." - We helped him.
* "Nosotros lo ayudamos." - We helped him.
* "Nosotras lo ayudamos." - We helped him.
* "Nosotros disparamos a un ciervo." - We hit a deer.
* "Nos quedamos en silencio." - We kept quiet.
* "Nos quedamos callados." - We kept quiet.
* "Mantuvimos la calma." - We kept still.
* "Matamos a Tom." - We killed Tom.
* "Nos gustan los juegos." - We like games.
* "Nos gusta la ópera." - We like opera.
* "Nos gustan los árboles." - We love trees.
* "Teníamos buena intención." - We meant well.
* "Lo hicimos de buena fe." - We meant well.
* "Quizá perdamos." - We might lose.
* "Necesitamos un coche." - We need a car.
* "Necesitamos dinero." - We need money.
* "Necesitamos música." - We need music.
* "Necesitamos agua." - We need water.
* "Nos hace falta agua." - We need water.
* "Nunca hablamos." - We never talk.

Note: Some of the phrases may have multiple translations or variations depending on the context and the region.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Así, así.
English:  Okay, here are the translations for the given phrases:

* ¿Cómo iba a saberlo? - How was he supposed to know?
* ¿Cómo iba yo a saberlo? - How was I supposed to know?
* ¡Cómo has crecido! - How you've grown!
* ¿Qué tal te va? - How are you doing?
* ¿Cómo lo llevas? - How are you doing?
* ¿Cómo está el cuello de Tom? - How is Tom's neck?
* ¿Cómo va el trabajo? - How's work going?
* ¿Cómo va tu trabajo? - How's your work going?
* Por favor, date prisa. - Hurry up, please.
* Aborrezco la violencia. - I abhor violence.
* Estoy de acuerdo con Tom. - I agree with Tom.
* Estoy de acuerdo con él. - I agree with him.
* Estoy de acuerdo con usted. - I agree with you.
* Casi me ahogué. - I almost drowned.
* Casi me rindo. - I almost gave up.
* Casi cedo. - I almost gave up.
* Casi lo dejo. - I almost gave up.
* Ya lo hice. - I already did it.
* Ya lo vi. - I already saw it.
* A mi también me gustan los pasteles. - I also like cake.
* También me gustan los perros. - I also like dogs.
* Siempre como afuera. - I always eat out.
* Estoy un poco bebido. - I am a bit drunk.
* Estoy un poquito borracho. - I am a bit drunk.
* Estoy un poco borracho. - I am a bit drunk.
* Me lo comí. - I ate it.
* Me la comí. - I ate it.
* Puedo ir. - I can go.
* Maldije. - I cursed.
* Despotriqué. - I cursed.
* Lo hice bien. - I did OK.
* Lo hice. - I did it.
* Fracasé. - I failed.
* Fallé. - I failed.
* Lo olvidé. - I forgot.
* Me las arreglo. - I get by.
* Lo entiendo. - I get it.
* Lo tengo. - I got it.
* Lo tenía. - I had it.
* Ayudé. - I helped.
* Salté. - I jumped.
* Miré. - I looked.
* Llamé por teléfono. - I phoned.
* Recé. - I prayed.
* Me niego. - I refuse.
* Dimito. - I resign.
* Renuncio. - I resign.
* Me senté. - I sat up.
* Lo vi. - I saw it.
* Me rasuré. - I shaved.
* Suspiré. - I sighed.
* Sonreí. - I smiled.
* Me quedé. - I stayed.
* Hablé. - I talked.
* Hablaba. - I talked.
* Charlé. - I talked.
* Charlaba. - I talked.
* Yo lo uso. - I use it.
* Esperé. - I waited.
* Yo pagaré. - I'll pay.
* He vuelto. - I'm back.
* Estoy de vuelta. - I'm back.
* ¡He vuelto! - I'm back.
* Soy calvo. - I'm bald.
* Estoy calvo. - I'm bald.
* Estoy calmado. - I'm calm.
* Estoy tranquilo. - I'm cool.
* Soy sordo. - I'm deaf.
* He terminado. - I'm done.
* Estoy acabado. - I'm done.
* Lo dejo. - I'm done.
* Soy bastante facilón. - I'm easy.
* Es el turno de Tom. - It's Tom's turn.
* No es un buen momento. - It's a bad time.
* Es un mal momento. - It's a bad time.
* Es una gran ciudad. - It's a big city.
* Es un gran paso. - It's a big step.
* Es un callejón sin salida. - It's a dead end.
* Es un número fraccionario. - It's a fraction.
* Es una seta. - It's a mushroom.
* Es un libro nuevo. - It's a new book.
* Es un atajo. - It's a shortcut.
* Es una sorpresa. - It's a surprise.
* Ya casi es hora. - It's about time.
* Es aceptable. - It's acceptable.
* Eso es todo lo que tengo. - It's all I have.
* Eso es todo lo que quiero. - It's all I want.
* Son casi las seis. - It's almost six.
* Ya casi son las seis. - It's almost six.
* Es un engendro. - It's an eyesore.
* Es artificial. - It's artificial.
* Hace frío hoy. - It's cold today.
* Hoy hace fresco. - It's cool today.
* Es la hora de la cena. - It's dinnertime.
* Está botado. - It's dirt-cheap.
* Es trabajo sucio. - It's dirty work.
* Es dinero fácil. - It's easy money.
* Hoy hace bueno. - It's fine today.
* Es imposible. - It's impossible.
* ¡Es increíble! - It's incredible.
* Disculpe a Tom. - Forgive Tom.
* Disculpa a Tom. - Forgive Tom.
* Vístete. - Get dressed.
* Vestite - Get dressed.
* ¡Entra aquí! - Get in here!
* ¡Ponte serio! - Get serious!
* Empieza. - Get started.
* Id a descansar. - Go and rest.
* Ve a descansar. - Go and rest.
* Vete a descansar. - Go and rest.
* Iros a descansar. - Go and rest.
* Vaya a descansar. - Go and rest.
* Vayan a descansar. - Go and rest.
* Ve a encontrar a Tom. - Go find Tom.
* Vayan a encontrar a Tom. - Go find Tom.
* Ve a buscar a Tom. - Go find Tom.
* Ve a tumbarte. - Go lie down.
* Ve a acostarte. - Go lie down.
* Ve a ver a Tom. - Go meet Tom.
* Ve por ahí. - Go that way.
* Ve por allí. - Go that way.
* Ve a dormir. - Go to sleep.
* ¡Váyanse a dormir! - Go to sleep.
* ¡Ve a dormir! - Go to sleep.
* ¡Vete a dormir! - Go to sleep.

Note: Some of the phrases may have multiple translations or variations depending on the context and the region.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: No muy bien.
English:  No es verdad.
Ahora son las dos y media.
Es obsoleto.
Está ocupado.
Es oficial.
Es hora del té.
Hace demasiado frío.
Es muy oscuro.
Es demasiado fácil.
Es demasiado rápido.
Es muy tarde.
Es demasiado alto.
Es muy seco.
Es muy caliente.
Es muy viejo.
Es muy vieja.
Es muy triste.
Vale la pena.
Yo hago bien mi trabajo.
Claro que lo recuerdo.
No como pescado.
No como carne.
No como carne de cerdo.
No te envidio.
No tengo ninguno.
No la conozco.
No le conozco.
No sé por qué.
No sé la causa.
No conozco la razón.
Todavía no lo sé.
Aún no lo sabe.
No le conozco.
No te conozco.
No os conozco.
No les conozco.
No me gusta Tom.
Ella no me simpatiza.
Ella no me gusta.
No me cae bien.
Me cae mal.
No me gustas.
Me caes mal.
Me caes gordo.
No amo a Tom.
No la amo.
¿El color de su carro es negro?
¿Tu auto es negro?
¿Tu perro es blanco?
¿Tu micro es desactivado?
¿Tu esposa es alta?
¿No es emocionante?
¿No es patético?
¿No es impresionante?
¿Eso no es de ellos?
No se puede arreglar.
No puede ser cierto.
No puede ser verdad.
Eso no puede ser verdad.
Cuesta demasiado caro.
Podría ser fatal.
Lo pasó mal.
No me queda.
No es importante.
Eso no importa.
No importa.
Se hizo pedazos.
Funciona en ambos sentidos.
Ha refrescado.
Hay que hacerlo.
Debe de ser verdad.
Depende de ti.
No es un montaje.
No es un pez.
No está roto.
No se quebró.
Esto no es suficiente.
Me molesta.
Se veía horrible.
Se veía barato.
Puede parecer raro.
Esto puede parecer extraño.
Podría suceder.
Tiene que ser aquí.
Debe de ser verdad.
Realmente funciona.
Verdaderamente va.
Sí que funciona.
Parece probable.
¡Suena genial!
¡Me parece bien!
Suena raro.
Sabía dulce.
Era un secreto.
Fue muy emocionante.
Pasó hace siglos.
Todo terminó.
Todo estaba bien.
Fue un honor.
Es hora del té.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¡Adiós!
English:  Goodbye!

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Hasta mañana.
English:  See you tomorrow.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Hasta luego.
English:  Goodbye.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Hasta pronto.
English:  Until soon.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Nos vemos.
English:  We see each other.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Gracias.
English:  Here is the translation of the Spanish text to English:

Thanks.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Por favor.
English:  * Pass the ketchup: Por favor, pásame el ketchup.
* Pay what you can: Por favor, paga lo que puedas.
* People are dying: La gente está muriendo.
* People are funny: La gente es ridícula.
* People love dogs: La gente ama a los perros.
* People will talk: La gente hablará.
* Pets are allowed: Se permiten mascotas.
* Phone the police: Llama a la Policía.
* Please answer me: Por favor, respóndeme.
* Please be gentle: Por favor, sé un caballero.
* Please be polite: Por favor, sé educado.
* Please calm down: Por favor, cálmate.
* Please come here: Por favor, ven aquí.
* Please come quickly: ¡Ven rápido!
* Please help me: Ven a ayudarme.
* Please come and help me: Ven a echarme una mano.
* Please come and join us: Ven y únetenos.
* Come home at six: Vuelve a la casa a las seis.
* Come on out here: Sal aquí.
* Come on, wake up: Vamos, despierta.
* Come sit with us: Ven a sentarse con nosotros.
* Come to my house: Venga a mi casa.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: De nada.
English:  "No worries."

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Lo siento.
English:  Here are the translations of the given sentences:

1. ¿El color de su carro es negro? - Is your car black?
Translation: The color of your car is black.
2. ¿Tu auto es negro? - Is your car black?
Translation: Your car is black.
3. ¿Tu perro es blanco? - Is your dog white?
Translation: Your dog is white.
4. ¿Está tu micro desactivado? - Is your mic muted?
Translation: Is your microphone muted?
5. ¿Tu esposa es alta? - Is your wife tall?
Translation: Your wife is tall.
6. ¿No es emocionante? - Isn't it exciting?
Translation: It's not exciting.
7. ¿No es patético? - Isn't it pathetic?
Translation: It's not pathetic.
8. ¿No es impresionante? - Isn't it stunning?
Translation: It's not stunning.
9. ¿Eso no es de ellos? - Isn't that theirs?
Translation: That's not theirs.
10. No se puede arreglar. - It can't be fixed.
Translation: It can't be fixed.
11. No puede ser cierto. - It cannot be true.
Translation: It cannot be true.
12. No puede ser verdad. - It cannot be true.
Translation: It cannot be true.
13. Eso no puede ser verdad. - It cannot be true.
Translation: It cannot be true.
14. Cuesta demasiado caro. - It costs too much.
Translation: It costs too much.
15. Podría ser fatal. - It could be fatal.
Translation: It could be fatal.
16. Lo pasó mal. - It didn't go well.
Translation: It didn't go well.
17. No me queda. - It doesn't fit me.
Translation: It doesn't fit me.
18. No es importante. - It doesn't matter.
Translation: It doesn't matter.
19. Eso no importa. - It doesn't matter.
Translation: It doesn't matter.
20. No importa. - It doesn't matter.
Translation: It doesn't matter.
21. Se hizo pedazos. - It fell to pieces.
Translation: It fell to pieces.
22. Functiona en ambos sentidos. - It goes both ways.
Translation: It goes both ways.
23. Hay que hacerlo. - It has to be done.
Translation: It has to be done.
24. Debe de ser verdad. - It has to be true.
Translation: It has to be true.
25. Tom está levantado. - Tom is up.
Translation: Tom is up.
26. Tom teje. - Tom knits.
Translation: Tom knits.
27. Tom sabe. - Tom knows.
Translation: Tom knows.
28. Tom se mudó. - Tom moved.
Translation: Tom moved.
29. Tom se movió. - Tom moved.
Translation: Tom moved.
30. Tom se mece. - Tom rocks.
Translation: Tom rocks.
31. Tom se quedó. - Tom stood.
Translation: Tom stood.
32. Tom nada. - Tom swims.
Translation: Tom swims.
33. Tom juró. - Tom swore.
Translation: Tom swore.
34. Tomás lo intentó. - Tom tried.
Translation: Tom tried.
35. Tomás lo intenta. - Tom tries.
Translation: Tom tries.
36. Tomás votó. - Tom voted.
Translation: Tom voted.
37. Tom camina. - Tom walks.
Translation: Tom walks.
38. Tom saludó. - Tom waved.
Translation: Tom waved.
39. Tomás trabaja. - Tom works.
Translation: Tom works.
40. Tom irá. - Tom'll go.
Translation: Tom'll go.
41. Tom está gordo. - Tom's fat.
Translation: Tom is fat.
42. Tom está loco. - Tom's mad.
Translation: Tom is mad.
43. Tom está triste. - Tom's sad.
Translation: Tom is sad.
44. Tom es tímido. - Tom's shy.
Translation: Tom is shy.
45. Confía en Tom. - Trust Tom.
Translation: Trust Tom.
46. Inténtalo de nuevo. - Try again.
Translation: Try again.
47. Intentadlo otra vez. - Try again.
Translation: Try again.
48. Intenta otra vez. - Try again.
Translation: Try again.
49. Pruébatelo. - Try it on.
Translation: Try it on.
50. Abre el candado. - Unlock it.
Translation: Unlock it.
51. Espera aquí. - Wait here.
Translation: Wait here.
52. Aguarda aquí. - Wait here.
Translation: Wait here.
53. Esperen aquí. - Wait here.
Translation: Wait here.
54. Esperad aquí. - Wait here.
Translation: Wait here.
55. Vigila a Tom. - Watch Tom.
Translation: Watch Tom.
56. ¡Abusado! - Watch out!
Translation: Watch out!
57. Nos pusimos de acuerdo. - We agreed.
Translation: We agreed.
58. Podemos ir. - We can go.
Translation: We can go.
59. Podemos irnos. - We can go.
Translation: We can go.
60. Nos podemos marchar. - We can go.
Translation: We can go.
61. Lo logramos. - We did it.
Translation: We did it.
62. Fallamos. - We failed.
Translation: We failed.
63. Hemos fallado. - We failed.
Translation: We failed.
64. Deja de gritar. - Stop yelling.
Translation: Stop yelling.
65. Por favor, párate. - Stop, please.
Translation: Stop, please.
66. Estudia más. - Study harder.
Translation: Study harder.
67. Estudiad más. - Study harder.
Translation: Study harder.
68. ¡Felices sueños! - Sweet dreams!
Translation: Sweet dreams!
69. ¡Dulces sueños! - Sweet dreams!
Translation: Sweet dreams!
70. Dulces sueños. - Sweet dreams.
Translation: Sweet dreams.
71. Enciéndelo. - Switch it on.
Translation: Switch it on.
72. Descanse. - Take a break.
Translation: Take a break.
73. Tómate un descanso. - Take a break.
Translation: Take a break.
74. Toma el control. - Take command.
Translation: Take command.
75. Hazte con el control. - Take command.
Translation: Take command.
76. Toma el control. - Take control.
Translation: Take control.
77. ¡Relajate! - Take it easy!
Translation: Take it easy!
78. ¡Relájate! - Take it easy!
Translation: Take it easy!
79. Llévatelo a casa. - Take it home.
Translation: Take it home.
80. Llévatelo. - Take it home.
Translation: Take it home.
81. Tomate el bondi. - Take the bus.
Translation: Take the bus.
82. Llevaos a casa. - Take us home.
Translation: Take us home.
83. Dile a Tom por qué. - Tell Tom why.
Translation: Tell Tom why.
84. Cuéntame más. - Tell me more.
Translation: Tell me more.
85. Dime más. - Tell me more.
Translation: Tell me more.
86. Díganos más. - Tell us more.
Translation: Tell us more.
87. Dígnos más. - Tell us more.
Translation: Tell us more.
88. Yo vi un OVNI. - I saw a UFO.
Translation: I saw a UFO.
89. Ví a un perro. - I saw a dog.
Translation: I saw a dog.
90. Ví un perro. - I saw a dog.
Translation: I saw a dog.
91. Yo vi un perro. - I saw a dog.
Translation: I saw a dog.
92. Vendo autos. - I sell cars.
Translation: I sell cars.
93. Vendo coches. - I sell cars.
Translation: I sell cars.
94. Vendo pescado. - I sell fish.
Translation: I sell fish.
95. Vendo jabón. - I sell soap.
Translation: I sell soap.
96. Me debería ir. - I should go.
Translation: I should go.
97. Huelo a gas. - I smell gas.
Translation: I smell gas.
98. Huelo gas. - I smell gas.
Translation: I smell gas.
99. Me huele a gas. - I smell gas.
Translation: I smell gas.
100. Te lo agradezco. - I trust you.
Translation: I trust you.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Perdón.
English:  Here are the translations for the given phrases:

* Obsérvanos: Watch us.
* Estamos de acuerdo: We agree.
* Lo intentamos: We tried.
* Iremos: We'll go.
* Estamos bien: We're OK.
* ¿Para qué?: What for?
* ¡Qué divertido!" : What fun!
* ¿Y ahora qué?: What now?
* ¿Quién soy yo?: Who am I?
* ¿Quién soy?: Who am I?
* ¿Quién vino?: Who came?
* ¿Quién murió?: Who died?
* ¿Quién se calló?: Who fell?
* ¿Quién se cayó?: Who fell?
* ¿Quién perdió?: Who lost?
* ¿Quién pagó?: Who paid?
* ¿Quién se ha ido?: Who quit?
* ¿Quién lo ha dejado?: Who quit?
* ¿Quién nadó?: Who swam?
* ¿Quién es él?: Who's he?
* Escríbeme: Write me.
* Perdiste: You lost.
* Has perdido: You lost.
* Perdisteis: You lost.
* Han perdido: You lost.
* No puedo negarlo: I can't deny it.
* No lo puedo negar: I can't deny it.
* Yo no puedo hacer eso: I can't do that.
* No lo puedo sentir: I can't feel it.
* No puedo encontrarlo: I can't find it.
* No puedo rendirme: I can't give up.
* No puedo volver: I can't go back.
* No puedo ir a casa: I can't go home.
* No lo puedo oír: I can't hear it.
* No puedo oírlo: I can't hear it.
* No puedo evitarlo: I can't help it.
* No te lo puedo permitir: I can't let you.
* No puedo hacerlo: I can't make it.
* No puedo ver a Tom: I can't see Tom.
* No puedo verte: I can't see you.
* No puedo veros: I can't see you.
* No puedo verlo: I can't see you.
* No puedo ingresar: I can't sign in.
* No puedo deshacerlo: I can't undo it.
* No sé silbar: I can't whistle.
* Me resfrié: I caught a cold.
* Pillé un resfriado: I caught a cold.
* ¡Atrapé un pez!: I caught a fish!
* Capturé una anguila: I caught an eel.
* Cogí una anguila: I caught an eel.
* Me acobardé: I chickened out.
* Cociné la cena: I cooked dinner.
* Tomá otro: Have another.
* Tomá otra: Have another.
* Toma otra: Have another.
* Toma otro: Have another.
* Tome otro: Have another.
* Tome otra: Have another.
* Sé valiente: Have courage.
* Sed valientes: Have courage.
* Él me evita: He avoids me.
* Él lo negó: He denied it.
* Se quedó dormido: He dozed off.
* Él se enfadó: He got angry.
* Él tenía un perro: He had a dog.
* Él tiene un perro: He has a dog.
* Tiene un perro: He has a dog.
* La ayuda: He helps her.
* Está enfadado: He is cranky.
* Está de morros: He is cranky.
* Él está motivado: He is driven.
* Está comiendo: He is eating.
* No está aquí: He is not in.
* Él no está dentro: He is not in.
* Él lo pateó: He kicked it.
* Me dejó ir: He let me go.
* Dejó que me fuera: He let me go.
* Nos dejó irnos: He let us go.
* Dejó que nos fuéramos: He let us go.
* Le gusta el té: He likes tea.
* Él le gusta el té: He likes tea.
* Él fue humillado: He lost face.
* Él quedó mal: He lost face.
* Él perdió prestigio: He lost face.
* Él la quiere: He loves her.
* Él la quiere: He loves her.
* Me gusta tu coche: I like your car.
* Me gusta su gato: I like your cat.
* Me gusta tu perro: I like your dog.
* Me gusta vuestro perro: I like your dog.
* Me gusta tu corbata: I like your tie.
* A mí también me ha gustado: I liked it, too.
* Ahora vivo aquí: I live here now.
* Vivo aquí ahora: I live here now.
* Vivo en Japón: I live in Japan.
* Vivo con Tom: I live with Tom.
* Miré a mi alrededor: I looked around.
* Miré a Tom: I looked at Tom.
* Perdí las ganas: I lost interest.
* Perdí el interés: I lost interest.
* Perdí mi reloj: I lost my watch.
* Perdí el juego: I lost the game.
* Perdí la partida: I lost the game.
* Perdí la lista: I lost the list.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Disculpe.
English:  Sorry.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Con permiso.
English:  Sure! Here are the translations for the given sentences:

* Salimos a las dos y media. - We left at 2:30.
* Nos gusta conversar. - We like to talk.
* Nos encanta esta zona. - We love it here.
* Nos encanta estar aquí. - We love it here.
* Nos encantan los picnics. - We love picnics.
* Nos encanta ayudar. - We love to help.
* Le hicimos llorar. - We made him cry.
* Hicimos waffles. - We made waffles.
* Hicimos gofres. - We made waffles.
* Conocimos un escritor. - We met a writer.
* Debemos ver a Tom. - We must see Tom.
* Deberíamos ganar. - We ought to win.
* Le pagamos bien a Tom. - We pay Tom well.
* Castigamos a Tom. - We punished Tom.
* Nos acordamos de Tom. - We remember Tom.
* Los respetamos. - We respect them.
* Las respetamos. - We respect them.
* Nosotros cantamos para ella. - We sang for her.
* Compartimos ideas. - We shared ideas.
* Debemos irnos. - We should leave.
* Hablamos francés. - We speak French.
* Estudiamos francés. - We study French.
* Anduvimos mucho. - We walked a lot.
* Lo queremos de vuelta. - We want it back.
* Queremos justicia. - We want justice.
* Queremos ayudar. - We want to help.
* Vivimos en paz. - We live in peace.
* Vivimos juntos. - We live together.
* Perdimos la partida. - We lost the game.
* Nos referimos a negocios. - We mean business.
* Nos conocimos en Boston. - We met in Boston.
* Nos conocimos la semana pasada. - We met last week.
* Debemos continuar. - We must continue.
* Debemos evacuar. - We must evacuate.
* Tenemos que evacuar. - We must evacuate.
* Debemos arreglar esto. - We must fix this.
* Tenemos que sentarnos. - We must sit down.
* Debemos sentarnos. - We must sit down.
* Tenemos que avisarnle. - We must warn him.
* Debemos retirarnos. - We must withdraw.
* Necesitamos una escalera. - We need a ladder.
* Necesitamos un líder. - We need a leader.
* Necesitamos pruebas. - We need evidence.
* Necesitamos que regreses. - We need you back.
* Necesitamos tu llave. - We need your key.
* Necesitamos vuestra llave. - We need your key.
* Necesitamos su llave. - We need your key.
* Necesitamos tu clave. - We need your key.
* Necesitamos vuestra clave. - We need your key.
* Necesitamos su clave. - We need your key.
* El crimen no compensa. - Crime doesn't pay.
* La delincuencia no compensa. - Crime doesn't pay.
* Dame un respiro. - Cut me some slack.
* Repártenos los naipes. - Deal us the cards.
* La muerte es inminente. - Death is imminent.
* Defendeos. - Defend yourselves.
* Describídmelo. - Describe it to me.
* Describámelo. - Describe it to me.
* Describámela. - Describe it to me.
* Describate a sí mismo. - Describe yourself.
* No te pases de vueltas, Tom. - Dial it back, Tom.
* Did I wake Tom up? - Did I wake you up?
* Did Tom come here? - Did Tom come here?
* Did Tom come home? - Did Tom come home?
* Did Tom hurt Mary? - Did Tom hurt Mary?
* Did Tom kiss Mary? - Did Tom kiss Mary?
* Did Tom know Mary? - Did Tom know Mary?
* Did he fail again? - Did he fail again?
* Did my phone ring? - Did my phone ring?
* Did you feed them? - Did you feed them?
* Did they hurt you? - Did they hurt you?
* I can't trust him. - I can't trust him.
* I can't trust you. - I can't trust you.
* I can't trust you. - I can't trust you.
* I chose to resign. - I chose to resign.
* I came from Japan. - I come from Japan.
* I come here often. - I come here often.
* I do it often. - I do it often.
* I consented to go. - I consented to go.
* I couldn't answer. - I couldn't answer.
* I couldn't get it. - I couldn't get it.
* I couldn't refuse. - I couldn't refuse.
* I cried all night. - I cried all night.
* I defended myself. - I defended myself.
* I demand a refund. - I demand a refund.
* I deny everything. - I deny everything.
* I did you a favor. - I did you a favor.
* I didn't bite Tom. - I didn't bite Tom.
* I didn't buy that. - I didn't buy that.
* I didn't buy them. - I didn't buy them.
* No mordí a Tom. - I didn't bite Tom.
* No compré eso. - I didn't buy that.
* No compré eso. - I didn't buy that.
* No me pude rehusar. - I couldn't refuse.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¡Salud!
English:  Here are the translations for the given phrases:

* ¡Salud! - Cheerio!
* Nos gusta conversar. - We like to talk.
* Nos encanta esta zona. - We love it here.
* Nos encanta estar aquí. - We love it here.
* Nos encantan los picnics. - We love picnics.
* Nos encanta ayudar. - We love to help.
* Le hicimos llorar. - We made him cry.
* Hicimos waffles. - We made waffles.
* Hicimos gofres. - We made waffles.
* Conocimos un escritor. - We met a writer.
* Debemos ver a Tom. - We must see Tom.
* Deberíamos ganar. - We ought to win.
* Le pagamos bien a Tom. - We pay Tom well.
* Castigamos a Tom. - We punished Tom.
* Nos acordamos de Tom. - We remember Tom.
* Los respetamos. - We respect them.
* Las respetamos. - We respect them.
* Nosotros cantamos para ella. - We sang for her.
* Compartimos ideas. - We shared ideas.
* Deberíamos irnos. - We should leave.
* Hablamos francés. - We speak French.
* Estudiamos francés. - We study French.
* Anduvimos mucho. - We walked a lot.
* Lo queremos de vuelta. - We want it back.
* Queremos justicia. - We want justice.
* Queremos ayudar. - We want to help.
* ¡No esperes! - Don't wait!
* ¡No esperen! - Don't wait!
* No esperes. - Don't wait!
* No grites. - Don't yell.
* No chilles. - Don't yell.
* No chilléis. - Don't yell.
* No chille. - Don't yell.
* No chillen. - Don't yell.
* Come despacio. - Eat slowly.
* ¡Comé despacio! - Eat slowly!
* Disfruta la vida. - Enjoy life!
* ¡Enfréntate a los hechos! - Face facts!
* ¡Enfrentaos a los hechos! - Face facts!
* ¡Enfréntese a los hechos! - Face facts!
* ¡Enfréntense a los hechos! - Face facts!
* El fuego quema. - Fire burns.
* Seguilo a Tomás. - Follow Tom.
* Sígalo a Tomás. - Follow Tom.
* Sígalo. - Follow him.
* Sígalo. - Follow him.
* Olvidate de Tomás. - Forget Tom.
* Olvídate de Tomás. - Forget Tom.
* Olvídenlo. - Forget him.
* Perdónanos. - Forgive us.
* Perdónenos. - Forgive us.
* Consíguete una vida. - Get a life.
* Búscate una vida. - Get a life.
* Entra. - Get inside.
* Vete a la cama. - Go on home.
* Déjalo. - Give it up.
* Ríndanse. - Give it up.
* Vete a casa. - Go on home.
* Váyase a casa. - Go on home.
* Más alto. - Aim higher.
* Apuntad más alto. - Aim higher.
* ¡Todos a bordo! - All aboard!
* ¡Al abordaje! - All aboard!
* ¿Me estoy muriendo? - Am I dying?
* ¿Estoy despedido? - Am I fired?
* ¿Estoy contratado? - Am I hired?
* ¿Estoy listo? - Am I ready?
* ¿Tengo razón? - Am I right?
* ¿Me equivoco? - Am I wrong?
* ¿Estoy equivocado? - Am I wrong?
* ¡Respóndale a Tomás! - Answer Tom.
* ¡Respondele a Tomás! - Answer Tom.
* ¡Respóndanle a Tomás! - Answer Tom.
* ¿Tienes dieciocho? - Are you 18?
* ¿Has cumplido dieciocho? - Are you 18?
* ¿Estás bien? - Are you OK?
* ¿Te apuntas? - Are you in?
* ¿Estás dentro? - Are you in?
* ¿Estás levantado? - Are you up?
* Pregúntale a cualquiera. - Ask anyone.
* Preguntadle a cualquiera. - Ask anyone.
* Pregúntele a cualquiera. - Ask anyone.
* Pregúntenle a cualquiera. - Ask anyone.
* ¡Ten cuidado! - Be careful!
* ¡Ten cuidado! - Be careful!
* ¡Sé cuidadoso! - Be careful!
* Estamos contentos. - We're content.
* Llega a tiempo. - Be on time.
* Llegue a tiempo. - Be on time.
* Sea paciente. - Be patient.
* Estamos muertos de hambre. - We're famished.
* Somos ingenuos. - We're gullible.
* Estamos sin esperanza. - We're hopeless.
* Estamos involucradas. - We're involved.
* Estamos involucrados. - We're involved.
* No somos pobres. - We're not poor.
* No somos ricos. - We're not rich.
* No estamos seguros. - We're not sure.
* Estamos de vacaciones. - We're on leave.
* Somos pacientes. - We're patients.
* Somos confiables. - We're reliable.
* Somos inquietos. - We're restless.
* Ahora estamos a salvo. - We're safe now.
* Somos tan felices. - We're so happy.
* Estamos tan felices. - We're so happy.
* Nos morimos de hambre. - We're starving.
* Estamos colgados. - We're stranded.
* Somos profesoras. - We're teachers.
* Somos los mejores. - We're the best.
* Somos minuciosos. - We're thorough.
* Nos levantamos temprano. - We're up early.
* Estamos muy tristes. - We're very sad.
* Estamos observando. - We're watching.
* Estamos mirando. - We're watching.
* Observamos. - We're watching.
* Miramos. - We're watching.
* Estamos con vos. - We're with you.
* Se nos ha golpeado. - We've been hit.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Buen provecho.
English:  Enjoy your meal.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¡Buena suerte!
English:  Good luck!

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Cuídate.
English:  Here is the translation of the Spanish text to English:

Take care of yourself.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¿Cómo te llamas?
English:  How are you?

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¿Cuál es tu nombre?
English:  My name is...

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Me llamo Michael.
English:  Soy Michael.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Mucho gusto.
English:  Hello! Here is the translation of the text you provided:

Mucho gusto!

I like:

* This watch (Me gusta este reloj de pulsera.)
* Being here (Me gusta estar aquí.)
* Watermelon (Me gusta la sandía.)
* Your horse (Me gusta tu caballo.)
* Your house (Me gusta tu casa.)
* Your ideas (Me gustan tus ideas.)
* Your phone (Me gusta tu teléfono.)
* Your scarf (Me gusta tu bufanda.)
* Your shirt (Me gusta tu camisa.)
* Your style (Me gusta tu estilo.)
* Your truck (Me gusta tu camión.)
* Your voice (Me gusta tu voz.)
* The movie (La película me gustó.)
* Boston (Vivo en Boston.)
* Locking the door (He bloqueado la puerta.)
* Losing an earring (Perdí un arete.)
* Reading (Me gusta mucho leer.)
* Sashimi (Me gusta el sashimi.)
* Seafood (Me gusta los mariscos.)
* Singing (Me gusta cantar.)
* Stories (Me gusta las historias.)
* Talking (Me gusta hablar.)
* Walking (Me gusta caminar.)
* Working (Me gusta trabajar.)
* Loving animals (Me encanta los animales.)
* Ice cream (Me gusta el helado.)
* Junk food (Me gusta la comida chatarra.)
* Languages (Me gusta los idiomas.)
* Math (Lo que más me gusta son las matemáticas.)
* Pop music (Me gusta la música pop.)
* Red roses (Me gusta las rosas rojas.)
* Surprises (Me gusta las sorpresas.)
* That flag (Me gusta esa bandera.)
* That name (Me gusta ese nombre.)
* That song (Me gusta esa canción.)
* The beach (Me gusta la playa.)
* This book (Me gusta este libro.)
* This city (Me gusta esta ciudad.)
* This plan (Me gusta este plan.)

I hope this helps! Let me know if you have any other questions.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Un placer.
English:  A pleasure.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: El placer es mío.
English:  He is mine.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Encantado/Encantada
English:  Here are the translations for "encantado/encantada" in the context provided:

* Encantado: I love (something)
	+ Example: Me encanta el brécol. (I love broccoli)
* Encantada: I love (something)
	+ Example: Me encantan las berenjenas. (I love eggplant)
* Encantado: I love to (do something)
	+ Example: Me encanta enseñar. (I love teaching)
* Encantada: I love to (do something)
	+ Example: Me encanta aprender. (I love learning)
* Encantado: I love you (to someone)
	+ Example: Te amo a ti. (I love you, too)
* Encantada: I love you (to someone)
	+ Example: Los amo a los dos. (I love you both)

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¿De dónde eres?
English:  Where are you from?

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Soy de los Estados Unidos.
English:  I am from the United States.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¿Qué edad tienes?
English:  "¿Cuánto tienes?"

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¿Cuántos años tienes?
English:  How old are you?

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¿Cuándo es tu cumpleaños?
English:  When is your birthday?

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¿A qué te dedicas?
English:  You dedicate yourself to:

* Leer: Leer
* Hacer: Hacer
* Ver: Ver
* Oír: Oír
* Pagar: Pagar
* Ayudar: Ayudar
* Hacer: Hacer
* Ver: Ver
* Oír: Oír
* Pagar: Pagar
* Quedarse: Quedarse
* Ir: Ir
* Venir: Venir
* Hacer: Hacer
* Ver: Ver
* Oír: Oír
* Pagar: Pagar
* Ayudar: Ayudar
* Hacer: Hacer
* Ver: Ver
* Oír: Oír
* Pagar: Pagar
* Quedarse: Quedarse
* Ir: Ir
* Venir: Venir
* Hacer: Hacer
* Ver: Ver
* Oír: Oír
* Pagar: Pagar
* Ayudar: Ayudar
* Hacer: Hacer
* Ver: Ver
* Oír: Oír
* Pagar: Pagar
* Quedarse: Quedarse
* Ir: Ir
* Venir: Venir

Note: Some of the phrases in the original text may not be idiomatic or correct in English, and I may have changed them for clarity or accuracy.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Soy astronauta.
English:  You are an astronaut.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¿En qué trabajas?
English:  You work?

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Trabajo en NASA
English:  Work at NASA

* ¿Qué es esto? - What is this?
	+ Está trabajando en NASA. - He's working at NASA.
* ¿Qué es un OVNI? - What's a UFO?
	+ No lo sé, pero eso es un OVNI. - I don't know, but that's a UFO.
* ¿Qué hay en la televisión? - What's on TV?
	+ Hay un programa interesante en la televisión. - There's an interesting program on TV.
* ¿Qué anda mal? - What's wrong?
	+ Está andando mal el proyecto. - The project is going wrong.
* ¿Dónde está Tom? - Where is Tom?
	+ No lo sé, pero creo que está en la oficina. - I don't know, but I think he's in the office.
* ¿Quiénes son ellos? - Who are they?
	+ Son los nuevos empleados de NASA. - They are the new employees of NASA.
* ¿Quiénes son? - Who are they?
	+ Son los científicos de la NASA. - They are the NASA scientists.
* ¿Quién lo construyó? - Who built it?
	+ La NASA construyó la estación de prueba. - NASA built the testing station.
* ¿Quién canceló? - Who canceled?
	+ La reunión cancelada debido a la tormenta. - The meeting was canceled due to the storm.
* ¿Quién fue el que hizo la cancelación? - Who canceled?
	+ No lo sé, pero creo que fue el jefe de la oficina. - I don't know, but I think it was the office manager.
* ¿Quién ha hecho esto? - Who did this?
	+ Lo hizo el equipo de investigación de la NASA. - The team did it.
* ¿Quién ha venido? - Who has come?
	+ Hicieron una visita a la NASA. - They visited NASA.
* ¿Quién está ahí? - Who is there?
	+ Hay un equipo de investigación en la oficina. - There's a research team in the office.
* ¿Quién escuchó? - Who listened?
	+ No escuché la respuesta. - I didn't hear the answer.
* ¿Quién te pagó? - Who paid you?
	+ La NASA me pagó por mi trabajo. - NASA paid me for my work.
* ¿Quién entró en pánico? - Who panicked?
	+ No entré en pánico, pero sí me preocupó. - I didn't panic, but I was concerned.
* ¿Quién te paga? - Who pays you?
	+ La NASA me paga un sueldo. - NASA pays me a salary.
* ¿Quién huyó? - Who ran away?
	+ No hice nada de eso, pero sí me escapé. - I didn't do anything like that, but I did escape.
* ¿Quién renunció? - Who resigned?
	+ Renunció el jefe de la oficina. - The office manager resigned.
* ¿Quién te envió? - Who sent you?
	+ La NASA me envió a hacer la prueba. - NASA sent me to take the test.
* ¿Quién sobrevivió? - Who survived?
	+ No sobrevive nadie en la oficina. - No one survived in the office.
* ¿Quién le contó a Tom? - Who told Tom?
	+ No lo sé, pero creo que fue el jefe de la oficina. - I don't know, but I think it was the office manager.
* ¿Quién desapareció? - Who vanished?
	+ Desapareció el equipo de investigación. - The research team disappeared.
* ¿Quién lo quiere? - Who wants it?
	+ La NASA quiere la información. - NASA wants the information.
* ¿Quién era ese? - Who was that?
	+ Era el jefe de la oficina. - It was the office manager.
* ¿Quién va a pagar? - Who will pay?
	+ La NASA va a pagar por la prueba. - NASA will pay for the test.
* ¿Quién luchará? - Who'll fight?
	+ Lucharán los científicos de la NASA. - The scientists will fight.
* ¿Quién empieza? - Who'll start?
	+ Empieza el equipo de investigación. - The research team starts.
* ¿Quién parte? - Who'll start?
	+ Partimos hacia la estación de prueba. - We're going to the testing station.
* Vayamos juntos. - Let's go together.
	+ Vamos a la oficina de la NASA. - Let's go to the NASA office.
* Vayámonos juntos. - Let's go together.
	+ Vamos a la estación de prueba. - Let's go to the testing station.
* Vamos juntos. - Let's go together.
	+ Vamos a la oficina de la NASA. - Let's go to the NASA office.
* Vamos adentro. - Let's go inside.
	+ Vamos a la estación de prueba. - Let's go to the testing station.
* Vamos para adentro. - Let's go inside.
	+ Vamos a la oficina de la NASA. - Let's go to the NASA office.
* Vámonos a la cama. - Let's go to bed.
	+ Vámonos a la estación de prueba. - Let's go to the testing station.
* Improvisemos. - Let's improvise.
	+ Improvisamos la prueba. - We improvise the test.
* Negociemos. - Let's negotiate.
	+ Negociamos el precio de la prueba. - We negotiate the price of the test.
* Visitemos a Tom. - Let's visit Tom.
	+ Visitemos a la oficina de la NASA. - Let's visit the NASA office.
* Esperemos aquí. - Let's wait here.
	+ Esperamos a la estación de prueba. - We wait at the testing station.
* La vida no es fácil. - Life ain't easy.
	+ La vida es complicada. - Life is complicated.
* La vida es un sueño. - Life is a dream.
	+ La vida es un sueño real. - Life is a real dream.
* La vida es extraña. - Life is strange.
	+ La vida es extraña y complicada. - Life is strange and complicated.
* No lo lograremos. - We won't make it.
	+ No logramos la prueba. - We didn't pass the test.
* Trabajamos juntos. - We work together.
	+ Trabajamos en la oficina de la NASA. - We work at the NASA office.
* Escribimos cartas. - We wrote letters.
	+ Escribimos cartas a la oficina de la NASA. - We wrote letters to the NASA office.
* Es mejor que esperemos. - We'd better wait.
	+ Es mejor que esperemos la respuesta. - It's better to wait for the answer.
* Seremos rescatados. - We'll be rescued.
	+ Seremos rescatados de la oficina de la NASA. - We'll be rescued from the NASA office.
* Estaremos esperando. - We'll be waiting.
	+ Estaremos esperando la respuesta. - We'll be waiting for the answer.
* Lo hemos logrado. - We did it.
	+ Lo hemos logrado en la oficina de la NASA. - We did it at the NASA office.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¿Qué te gusta hacer?
English:  I like to do many things. Here are some translations:

* "Me gusta ir de picnic." - I like to go on picnics.
* "Me gusta los rompecabezas." - I like puzzles.
* "Me gusta mucho leer." - I like to read a lot.
* "Me gusta el sashimi." - I like sashimi.
* "Me gustan los mariscos." - I like seafood.
* "Me gusta cantar." - I like to sing.
* "Me gustan las historias." - I like stories.
* "Me gusta hablar." - I like to talk.
* "Me gusta el perro." - I like dogs.
* "Me gusta cocinar." - I like to cook.
* "Me gusta dibujar." - I like to draw.
* "Me gusta la escritura." - I like writing.
* "Vivo en el norte." - I live in the north.
* "Vivo hacia el norte." - I live upstate.
* "Perdí la llave." - I lost the key.
* "Me encanta Harvard." - I love Harvard.
* "Adoro Harvard." - I love Harvard.
* "Amo los animales." - I love animals.
* "Sencillamente me rendí." - I just gave up.
* "Me acabo de encontrar con él." - I just met him.
* "Acabo de gritar." - I just shouted.
* "Acabo de venderlo." - I just sold it.
* "Simplemente lo quiero." - I just want it.
* "Lo quiero ya." - I just want it.
* "Lo quiero y ya está." - I just want it.
* "Mantuve mi palabra." - I kept my word.
* "Lo sé bien." - I know it well.
* "Conozco al chico." - I know the boy.
* "Me gusta el inglés." - I like English.
* "Me gustan los castillos." - I like castles.
* "Me gusta el pollo." - I like chicken.
* "Me gustan las galletas." - I like cookies.
* "Me gusta la pesca." - I like fishing.
* "Me gusta la historia." - I like history.
* "Me gusta planchar." - I like ironing.
* "Me gusta trotar." - I like jogging.
* "Me gusta la lechuga." - I like lettuce.
* "Me gusta el mahjong." - I like mahjong.
* "Me gusta mi vida." - I like my life.
* "Me gusta mi nombre." - I like my name.
* "Me gustan los fideos." - I like noodles.
* "Me gustan los tallarines." - I like noodles.
* "Me gustan las naranjas." - I like oranges.
* "Me gusta este reloj de pulsera." - I like this watch.
* "Me gusta estar aquí." - I like to be here.
* "Me gusta la sandía." - I like watermelon.
* "Me gusta tu caballo." - I like your horse.
* "Me gusta su casa." - I like your house.
* "Me gusta tu casa." - I like your house.
* "Me gustan tus ideas." - I like your ideas.
* "Me gusta tu teléfono." - I like your phone.
* "Me gusta tu bufanda." - I like your scarf.
* "Me gusta tu camisa." - I like your shirt.
* "Me gusta tu estilo." - I like your style.
* "Me gusta tu camión." - I like your truck.
* "Me gusta tu voz." - I like your voice.
* "La película me gustó." - I liked the movie.
* "La película me gustó." - I liked this film.
* "Vivo aquí solo." - I live here alone.
* "Viví en Boston." - I lived in Boston.
* "He bloqueado la puerta." - I locked the door.
* "He trancado la puerta." - I locked the door.
* "Perdí un arete." - I lost an earring.
* "Yo perdí un arete." - I lost an earring.
* "He perdido un arete." - I lost an earring.
* "Yo he perdido un arete." - I lost an earring.
* "Lo he perdido todo." - I lost everything.
* "Lo perdí todo." - I lost everything.
* "Me gusta su música." - I like his music.
* "Me gusta la nieve." - I like ice cream.
* "Me gusta el helado." - I like ice cream.
* "Me gusta la comida basura." - I like junk food.
* "Me gusta la comida chatarra." - I like junk food.
* "Me gustan los idiomas." - I like languages.
* "Lo que más me gusta son las matemáticas." - I like math best.
* "Me gusta la música pop." - I like pop music.
* "Me gustan las rosas rojas." - I like red roses.
* "Me gustan las sorpresas." - I like surprises.
* "Me gusta esa bandera." - I like that flag.
* "Me gusta ese nombre." - I like that name.
* "Me gusta esa canción." - I like that song.
* "Me gusta la playa." - I like the beach.
* "Me gusta este libro." - I like this book.
* "Me gusta esta ciudad." - I like this city.
* "Me gusta este plan." - I like this plan.
* "Me gusta esa canción." - I like that song.
* "Me gusta viajar." - I like to travel.
* "Te quiero mucho." - I like you a lot.
* "Me gustás mucho." - I like you a lot.
* "Me gusta tu ciudad." - I like your city.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Me gusta leer.
English:  I like reading.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Me encanta comer.
English:  Enjoy

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¿Qué haces en tu tiempo libre?
English:  What do you do in your free time?

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¿Cuáles son tus pasatiempos?
English:  He likes.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¿Cuál es tu banda favorita?
English:  Your favorite band?

Me encanta la música de Boston.
I love Boston's music.

Or:

Me gusta la música de France.
I like French music.

Or:

Amo la música de los lunes.
I love Monday's music.

Or:

Me gusta el empleo que tengo.
I love my job.

Or:

Amo a mi papá.
I love my dad.

Or:

Me encanta el ajo.
I love garlic.

Or:

He perdido el reloj.
I lost the watch.

Or:

Adoro los elefantes.
I love elephants.

Or:

Me encanta la astronomía.
I love astronomy.

Or:

Me gusta la jardinería.
I love gardening.

Or:

Me gusta el helado.
I love ice cream.

Or:

Yo amo a mi patria.
I love my country.

Or:

Amo mi país.
I love my country.

Or:

Me gusta la música de mi ciudad.
I love the music of my city.

Or:

Me gusta la comida de mi ciudad.
I love the food of my city.

Or:

Amo a mis amigos.
I love my friends.

Or:

Me encanta la Navidad.
I love Christmas.

Or:

Me gusta la playa.
I love the beach.

Or:

Me gusta el parque.
I love the park.

Or:

Amo a mis padres.
I love my parents.

Or:

Me gusta la televisión.
I love TV.

Or:

Me gusta el cine.
I love movies.

Or:

Amo a mis hermanos.
I love my brothers.

Or:

Me gusta la música clásica.
I love classical music.

Or:

Me gusta la danza.
I love dancing.

Or:

Amo a mis colegas.
I love my colleagues.

Or:

Me gusta la naturaleza.
I love nature.

Or:

Me gusta el arte.
I love art.

Or:

Amo a mis familiares.
I love my family.

Or:

Me gusta la literatura.
I love literature.

Or:

Me gusta la cocina.
I love cooking.

Or:

Amo a mis amigos de la infancia.
I love my childhood friends.

Or:

Me gusta la tecnología.
I love technology.

Or:

Amo a mis colegas de trabajo.
I love my work colleagues.

Or:

Me gusta la música electrónica.
I love electronic music.

Or:

Me gusta el baile.
I love dancing.

Or:

Amo a mis amigos de la universidad.
I love my university friends.

Or:

Me gusta la moda.
I love fashion.

Or:

Amo a mis amigos de la escuela.
I love my school friends.

Or:

Me gusta la música de la generación anterior.
I love the music of the previous generation.

Or:

Amo a mis amigos de la comunidad.
I love my community friends.

Or:

Me gusta la música de la generación posterior.
I love the music of the next generation.

Or:

Amo a mis amigos de la ciudad.
I love my city friends.

Or:

Me gusta la música de la región.
I love the music of the region.

Or:

Amo a mis amigos de la cultura.
I love my cultural friends.

Or:

Me gusta la música de la nación.
I love the music of the nation.

Or:

Amo a mis amigos de la lengua.
I love my linguistic friends.

Or:

Me gusta la música de la tradición.
I love the music of the tradition.

Or:

Amo a mis amigos de la historia.
I love my historical friends.

Or:

Me gusta la música de la innovación.
I love the music of innovation.

Or:

Amo a mis amigos de la creatividad.
I love my creative friends.

Or:

Me gusta la música de la expresión.
I love the music of expression.

Or:

Amo a mis amigos de la emoción.
I love my emotional friends.

Or:

Me gusta la música de la comunicación.
I love the music of communication.

Or:

Amo a mis amigos de la interacción.
I love my interactive friends.

Or:

Me gusta la música de la colaboración.
I love the music of collaboration.

Or:

Amo a mis amigos de la creación.
I love my creative friends.

Or:

Me gusta la música de la inspiración.
I love the music of inspiration.

Or:

Amo a mis amigos de la motivación.
I love my motivational friends.

Or:

Me gusta la música de la felicidad.
I love the music of happiness.

Or:

Amo a mis amigos de la satisfacción.
I love my satisfied friends.

Or:

Me gusta la música de la alegría.
I love the music of joy.

Or:

Amo a mis amigos de la serenidad.
I love my serene friends.

Or:

Me gusta la música de la armonía.
I love the music of harmony.

Or:

Amo a mis amigos de la armonía.
I love my harmonious friends.

Or:

Me gusta la música de la unión.
I love the music of union.

Or:

Amo a mis amigos de la unión.
I love my united friends.

Or:

Me gusta la música de la diversidad.
I love the music of diversity.

Or:

Amo a mis amigos de la diversidad.
I love my diverse friends.

Or:

Me gusta la música de la inclusión.
I love the music of inclusion.

Or:

Amo a mis amigos de la inclusión.
I love my inclusive friends.

Or:

Me gusta la música de la empatía.
I love the music of empathy.

Or:

Amo a mis amigos de la empatía.
I love my empathetic friends.

Or:

Me gusta la música de la comprensión.
I love the music of understanding.

Or:

Amo a mis amigos de la comprensión.
I love my understanding friends.

Or:

Me gusta la música de la comunicación abierta.
I love the music of open communication.

Or:

Amo a mis amigos de la comunicación abierta.
I love my open-communicative friends.

Or:

Me gusta la música de la colaboración activa.
I love the music of active collaboration.

Or:

Amo a mis amigos de la colaboración activa.
I love my active collaborative friends.

Or:

Me gusta la música de la creatividad colectiva.
I love the music of collective creativity.

Or:

Amo a mis amigos de la creatividad colectiva.
I love my collectively creative friends.

Or:

Me gusta la música de la interacción positiva.
I love the music of positive interaction.

Or:

Amo a mis amigos de la interacción positiva.
I love my positive interactive friends.

Or:

Me gusta la música de la felicidad compartida.
I love the music of shared happiness.

Or:

Amo a mis amigos de la felicidad compartida.
I love my shared happy friends.

Or:

Me gusta la música de la satisfacción compartida.
I love the music of shared satisfaction.

Or:

Amo a mis amigos de la satisfacción compartida.
I love my shared satisfied friends.

Or:

Me gusta la música de la armonía colectiva.
I love the music of collective harmony.

Or:

Amo a mis amigos de la armonía colectiva.
I love my collectively harmonious friends.

Or:

Me gusta la música de la unión colectiva.
I love the music of collective union.

Or:

Amo a mis amigos de la unión colectiva.
I love my collectively united friends.

Or:

Me gusta la música de la diversidad colectiva.
I love the music of collective diversity.

Or:

Amo a mis amigos de la diversidad colectiva.
I love my collectively diverse friends.

Or:

Me gusta la música de la inclusión colectiva.
I love the music of collective inclusion.

Or:

Amo a mis amigos de la inclusión colectiva.
I love my collectively inclusive friends.

Or:

Me gusta la música de la empatía colectiva.
I love the music of collective empathy.

Or:

Amo a mis amigos de la empatía colectiva.
I love my collectively empathetic friends.

Or:

Me gusta la música de la comprensión colectiva.
I love the music of collective understanding.

Or:

Amo a mis amigos de la comprensión colectiva.
I love my collectively understanding friends.

Or:

Me gusta la música de la comunicación abierta colectiva.
I love the music of collective open communication.

Or:

Amo a mis amigos de la comunicación abierta colectiva.
I love my collectively open-communicative friends.

Or:

Me gusta la música de la colaboración activa colectiva.
I love the music of collective active collaboration.

Or:

Amo a mis amigos de la colaboración activa colectiva.
I love my collectively active collaborative friends.

Or:

Me gusta la música de la creatividad colectiva.
I love the music of collective creativity.

Or:

Amo a mis amigos de la creatividad colectiva.
I love my collectively creative friends.

Or:

Me gusta la música de la felicidad compartida.
I love the music of shared happiness.

Or:

Amo a mis amigos de la felicidad compartida.
I love my shared happy friends.

Or:

Me gusta la música de la satisfacción compartida.
I love the music of shared satisfaction.

Or:

Amo a mis amigos de la satisfacción compartida.
I love my shared satisfied friends.

Or:

Me gusta la música de la armonía colectiva.
I love the music of collective harmony.

Or:

Amo a mis amigos de la armonía colectiva.
I love my collectively harmonious friends.

Or:

Me gusta la música de la unión colectiva.
I love the music of collective union.

Or:

Amo a mis amigos de la unión colectiva.
I love my collectively united friends.

Or:

Me gusta la música de la diversidad colectiva.
I love the music of collective diversity.

Or:

Amo a mis amigos de la diversidad colectiva.
I love my collectively diverse friends.

Or:

Me gusta la música de la inclusión colectiva.
I love the music of collective inclusion.

Or:

Amo a mis amigos de la inclusión colectiva.
I love my collectively inclusive friends.

Or:

Me gusta la música de la empatía colectiva.
I love the music of collective empathy.

Or:

Amo a mis amigos de la empatía colectiva.
I love my collectively empathetic friends.

Or:

Me gusta la música de la comprensión colectiva.
I love the music of collective understanding.

Or:

Amo a mis amigos de la comprensión colectiva.
I love my collectively understanding friends.

Or:

Me gusta la música de la colaboración activa.
I love the music of active collaboration.

Or:

Amo a mis amigos de la colaboración activa.
I love my actively collaborative friends.

Or:

Me gusta la música de la creatividad colectiva.
I love the music of collective creativity.

Or:

Amo a mis amigos de la creatividad colectiva.
I love my collectively creative friends.

Or:

Me gusta la música de la felicidad compartida.
I love the music of shared happiness.

Or:

Amo a mis amigos de la felicidad compartida.
I love my shared happy friends.

Or:

Me gusta la música de la satisfacción compartida.
I love the music of shared satisfaction.

Or:

Amo a mis amigos de la satisfacción compartida.
I love my shared satisfied friends.

Or:

Me gusta la música de la armonía colectiva.
I love the music of collective harmony.

Or:

Amo a mis amigos de la armonía colectiva.
I love my collectively harmonious friends.

Or:

Me gusta la música de la unión colectiva.
I love the music of collective union.

Or:

Amo a mis amigos de la unión colectiva.
I love my collectively united friends.

Or:

Me gusta la música de la creatividad colectiva.
I love the music of collective creativity.

Or:

Amo a mis amigos de la creatividad colectiva.
I love my collectively creative friends.

Or:

Me gusta la música de la felicidad compartida.
I love the music of shared happiness.

Or:

Amo a mis amigos de la felicidad compartida.
I love my shared happy friends.

Or:

Me gusta la música de la satisfacción compartida.
I love the music of shared satisfaction.

Or:

Amo a mis amigos de la satisfacción compartida.
I love my shared satisfied friends.

Or:

Me gusta la música de la unión colectiva.
I love the music of collective union.

Or:

Amo a mis amigos de la unión colectiva.
I love my collectively united friends.

Or:

Me gusta la música de la creatividad colectiva.
I love the music of collective creativity.

Or:

Amo a mis amigos de la creatividad colectiva.
I love my collectively creative friends.

Or:

Me gusta la música de la felicidad compartida.
I love the music of shared happiness.

Or:

Amo a mis amigos de la felicidad compartida.
I love my shared happy friends.

Or:

Me gusta la música de la satisfacción compartida.
I love the music of shared satisfaction.

Or:

Amo a mis amigos de la satisfacción compartida.
I love my shared satisfied friends.

Or:

Me gusta la música de la armonía colectiva.
I love the music of collective harmony.

Or:

Amo a mis amigos de la armonía colectiva.
I love my collectively harmonious friends.

Or:

Me gusta la música de la unión colectiva.
I love the music of collective union.

Or:

Amo a mis amigos de la unión colectiva.
I love my collectively united friends.

Or:

Me gusta la música de la creatividad colectiva.
I love the music of collective creativity.

Or:

Amo a mis amigos de la creatividad colectiva.
I love my collectively creative friends.

Or:

Me gusta la música de la felicidad compartida.
I love the music of shared happiness.

Or:

Amo a mis amigos de la felicidad compartida.
I love my shared happy friends.

Or:

Me gusta la música de la satisfacción compartida.
I love the music of shared satisfaction.

Or:

Amo a mis amigos de la satisfacción compartida.
I love my shared satisfied friends.

Or:

Me gusta la música de la unión colectiva.
I love the music of collective union.

Or:

Amo a mis amigos de la unión colectiva.
I love my collectively united friends.

Or:

Me gusta la música de la creatividad colectiva.
I love the music of collective creativity.

Or:

Amo a mis amigos de la creatividad colectiva.
I love my collectively creative friends.

Or:

Me gusta la música de la felicidad compartida.
I love the music of shared happiness.

Or:

Amo a mis amigos de la felicidad compartida.
I love my shared happy friends.

Or:

Me gusta la música de la satisfacción compartida.
I love the music of shared satisfaction.

Or:

Amo a mis amigos de la satisfacción compartida.
I love my shared satisfied friends.

Or:

Me gusta la música de la unión colectiva.
I love the music of collective union.

Or:

Amo a mis amigos de la unión colectiva.
I love my collectively united friends.

Or:

Me gusta la música de la creatividad colectiva.
I love the music of collective creativity.

Or:

Amo a mis amigos de la creatividad colectiva.
I love my collectively creative friends.

Or:

Me gusta la música de la felicidad compartida.
I love the music of shared happiness.

Or:

Amo a mis amigos de la felicidad compartida.
I love my shared happy friends.

Or:

Me gusta la música de la satisfacción compartida.
I love the music of shared satisfaction.

Or:

Amo a mis amigos de la satisfacción compartida.
I love my shared satisfied friends.

Or:

Me gusta la música de la unión colectiva.
I love the music of collective union.

Or:

Amo a mis amigos de la unión colectiva.
I love my collectively united friends.

Or:

Me gusta la música de la creatividad colectiva.
I love the music of collective creativity.

Or:

Amo a mis amigos de la creatividad colectiva.
I love my collectively creative friends.

Or:

Me gusta la música de la felicidad compartida.
I love the music of shared happiness.

Or:

Amo a mis amigos de la felicidad compartida.
I love my shared happy friends.

Or:

Me gusta la música de la satisfacción compartida.
I love the music of shared satisfaction.

Or:

Amo a mis amigos de la satisfacción compartida.
I love my shared satisfied friends.

Or:

Me gusta la música de la unión colectiva.
I love the music of collective union.

Or:

Amo a mis amigos de la unión colectiva.
I love my collectively united friends.

Or:

Me gusta la música de la creatividad colectiva.
I love the music of collective creativity.

Or:

Amo a mis amigos de la creatividad colectiva.
I love my collectively creative friends.

Or:

Me gusta la música de la felicidad compartida.
I love the music of shared happiness.

Or:

Amo a mis amigos de la felicidad compartida.
I love my shared happy friends.

Or:

Me gusta la música de la satisfacción compartida.
I love the music of shared satisfaction.

Or:

Amo a mis amigos de la satisfacción compartida.
I love my shared satisfied friends.

Or:

Me gusta la música de la unión colectiva.
I love the music of collective union.

Or:

Amo a mis amigos de la unión colectiva.
I love my collectively united friends.

Or:

Me gusta la música de la creatividad colectiva.
I love the music of collective creativity.

Or:

Amo a mis amigos de la creatividad colectiva.
I love my collectively creative friends.

Or:

Me gusta la música de la felicidad compartida.
I love the music of shared happiness.

Or:

Amo a mis amigos de la felicidad compartida.
I love my shared happy friends.

Or:

Me gusta la música de la satisfacción compartida.
I love the music of shared satisfaction.

Or:

Amo a mis amigos de la satisfacción compartida.
I love my shared satisfied friends.

Or:

Me gusta la música de la unión colectiva.
I love the music of collective union.

Or:

Amo a mis amigos de la unión colectiva.
I love my collectively united friends.

Or:

Me gusta la música de la creatividad colectiva.
I love the music of collective creativity.

Or:

Amo a mis amigos de la creatividad colectiva.
I love my collectively creative friends.

Or:

Me gusta la música de la felicidad compartida.
I love the music of shared happiness.

Or:

Amo a mis amigos de la felicidad compartida.
I love my shared happy friends.

Or:

Me gusta la música de la satisfacción compartida.
I love the music of shared satisfaction.

Or:

Amo a mis amigos de la satisfacción compartida.
I love my shared satisfied friends.

Or:

Me gusta la música de la unión colectiva.
I love the music of collective union.

Or:

Amo a mis amigos de la unión colectiva.
I love my collectively united friends.

Or:

Me gusta la música de la creatividad colectiva.
I love the music of collective creativity.

Or:

Amo a mis amigos de la creatividad colectiva.
I love my collectively creative friends.

Or:

Me gusta la música de la felicidad compartida.
I love the music of shared happiness.

Or:

Amo a mis amigos de la felicidad compartida.
I love my shared happy friends.

Or:

Me gusta la música de la satisfacción compartida.
I love the music of shared satisfaction.

Or:

Amo a mis amigos de la satisfacción compartida.
I love my shared satisfied friends.

Or:

Me gusta la música de la unión colectiva.
I love the music of collective union.

Or:

Amo a mis amigos de la unión colectiva.
I love my collectively united friends.

Or:

Me gusta la música de la creatividad colectiva.
I love the music of collective creativity.

Or:

Amo a mis amigos de la creatividad colectiva.
I love my collectively creative friends.

Or:

Me gusta la música de la felicidad compartida.
I love the music of shared happiness.

Or:

Amo a mis amigos de la felicidad compartida.
I love my shared happy friends.

Or:

Me gusta la música de la satisfacción compartida.
I love the music of shared satisfaction.

Or:

Amo a mis amigos de la satisfacción compartida.
I love my shared satisfied friends.

Or:

Me gusta la música de la unión colectiva.
I love the music of collective union.

Or:

Amo a mis amigos de la unión colectiva.
I love my collectively united friends.

Or:

Me gusta la música de la creatividad colectiva.
I love the music of collective creativity.

Or:

Amo a mis amigos de la creatividad colectiva.
I love my collectively creative friends.

Or:

Me gusta la música de la felicidad compartida.
I love the music of shared happiness.

Or:

Amo a mis amigos de la felicidad compartida.
I love my shared happy friends.

Or:

Me gusta la música de la satisfacción compartida.
I love the music of shared satisfaction.

Or:

Amo a mis amigos de la satisfacción compartida.
I love my shared satisfied friends.

Or:

Me gusta la música de la unión colectiva.
I love the music of collective union.

Or:

Amo a mis amigos de la unión colectiva.
I love my collectively united friends.

Or:

Me gusta la música de la creatividad colectiva.
I love the music of collective creativity.

Or:

Amo a mis amigos de la creatividad colectiva.
I love my collectively creative friends.

Or:

Me gusta la música de la felicidad compartida.
I love the music of shared happiness.

Or:

Amo a mis amigos de la felicidad compartida.
I love my shared happy friends.

Or:

Me gusta la música de la satisfacción compartida.
I love the music of shared satisfaction.

Or:

Amo a mis amigos de la satisfacción compartida.
I love my shared satisfied friends.

Or:

Me gusta la música de la unión colectiva.
I love the music of collective union.

Or:

Amo a mis amigos de la unión colectiva.
I love my collectively united friends.

Or:

Me gusta la música de la creatividad colectiva.
I love the music of collective creativity.

Or:

Amo a mis amigos de la creatividad colectiva.
I love my collectively creative friends.

Or:

Me gusta la música de la felicidad compartida.
I love the music of shared happiness.

Or:

Amo a mis amigos de la felicidad compartida.
I love my shared happy friends.

Or:

Me gusta la música de la satisfacción compartida.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Mi (libro, película, banda) favorito(a) es…
English:  My (book, movie, band) favorite is...

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¿Qué haces aquí?
English:  What are you doing here?

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¿Quién eres?
English:  You are:

* Él (he)
* Ella (she)
* Él/ella (he/she)
* Los (they)
* Nosotros (we)
* Vosotros (you all)
* Él/ella/usted (he/she/you)

Example sentences:

* Él es médico. (He is a doctor.)
* Ella es abogada. (She is a lawyer.)
* Él es un genio. (He is a genius.)
* Vosotros sois amigos. (You are friends.)
* Nosotros vamos al cine. (We are going to the movies.)
* Él es japonés. (He is Japanese.)
* Ella es alta. (She is tall.)
* Él es un sin techo. (He is homeless.)
* Vosotros habláis español. (You speak Spanish.)

Note: Some of the sentences may have multiple translations depending on the context and the level of formality desired.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¿Cuánto cuesta?
English:  "It costs"

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¿Dónde está el baño?
English:  The translation of "¿Dónde está el baño?" is:

Where is the bathroom?

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¿Quieres tomar algo?
English:  Sure! Here is the translation of "¿Quieres tomar algo?" in English:

Do you want to take something?

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¿Qué hora es?
English:  What time is it?

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¿Qué día es hoy?
English:  English translation: What day is it today?

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¿Habla inglés?
English:  Sure! Here is the translation of the text you provided:

"Do you speak English?"

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¿Puedo pasar?
English:  Sure! Here's the translation of "¿Puedo pasar?" in English:

Can I go through?

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¿Pasa algo malo?
English:  "Something's wrong."

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¡Feliz cumpleaños!
English:  Happy birthday!

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¡Feliz navidad!
English:  Happy Christmas!

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¡Feliz año nuevo!
English:  Happy New Year!

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¡Felicidades!
English:  Congratulations!

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¡Enhorabuena!
English:  Congratulations!

Here are the translations for the given phrases:

* ¡Enhorabuena! - Congratulations!
* Me escapó - I escaped.
* Yo lo sé - I know.
* Sé - I know.
* Salí - I left.
* Mentí - I lied.
* Perdí - I lost.
* Pagué - I paid.
* Dimito - I quit.
* Renuncié - I quit.
* Lo dejo - I quit.
* Canté - I sang.
* Lloré - I wept.
* Lloraba - I wept.
* Estoy trabajando - I'm working.
* Tengo diecinueve - I'm 19.
* Estoy levantado - I'm up.
* Inhalar - Inhale.
* Inspira - Inhale.
* Inspirad - Inhale.
* Inspire - Inhale.
* Inspiren - Inhale.
* Escucha - Listen.
* Escuche - Listen.
* Escuchen - Listen.
* ¡No puede ser! - No way!
* De ninguna manera - No way!
* ¡De ninguna manera! - No way!
* ¡Imposible! - No way!
* ¡De ningún modo! - No way!
* ¡De eso nada! - No way!
* ¡Ni cagando! - No way!
* ¡Mangos! - No way!
* ¡Minga! - No way!
* ¡Ni en pedo! - No way!
* ¿En serio? - Really?
* ¿La verdad? - Really?
* ¡Gracias! - Thanks!
* ¡Gracias! - Thanks.
* Gracias. - Thanks.
* Pruébalo. - Try it.
* A que sí, ya verás. - Try me.
* Comimos. - We ate.
* Lo procuramos. - We try.
* Ganamos. - We won.
* ¿Por qué yo? - Why me?
* Pregúntale a Tom. - Ask Tom.
* Pregúntale. - Ask him.
* ¡Órale! - Awesome!
* Mantente en calma. - Be calm.
* Estate tranquilo. - Be cool.
* ¡No esperes! - Don't wait.
* ¡No esperen! - Don't wait.
* No esperes. - Don't wait.
* No grites. - Don't yell.
* No chilles. - Don't yell.
* No chilléis. - Don't yell.
* No chille. - Don't yell.
* No chillen. - Don't yell.
* Come despacio. - Eat slowly.
* ¡Comé despacio! - Eat slowly.
* Disfruta la vida. - Enjoy life.
* ¡Enfréntate a los hechos! - Face facts!
* ¡Enfrentaos a los hechos! - Face facts!
* ¡Enfréntese a los hechos! - Face facts!
* ¡Enfréntense a los hechos! - Face facts!
* El fuego quema. - Fire burns.
* Seguilo a Tomás. - Follow Tom.
* Sígalo a Tomás. - Follow Tom.
* Sígalo a Tomás. - Follow Tom.
* Síganlo a Tomás. - Follow Tom.
* Síguele. - Follow him.
* Síguelo. - Follow him.
* Olvidate de Tomás. - Forget Tom.
* Olvídate de Tomás. - Forget Tom.
* Olvídenlo. - Forget him.
* Perdónanos. - Forgive us.
* Perdónenos. - Forgive us.
* Consíguete una vida. - Get a life.
* Búscate una vida. - Get a life.
* Entra. - Get inside.
* Vete a la cama. - Go to bed.
* Déjalo. - Give it up.
* Ríndanse. - Give it up.
* Vete a casa. - Go home.
* Váyase a casa. - Go home.
* Hemos concluido. - We're through.
* ¡Estamos atrapados! - We're trapped!
* Estamos atrapados. - We're trapped.
* No tenemos suerte. - We're unlucky.
* Somos unos inútiles. - We're useless.
* Somos unas inútiles. - We're useless.
* Estamos ganando. - We're winning.
* Estamos trabajando. - We're working.
* Hemos llegado. - We've arrived.
* Llegamos. - We've arrived.
* Lo hemos hecho. - We've done it.
* ¿Estabas ocupado? - Were you busy?
* ¿Estabas ocupada? - Were you busy?
* ¿Estabais en casa? - Were you home?
* ¿Estabas en casa? - Were you home?
* ¿Te dispararon? - Were you shot?
* ¿Estabas enfermo? - Were you sick?
* ¡Qué fiasco! - What a fiasco!
* ¡Qué rollo! - What a hassle!
* ¡Qué lío! - What a hassle!
* ¡Menudo jaleo! - What a hassle!
* ¡Menudo lío! - What a hassle!
* ¡Vaya rollo! - What a hassle!
* ¡Qué alivio! - What a relief!
* ¡Qué tipo tan extraño! - What a weirdo!
* ¿Qué pasa conmigo? - What about me?
* ¿Qué hay de mí? - What about me?
* ¿Qué hay de lo mío? - What about me?
* ¿Qué hay de nosotros? - What about us?
* ¿Qué te aflige? - What ails you?
* Es inocente. - She's innocent.
* Ella no está aquí. - She's not here.
* No está aquí. - She's not here.
* Ella está embarazada. - She's pregnant.
* Ella es cabezota. - She's stubborn.
* Ella es testaruda. - She's stubborn.
* ¿Debería cerrar? - Should I close?
* ¿Paramos? - Should we stop?
* ¡Cierra la boca! - Shut your trap!
* ¡Ciérrala! - Shut your trap!
* ¡Para de hablar! - Shut your trap!
* ¡Cállate el pico! - Shut your trap!

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¡Salud!
English:  Here are the translations of the Spanish phrases you provided:

* ¡Salud! - Cheerio!
* Nos gusta conversar. - We like to talk.
* Nos encanta esta zona. - We love it here.
* Nos encanta estar aquí. - We love it here.
* Nos encantan los picnics. - We love picnics.
* Nos encanta ayudar. - We love to help.
* Le hicimos llorar. - We made him cry.
* Hicimos waffles. - We made waffles.
* Hicimos gofres. - We made waffles.
* Conocimos un escritor. - We met a writer.
* Debemos ver a Tom. - We must see Tom.
* Deberíamos ganar. - We ought to win.
* Le pagamos bien a Tom. - We pay Tom well.
* Castigamos a Tom. - We punished Tom.
* Nos acordamos de Tom. - We remember Tom.
* Los respetamos. - We respect them.
* Las respetamos. - We respect them.
* Nosotros cantamos para ella. - We sang for her.
* Compartimos ideas. - We shared ideas.
* Deberíamos irnos. - We should leave.
* Hablamos francés. - We speak French.
* Estudiamos francés. - We study French.
* Anduvimos mucho. - We walked a lot.
* Lo queremos de vuelta. - We want it back.
* Queremos justicia. - We want justice.
* Queremos ayudar. - We want to help.
* ¡No esperes! - Don't wait!
* ¡No esperen! - Don't wait!
* No esperes. - Don't wait!
* No grites. - Don't yell!
* No chilles. - Don't yell!
* No chilléis. - Don't yell!
* No chille. - Don't yell!
* No chillen. - Don't yell!
* Come despacio. - Eat slowly!
* ¡Comé despacio! - Eat slowly!
* Disfruta la vida. - Enjoy life!
* ¡Enfréntate a los hechos! - Face facts!
* ¡Enfrentaos a los hechos! - Face facts!
* ¡Enfréntese a los hechos! - Face facts!
* ¡Enfréntense a los hechos! - Face facts!
* El fuego quema. - Fire burns!
* Seguilo a Tomás. - Follow Tom!
* Sígalo a Tomás. - Follow Tom!
* Sígalo a Tomás. - Follow Tom!
* Síguele. - Follow him!
* Sígalo. - Follow him!
* Olvidate de Tomás. - Forget Tom!
* Olvídate de Tomás. - Forget Tom!
* Olvídenlo. - Forget him!
* Perdónanos. - Forgive us!
* Perdónenos. - Forgive us!
* Consíguete una vida. - Get a life!
* Búscate una vida. - Get a life!
* Entra. - Get inside!
* Vete a la cama. - Go on home!
* Déjalo. - Give it up!
* Ríndanse. - Give it up!
* Vete a casa. - Go on home!
* ¡Todos a bordo! - All aboard!
* ¡Al abordaje! - All aboard!
* ¿Me estoy muriendo? - Am I dying?
* ¿Estoy despedido? - Am I fired?
* ¿Estoy contratado? - Am I hired?
* ¿Estoy listo? - Am I ready?
* ¿Tengo razón? - Am I right?
* ¿Me equivoco? - Am I wrong?
* ¿Estoy equivocado? - Am I wrong?
* ¡Respóndale a Tomás! - Answer Tom!
* ¡Respondele a Tomás! - Answer Tom!
* ¡Respóndanle a Tomás! - Answer Tom!
* ¿Tienes dieciocho? - Are you 18?
* ¿Has cumplido dieciocho? - Are you 18?
* ¿Estás bien? - Are you OK?
* ¿Te apuntas? - Are you in?
* ¿Estás dentro? - Are you in?
* ¿Estás levantado? - Are you up?
* Pregúntale a cualquiera. - Ask anyone!
* Preguntadle a cualquiera. - Ask anyone!
* Pregúntele a cualquiera. - Ask anyone!
* Pregúntenle a cualquiera. - Ask anyone!
* ¡Ten cuidado! - Be careful!
* ¡Ten cuidado! - Be careful!
* ¡Sé cuidadoso! - Be careful!
* Estamos contentos. - We're content!
* Llega a tiempo. - Be on time!
* Llegue a tiempo. - Be on time!
* Sea paciente. - Be patient!
* Estamos muertos de hambre. - We're famished!
* Somos ingenuos. - We're gullible!
* Estamos sin esperanza. - We're hopeless!
* Estamos involucradas. - We're involved!
* Estamos involucrados. - We're involved!
* No somos pobres. - We're not poor!
* No somos ricos. - We're not rich!
* No estamos seguros. - We're not sure!
* Estamos de vacaciones. - We're on leave!
* Somos pacientes. - We're patients!
* Somos confiables. - We're reliable!
* Somos inquietos. - We're restless!
* Ahora estamos a salvo. - We're safe now!
* Somos tan felices. - We're so happy!
* Estamos tan felices. - We're so happy!
* Nos morimos de hambre. - We're starving!
* Estamos colgados. - We're stranded!
* Somos profesoras. - We're teachers!
* Somos los mejores. - We're the best!
* Somos minuciosos. - We're thorough!
* Nos levantamos temprano. - We're up early!
* Estamos muy tristes. - We're very sad!
* Estamos observando. - We're watching!
* Estamos mirando. - We're watching!
* Observamos. - We're watching!
* Miramos. - We're watching!
* Estamos con vos. - We're with you!

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¡Bienvenida!
English:  Hello! Here are the translations for the phrases you provided:

* Pásala bien: Have a good time!
* Pásenla bien: Have a good time!
* ¡Buen viaje!: Have a nice trip!
* ¡Ten un buen viaje!: Have a nice trip!
* ¡Que tengáis un buen viaje!: Have a nice trip!
* Sírvase otra copa: Have another cup.
* Sírvete otra copa: Have another cup.
* Sírvanse otra copa: Have another cup.
* Toma un poco de ponche: Have some eggnog.
* Bebe un poco de ponche: Have some eggnog.
* ¿Te decidiste? Have you decided?
* ¿Lo has visto? Have you seen it?
* Él se hizo famoso: He became famous.
* Él empezó a correr: He began running.
* Él empezó a cantar: He began to sing.
* Él se portó mal: He behaved badly.
* Él arruinó el trato: He blew the deal.
* Infringió la ley: He broke the law.
* Él me llamó gordo: He called me fat.
* Él sabe leer bien: He can read well.
* Él puede leer lo suficiente: He can read well.
* Él sabe nadar bien: He can swim well.
* Él puede nadar bien: He can swim well.
* Él no puede leerlo: He can't read it.
* Él no sabe silbar: He can't whistle.
* Fui engañado por él: He cheated on me.
* ¡Vota por mí!: Vote for me!
* Esperame: Wait for me.
* Espera por mí: Wait for me.
* Esperad por mí: Wait for me.
* Espérame: Wait for me.
* Espera por nosotros: Wait for us.
* Espéranos: Wait for us.
* Descendió a las dos y media: We left at 2:30.
* Nos gusta conversar: We like to talk.
* Nos encanta esta zona: We love it here.
* Nos encanta estar aquí: We love it here.
* Nos encantan los picnics: We love picnics.
* Nos encanta ayudar: We love to help.
* Le hicimos llorar: We made him cry.
* Hicimos waffles: We made waffles.
* Hicimos gofres: We made waffles.
* Conocimos un escritor: We met a writer.
* Debemos ver a Tom: We must see Tom.
* Deberíamos ganar: We ought to win.
* Le pagamos bien a Tom: We pay Tom well.
* Castigamos a Tom: We punished Tom.
* Nos acordamos de Tom: We remember Tom.
* Los respetamos: We respect them.
* Las respetamos: We respect them.
* Nosotros cantamos para ella: We sang for her.
* Compartimos ideas: We shared ideas.
* Deberíamos irnos: We should leave.
* Hablamos francés: We speak French.
* Estudiamos francés: We study French.
* Anduvimos mucho: We walked a lot.
* Lo hice bien: I've done OK.
* Lo he perdido: I've lost it.
* Lo he visto: I've seen it.
* El hielo es sólido: Ice is solid.
* El hierro es duro: Iron is hard.
* ¿Está bien el lunes?: Is Monday OK?
* ¿Está Tom despierto?: Is Tom awake?
* ¿Tom está loco?: Is Tom crazy?
* ¿Está Tom curado?: Is Tom cured?
* ¿Tom está borracho?: Is Tom drunk?
* ¿Se está muriendo Tom?: Is Tom dying?
* ¿Tom es feliz?: Is Tom happy?
* ¿Tom es lúcido?: Is Tom lucid?
* ¿Tom está mintiendo?: Is Tom lying?
* ¿Tom está preparado?: Is Tom ready?
* ¿Tom tiene razón?: Is Tom right?
* ¿Está ahí Tom?: Is Tom there?
* ¿Eso es un ciervo?: Is it a deer?
* ¿Acaso es una trampa?: Is it a trap?
* ¿Acaso es un lobo?: Is it a wolf?
* ¿Es un lobo?: Is it a wolf?
* ¿Eso es un alce?: Is it an elk?
* ¿Está roto?: Is it broken?
* ¿Es cáncer?: Is it cancer?
* ¿Es suficiente?: Is it enough?
* ¿Eso es amor?: Is that love?
* ¿Es mío ése?: Is that mine?
* ¿Es ése el mío?: Is that mine?
* ¿Eso es nuestro?: Is that ours?
* ¿Eso es nieve?: Is it snow?
* ¿Es verdad?: Is it true?

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¡Buen viaje!
English:  Have a nice trip!

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¡Cuánto tiempo sin verte!
English:  How are you?

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¡Bien hecho!
English:  Good job!

The provided text is a mix of formal and informal language, as well as different registers and styles. Here's my translation of the text:

* "Él es inteligente" = He's smart
* "Ve al sur" = Head south
* "¡Hola, Tom! ¡Helo aquí!" = Hello, Tom! Here he is!
* "¡Aquí está!" = Here it is!
* "¡Rápido, a casa!" = Hurry home!
* "Lo admito" = I admit it
* "Soy un niño" = I am a boy
* "Soy un hombre" = I am a man
* "Soy una persona" = I am a person
* "¡Soy feliz!" = I am happy!
* "Estoy listo" = I am ready!
* "Comí arroz" = I ate rice
* "Lo hice bien" = I've done OK!
* "Lo he perdido" = I've lost it!
* "Lo he visto" = I've seen it!
* "El hielo es sólido" = Ice is solid!
* "El hierro es duro" = Iron is hard!
* "¿Está bien el lunes?" = Is Monday OK?
* "¿Tom está despierto?" = Is Tom awake?
* "¿Tom está loco?" = Is Tom crazy?
* "¿Tom está curado?" = Is Tom cured?
* "¿Tom está borracho?" = Is Tom drunk?
* "¿Se está muriendo Tom?" = Is Tom dying?
* "¿Tom es feliz?" = Is Tom happy?
* "¿Tom es lúcido?" = Is Tom lucid?
* "¿Tom está mintiendo?" = Is Tom lying?
* "¿Tom está preparado?" = Is Tom ready?
* "¿Tom tiene razón?" = Is Tom right?
* "¿Está ahí Tom?" = Is Tom there?
* "¿Eso es un ciervo?" = Is it a deer?
* "¿Acaso es una trampa?" = Is it a trap?
* "¿Acaso es un lobo?" = Is it a wolf?
* "¿Es un lobo?" = Is it a wolf?
* "¿Eso es un alce?" = Is it an elk?
* "¿Está roto?" = Is it broken?
* "¿Es cáncer?" = Is it cancer?
* "¿Es suficiente?" = Is it enough?
* "¿Eso es amor?" = Is it love?
* "¿Es mío ése?" = Is that mine?
* "¿Es ése el mío?" = Is that mine?
* "¿Eso es nuestro?" = Is that ours?
* "¿Eso es nieve?" = Is it snow?
* "¿Es verdad?" = Is it true?
* "¿Será eso verdad?" = Is that true?
* "Pásala bien" = Have a nice time!
* "Pásenla bien" = Have a nice time!
* "¡Buen viaje!" = Have a nice trip!
* "¡Ten un buen viaje!" = Have a nice trip!
* "¡Que tengáis un buen viaje!" = Have a nice trip!
* "Sírvase otra copa" = Have another cup!
* "Sírvete otra copa" = Have another cup!
* "Sírvanse otra copa" = Have another cup!
* "Toma un poco de ponche" = Have some eggnog!
* "Bebe un poco de ponche" = Have some eggnog!
* "¿Te decidiste?" = Have you decided?
* "¿Lo has visto?" = Have you seen it?
* "Él se hizo famoso" = He became famous!
* "Él empezó a correr" = He began running!
* "Él empezó a cantar" = He began to sing!
* "Él se portó mal" = He behaved badly!
* "Él arruinó el trato" = He blew the deal!
* "Infringió la ley" = He broke the law!
* "Él me llamó gordo" = He called me fat!
* "Él sabe leer bien" = He can read well!
* "Él puede leer lo suficientemente" = He can read well enough!
* "Él sabe nadar bien" = He can swim well!
* "Él puede nadar bien" = He can swim well!
* "Él no puede leerlo" = He can't read it!
* "Él no sabe silbar" = He can't whistle!
* "Fui engañado por él" = He cheated on me!
* "Duerme algo" = Get some sleep!
* "Acostúmbrate" = Get used to it!
* "Dale una jalada" = Give it a pull!
* "Dáselo a ella" = Give it to her!
* "Dáselo" = Give it to her!
* "Dáselo a él" = Give it to him!
* "Dáselo" = Give it to him!
* "Démelo" = Give it to him!
* "Dame una pista" = Give me a hint!
* "Dame un beso" = Give me a kiss!
* "¡Dame un beso!" = Give me a kiss!
* "Dame mi bolsa" = Give me my bag!
* "Dame mi cartera" = Give me my bag!
* "Ayúdanos" = Give us a hand!
* "Vuelve a la cama" = Go back to bed!
* "Andá a cambiarte" = Go get changed!
* "Ve a cambiarte" = Go get changed!
* "Que Dios me perdone" = God forgive me!
* "El golf es aburrido" = Golf is boring!
* "Buenas tardes" = Good afternoon!
* "Buena suerte, Tom" = Good luck, Tom!
* "Buen trabajo, Tom" = Good work, Tom!
* "Buenas noches, Tom" = Goodnight, Tom!
* "Adivina quién soy" = Guess who I am!
* "Tráeme mi taza" = Hand me my mug!
* "¡Feliz año!": Happy New Year!
* "Feliz año nuevo" = Happy New Year!
* "Felices vacaciones" = Happy holidays!
* "Felices fiestas" = Happy holidays!
* "¿Llegó?" = Has it arrived?
* "¿Ha llegado?" = Has it arrived?
* "¿Han ido?" = Have they gone?

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¡Diviértete!
English:  * Raise your hands - Levanten sus manos
* Read it and weep - Léelo y llora
* Read the article - Lee el artículo
* Red wine, please - Vino tinto, por favor
* Respect yourself - Respétate a ti mismo
* Revenge is sweet - La venganza es dulce
* Rome is in Italy - Roma queda en Italia / Roma está en Italia
* Save your breath - Ahórrate la saliva / Ahórrate la palabrería / No vale la pena hablar
* Say your prayers - Di tus oraciones
* School is boring - El colegio es aburrido
* See for yourself - Véalo usted mismo / Te veo en el almuerzo / Los veo en el almuerzo
* Don't cheat - ¡No copiéis! / ¡No lo hagas! / ¡No lo haga! / ¡No lo hagan!
* Don't fight - ¡No peleéis! / ¡No peleen! / ¡No pelees! / ¡No peleen!
* Don't go in - ¡No entres! / ¡No entre usted! / ¡No te rías!
* Don't laugh - ¡No sonrías! / ¡No sonrían! / ¡No sonrías! / ¡No sonrían!
* Don't smoke - ¡No fumes! / ¡No fuméis! / ¡No fumas! / ¡No fuman!
* Don't speak - ¡No hables! / ¡No te preocupes! / ¡No os preocupéis! / ¡No se preocupen!
* Finish this - Termine esto
* Flip a coin - Lanza una moneda
* Forgive Tom - Disculpe a Tom
* She's a fox - ¡Es una zorra! / ¡Ella es una zorra! / ¡She's a fox!
* Should I go? - ¿Debería ir?
* Show me how - Muméstrame cómo
* Sleep tight - Que duermas bien
* Speak to me - ¡Háblame!
* Stand aside - ¡A un lado! / ¡Dejad sitio! / ¡Vuelva a empezar!
* Start again - Empieza de nuevo / Empieza otra vez / Empieza otra vez / Empieza de nuevo
* Stay inside - ¡Quédate adentro! / ¡Quédense adentro! / ¡Sigue adentro! / ¡Sigue adentro!
* Stay strong - Mantente fuerte / ¡Sigue haciéndolo! / ¡No te rindas! / ¡No te rendas!
* Step inside - Pase / Entra / ¡Sigue haciéndolo! / ¡No te muevas!
* Do it quickly - ¡Hágalo rápido!
* Do it with me - ¡Hazlo conmigo!
* Do the dishes - Lava los platos
* Does it sting? - ¿Pica?
* Does this fit? - ¿Esto viene bien? / ¿Esta viene bien? / ¿Este viene bien? / ¿Este viene bien?
* Don't be evil - ¡No seas malo! / ¡No seas mala! / ¡No seáis malos! / ¡No seáis malas!
* Don't be late - ¡No llegues tarde! / ¡No lleguéis tarde! / ¡No llegue tarde! / ¡No lleguen tarde!
* Don't be mean - ¡No seas tacaño! / ¡No seas grosero! / ¡No seas descortés! / ¡No seas descortés!
* Don't call me - ¡No me llames! / ¡No me llamés! / ¡No me llaméis! / ¡No me llame!
* Don't come in - ¡No entrar! / ¡No entre usted! / ¡No te rías! / ¡No te rindas!
* Don't deny it - ¡No lo niegues!
* Don't despair - ¡No te desesperes!

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¡Que te diviertas!
English:  Enjoy!

* Keep notes: Manténganse quietos.
* Let Tom go: Déjale irse.
* Let him in: Déjalo entrar.
* Let him out: ¡Déjame salir!
* Pay: Dejadme pagar.
* See: ¡Déjame ver!
* Hide: Escondámonos.
* Kiss: Besémonos.
* Play: Juguemos.
* Pray: Oremos.
* Quit: Debemos ver a Tom.
* Win: Deberíamos ganar.
* Make him cry: Le hicimos llorar.
* Make waffles: Hicimos waffles.
* Help: Nos encanta ayudar.
* Remember: Nos acordamos de Tom.
* Respect: Respetamos a Tom.
* Speak French: Hablamos francés.
* Study: Estudiamos francés.
* Walk a lot: Anduvimos mucho.
* Want it back: Lo queremos de vuelta.
* Want justice: Queremos justicia.
* Want to help: Queremos ayudar.
* It's not true: No es verdad.
* It's tea time: Es la hora del té.
* It's too cold: Hace demasiado frío.
* It's too dark: Es demasiado oscuro.
* It's too easy: Es demasiado fácil.
* It's too fast: Es demasiado rápido.
* It's too late: Es muy tarde.
* It's too loud: Es demasiado alto.
* It's too soon: Es demasiado pronto.
* It's up to me: Depende de mí.
* It's worth it: ¡A un lado!
* She's a fox: ¡Es una zorra!
* She's crazy: Ella está loca.
* Should I go?: ¿Debería ir?
* Show me how: ¡Muéstrame cómo!
* Sleep tight: ¡Que duermas bien!
* Speak to me: ¡Háblame!
* Stand aside: ¡A un lado!
* Start again: ¡Vuelve a empezar!
* Stay inside: ¡Quédate adentro!
* Stay strong: ¡Mantente fuerte!
* Step inside: ¡Pase!
* Stop moving: ¡No te muevas!
* Stop crying: ¡Deja de llorar!
* Stop trying: ¡Deja de intentarlo!
* Thief: ¡Alto! ¡Ladrón!

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: No te preocupes.
English:  No worries.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Lamento interrumpir.
English:  Up to you.
It isn't a fake.
It isn't a fish.
It isn't broken.
It isn't broken.
It may seem odd.
It really works.
It really works.
It seems likely.
It sounds great!
It sounds great!
It sounds weird.
It tasted sweet.
It was a secret.
It was a thrill.
It was ages ago.
It was all gone.
It was all good.
It was an honor.
It was like me.
It was obsolete.
It's our duty.
It's official.
It's up to me.
It's too cold.
It's too dark.
It's too easy.
It's too fast.
It's too late.
It's too loud.
It's too soon.
It's very big.
It's very dry.
It's very hot.
It's very old.
It's very sad.
It's worth it.
Is this a hoax?
Is this for me?
Is this normal?
Isn't it black?
Isn't it black?
Isn't it black?
It can be done.
It gets better.
It may be true.
It seems easy.
It smells good!
It's possible.
It was a dream.
It was a mouse.
It was amusing.
It was for Tom.
It was my idea.
It was my turn.
It was my hour.
It was nothing.
It was on sale.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Es una lástima.
English:  It's a shame.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: No sé. / No lo sé.
English:  Sure! Here are the translations for "No sé" and "No lo sé":

* "No sé" = I don't know.
* "No lo sé" = I don't know.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: No hay problema.
English:  No problem.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Necesito ayuda.
English:  I need help.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Necesito ir a…
English:  Translate: I need to go to...

* Debo ir allá: I must go there.
* Tengo que ayudarla: I must help her.
* Debo ayudarlo: I must help him.
* Debo obedecer a Tom: I must obey Tom.
* Tengo que decírselo a Tom: I must tell Tom.
* Lo hice por mi cuenta: I myself did it.
* Lo vi yo mismo: I myself saw it.
* Yo misma lo vi: I myself saw it.
* Necesito Internet: I need Internet.
* Necesito un doctor: I need a doctor.
* Necesito una escalera: I need a ladder.
* Necesito una laptop: I need a laptop.
* Necesito un portátil: I need a laptop.
* Necesito un abogado: I need a lawyer.
* Necesito un rotulador: I need a marker.
* Necesito un lápiz: I need a pencil.
* Necesito una ducha: I need a shower.
* Necesito un pañuelo: I need a tissue.
* Necesito un arma: I need a weapon.
* Necesito caféína: I need caffeine.
* Necesito su ayuda: I need his help.
* Necesito su nombre: I need his name.
* Lo necesito para hoy: I need it today.
* Lo necesito hoy: I need it today.
* Necesito mis pastillas: I need my pills.
* Necesito uno más: I need one more.
* Necesito una más: I need one more.
* Necesito un médico: I need a medic.
* Necesito un aumento: I need a raise.
* Necesito una regla: I need a ruler.
* Necesito afeitarme: I need a shave.
* Necesito un cigarrillo: I need a smoke.
* Necesito un bocadillo: I need a snack.
* Necesito un sello: I need a stamp.
* Necesito una toalla: I need a towel.
* Necesito respuestas: I need answers.
* Necesito tener amigos: I need friends.
* Necesito insulina: I need insulin.
* Lo necesito tan pronto como sea posible: I need it ASAP.
* Necesito mis llaves: I need my keys.
* Necesito cirugía: I need surgery.
* Necesito dejarlo: I need to quit.
* Necesito descansar: I need to rest.
* Tengo que parar: I need to stop.
* Necesito trabajar: I need to work.
* Necesitaba dinero: I needed money.
* Nunca salgo: I never go out.
* Viajo a menudo: I often travel.
* Le debo cien dólares: I owe him $100.
* Tengo este auto: I own this car.
* Pagué en efectivo: I paid in cash.
* Le pago bien a Tom: I pay Tom well.
* Yo pago mis impuestos: I pay my taxes.
* Me declaro culpable: I plead guilty.
* Necesito más luz: I need more light.
* Necesito más poder: I need more power.
* Necesito más espacio: I need more space.
* Necesito mis lentes: I need my glasses.
* Necesito mis gafas: I need my glasses.
* Necesito algo de papel: I need some paper.
* Necesito un poco de papel: I need some paper.
* Necesito papel: I need some paper.
* Necesito algo de azúcar: I need some sugar.
* Necesito un poco de agua: I need some water.
* Necesito ese teléfono: I need that phone.
* Necesito este dinero: I need this money.
* Tengo que comprar uno: I need to buy one.
* Necesito comprar uno: I need to buy one.
* Necesito hacer más: I need to do more.
* Necesito conseguir uno: I need to get one.
* Necesito regresar: I need to go back.
* Necesito ir a casa: I need to go home.
* Tengo que irme a casa: I need to go home.
* Necesitaba ese trabajo: I needed that job.
* Nunca compro azúcar: I never buy sugar.
* Yo nunca bebo té: I never drink tea.
* Nunca me enfado: I never get mad.
* Nunca me rindo: I never give up.
* No me rindo nunca: I never give up.
* Nunca dije que no: I never say no.
* No te he visto nunca: I never saw you.
* Yo le veo a menudo: I often see him.
* Solo necesito a Tom: I only need Tom.
* Solo quiero a Tom: I only want Tom.
* He pedido pan: I ordered bread.
* Pedí pizza: I ordered pizza.
* Le burlé: I outwitted him.
* Le debo dinero a Tom: I owe Tom money.
* Pagué mis cuentas: I paid my bills.
* Pagué la cuenta: I paid the bill.
* Juego al béisbol: I play baseball.
* Juego al fútbol: I play football.
* Juego en el campo: I play outfield.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¡Dios mío!
English:  Here are the translations of the phrases you provided:

* ¡Dios mío! - Oh my god!
* Hágalo rápido. - Do it quickly.
* Hazlo conmigo. - Do it with me.
* Lava los platos. - Do the dishes.
* ¿Lo necesitamos? - Do we need it?
* Haz lo que yo digo. - Do what I say.
* ¿Lo ves? - Do you see it?
* ¿Me ves? - Do you see me?
* ¿Lo sabe Tom? - Does Tom know?
* ¿Pica? - Does it sting?
* ¿Esto viene bien? - Does this fit?
* ¿Esta viene bien? - Does this fit?
* ¿Este viene bien? - Does this fit?
* No seas malo. - Don't be evil.
* No seas mala. - Don't be evil.
* No seáis malos. - Don't be evil.
* No seáis malas. - Don't be evil.
* No llegues tarde. - Don't be late.
* No lleguéis tarde. - Don't be late.
* No llegue tarde. - Don't be late.
* No entrar. - Don't come in.
* No lo niegues. - Don't deny it.
* ¡No te desesperes! - Don't despair.
* Me gustan los tulipanes. - I like tulips.
* Me gusta el invierno. - I like winter.
* Yo miré a otro lado. - I looked away.
* Yo aparté la vista. - I looked away.
* Yo miré hacia abajo. - I looked down.
* Perdí a mi perro. - I lost my dog.
* Yo perdí mi sombrero. - I lost my hat.
* He perdido la llave. - I lost my key.
* He perdido mi llave. - I lost my key.
* Perdí mi clave. - I lost my key.
* Perdí mi llave. - I lost my key.
* Yo amo Boston. - I love Boston.
* Me encanta el francés. - I love French.
* ¡Me encantan los lunes! - I love Monday!
* Me gusta hornear. - I love baking.
* Yo amo los camellos. - I love camels.
* Yo amo el queso. - I love cheese.
* Me encanta el café. - I love coffee.
* Yo amo el ajo. - I love garlic.
* Yo amo el excursionismo. - I love hiking.
* Me encantan los caballos. - I love horses.
* Amo a mi papá. - I love my dad.
* Me encanta mi trabajo. - I love my job.
* Me gusta el empleo que tengo. - I love my job.
* Quiero a mi mamá. - I love my mom.
* Quiero a mi madre. - I love my mom.
* Amo a mi hijo. - I love my son.
* Yo me quiero. - I love myself.
* No te me mueras. - Don't die on me.
* No te me vayas a morir. - Don't die on me.
* No lo olvides. - Don't forget it.
* No lo olvidéis. - Don't forget it.
* No se enoje. - Don't get angry.
* No te enojes. - Don't get angry.
* No se enfade. - Don't get angry.
* No te emborraches. - Don't get drunk.
* No interfieras. - Don't interfere.
* No interrumpas. - Don't interrupt.
* No me mientas. - Don't lie to me.
* No me mintáis. - Don't lie to me.
* No nos mientas. - Don't lie to us.
* No mires atrás. - Don't look back.
* No mires abajo. - Don't look down.
* No exageres. - Don't overdo it.
* No te hagas el muerto. - Don't play dead.
* ¡No hagas el ridículo! - Don't play dumb!
* No hagas el tonto. - Don't play dumb!
* No juegues aquí. - Don't play here.
* No me lo recuerdes. - Don't remind me.
* No pares aquí. - Don't stop here.
* No digas mentiras. - Don't tell lies.
* No mientas. - Don't tell lies.
* ¡No mientas! - Don't tell lies.
* No confíes en Tom. - Don't trust Tom.
* No confíes en él. - Don't trust him.
* No confíe en él. - Don't trust him.
* No confiéis en él. - Don't trust him.
* Descansemos. - Let's rest.
* Cantemos. - Let's sing.
* Nademos. - Let's swim.
* Conversemos. - Let's talk.
* Votemos. - Let's vote.
* Caminemos. - Let's walk.
* Trabajemos. - Let's work.
* Levanta. - Lift it up.
* Mirá de nuevo. - Look again.
* Mira de nuevo. - Look again.
* Mire de nuevo. - Look again.
* Miren de nuevo. - Look again.
* Mirá hacia adelante. - Look ahead.
* Mira hacia adelante. - Look ahead.
* Mire hacia adelante. - Look ahead.
* Miren hacia adelante. - Look ahead.
* Míralo. - Look at it.
* Obsérvalo. - Look it up.
* Buscalo. - Look it up.
* Mirá allí. - Look there.
* El amor dura. - Love lasts.
* Mamá lloró. - Mama cried.
* Caía la noche. - Night fell.
* Anochecía. - Night fell.
* Sin comentarios. - No comment.
* ¿En serio? - No kidding?
* ¡No hay problema! - No problem!
* ¡Sin problemas! - No problem!
* Ningún problema. - No problem.
* Sin problema. - No problem.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¿Lo entiendes?
English:  Sure, here are the translations:

* Salimos a las dos y media. = We left at 2:30.
* Nos gusta conversar. = We like to talk.
* Nos encanta esta zona. = We love it here.
* Nos encanta estar aquí. = We love it here.
* Nos encantan los picnics. = We love picnics.
* Nos encanta ayudar. = We love to help.
* Le hicimos llorar. = We made him cry.
* Hicimos waffles. = We made waffles.
* Hicimos gofres. = We made waffles.
* Conocimos un escritor. = We met a writer.
* Debemos ver a Tom. = We must see Tom.
* Deberíamos ganar. = We ought to win.
* Le pagamos bien a Tom. = We pay Tom well.
* Castigamos a Tom. = We punished Tom.
* Nos acordamos de Tom. = We remember Tom.
* Los respetamos. = We respect them.
* Las respetamos. = We respect them.
* Nosotros cantamos para ella. = We sang for her.
* Compartimos ideas. = We shared ideas.
* Deberíamos irnos. = We should leave.
* Hablamos francés. = We speak French.
* Estudiamos francés. = We study French.
* Anduvimos mucho. = We walked a lot.
* Lo queremos de vuelta. = We want it back.
* Queremos justicia. = We want justice.
* Queremos ayudar. = We want to help.
* La entrada es gratuita. = Admission is free.
* La entrada es libre. = Admission is free.
* Todo lo que quiero es vos. = All I want is you.
* Todos los hombres son iguales. = All men are equal.
* Los hombres son todos iguales. = All men are equal.
* ¿Soy una mala persona? = Am I a bad person?
* ¿Te estoy molestando? = Am I annoying you?
* ¿Me voy a morir? = Am I going to die?
* ¿Voy a morir? = Am I going to die?
* ¿Soy el único? = Am I the only one?
* ¿Estoy bajo arresto? = Am I under arrest?
* ¿Estoy detenido? = Am I under arrest?
* América los ama. = America loves you.
* América os ama. = America loves you.
* América te ama. = America loves you.
* Se cometió un error. = An error was made.
* Respóndame, por favor. = Answer me, please.
* Cualquier papel sirve. = Any paper will do.
* Cualquier lugar basta. = Any place will do.
* ¿Son velas estas? = Are these candles?
* ¿Son americanos? = Are they American?
* ¿Son estadounidenses? = Are they American?
* ¿Son canadienses? = Are they Canadian?
* ¿Son ellos japoneses? = Are they Japanese?
* ¿Son japoneses? = Are they Japanese?
* Me gustan los tulipanes. = I like tulips.
* Me gusta el invierno. = I like winter.
* Yo miré a otro lado. = I looked away.
* Yo aparté la vista. = I looked away.
* Yo miré hacia abajo. = I looked down.
* Perdí a mi perro. = I lost my dog.
* Yo perdí mi sombrero. = I lost my hat.
* He perdido la llave. = I lost my key.
* He perdido mi llave. = I lost my key.
* Perdí mi clave. = I lost my key.
* Perdí mi llave. = I lost my key.
* Yo amo Boston. = I love Boston.
* Me encanta el francés. = I love French.
* ¡Me encantan los lunes! = I love Mondays!
* Me gusta hornear. = I love baking.
* Yo amo los camellos. = I love camels.
* Yo amo el queso. = I love cheese.
* Me encanta el café. = I love coffee.
* Yo amo el ajo. = I love garlic.
* Yo amo el excursionismo. = I love hiking.
* Me encantan los caballos. = I love horses.
* Amo a mi papá. = I love my dad.
* Me encanta mi trabajo. = I love my job.
* Me gusta el empleo que tengo. = I love my job.
* Quiero a mi mamá. = I love my mom.
* Quiero a mi madre. = I love my mom.
* Amo a mi hijo. = I love my son.
* Yo me quiero. = I love myself.
* Yo vi un OVNI. = I saw a UFO.
* Vi a un perro. = I saw a dog.
* Vi un perro. = I saw a dog.
* Yo vi un perro. = I saw a dog.
* Vendo autos. = I sell cars.
* Vendo coches. = I sell cars.
* Vendo pescado. = I sell fish.
* Vendo jabón. = I sell soap.
* Me debería ir. = I should go.
* Huelo a gas. = I smell gas.
* Huelo gas. = I smell gas.
* Me huele a gas. = I smell gas.
* Te lo agradezco. = I thank you.
* Confío en Tom. = I trust Tom.
* Yo confío en ella. = I trust her.
* Yo confío en él. = I trust him.
* Confío en ti. = I trust you.
* Yo voté que sí. = I voted yes.
* Quiero huevos. = I want eggs.
* Quiero el mío. = I want mine.
* Yo quiero el mío. = I want mine.
* Yo quiero la mía. = I want mine.
* Quiero más. = I want more.
* Quiero sopa. = I want soup.
* Quiero eso. = I want that.
* Los quiero. = I want them.
* Las quiero. = I want them.
* Quiero este. = I want this.
* Quiero esto. = I want this.
* Yo estaba vivo. = I was alive.
* Estuve solo. = I was alone.
* Estaba despierto. = I was awake.
* Estaba aburrido. = I was bored.
* Estaba mareado. = I was dizzy.
* Estaba mareada. = I was dizzy.
* Estaba borracho. = I was drunk.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: No entiendo. / No lo entiendo.
English:  * Try to find it. - Intenta encontrarla.
* Stop me. - Trata de detenerme.
* Turn on the TV. - Enciende la televisión.
* Turn up the TV. - Aumente el volumen de la televisión.
* Update the app. - Actualice la aplicación.
* Was Tom crying? - ¿Lloró Tom?
* Is your car black? - ¿El color de su carro es negro?
* Is your dog white? - ¿El color de su perro es blanco?
* Is your mic muted? - ¿Tu mic es mudo?
* Is your wife tall? - ¿Tu esposa es alta?
* Isn't it exciting? - ¿No es emocionante?
* Isn't it pathetic? - ¿No es patético?
* Isn't it stunning? - ¿No es impresionante?
* Is that theirs? - ¿Eso no es de ellos?
* It can't be fixed. - No se puede arreglar.
* It can't be true. - No puede ser verdad.
* It costs too much. - Cuesta demasiado caro.
* It could be fatal. - Podría ser fatal.
* It didn't go well. - Lo pasó mal.
* It doesn't fit me. - No me queda.
* It doesn't matter. - No importa.
* It has to be done. - Debe de ser hecho.
* It has to be true. - Debe de ser verdad.
* Is this your son? - ¿Este es tu hijo?
* Is your car blue? - ¿Tu coche es azul?
* Is your dog mean? - ¿Tu perro es cruel?
* Is your name Tom? - ¿Tu nombre es Tom?
* Isn't that right? - ¿A que sí?
* Isn't that weird? - ¿No es eso raro?
* It began to rain. - Empezó a llover.
* It began to snow. - Empezó a nevar.
* It can't be true. - No puede ser verdad.
* It costs 2 euros. - Cuesta 2 euros.
* It creeps me out. - Me da una enchinada.
* It doesn't exist. - No existe.
* It looks painful. - Parece doloroso.
* It looks perfect. - Lo veo perfecto.
* I couldn't move. - No podía moverme.
* I didn't listen. - No escuché.
* I didn't say it. - No lo dije.
* I didn't see it. - No lo vi.
* I do that a lot. - Lo hago mucho.
* I do understand. - Sí que lo entiendo.
* I don't feel it. - No lo siento.
* I don't like it. - No me gusta.
* I don't need it. - No lo necesito.
* I don't see him. - No lo veo.
* I don't understand. - No lo entiendo.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Me voy a casa.
English:  Going home.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¿Cómo llego a…?
English:  "How do I get to...?"

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: No tengo idea.
English:  I have no idea.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¿Me puede traer (la carta, una bebida, etc.)?
English:  Sure! Here's the translation:

Can you bring me (the letter, a drink, etc.)?

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: La cuenta por favor.
English:  Stop yelling.
Please stop.
Study harder.
Study more.
Sweet dreams!
Take it easy!
Take control.
Take it home.
Take my hand.
Tell Tom why.
Cuéntame más.
Tell me more.
Díganos más.
Dígannos más.
Tell us more.
Cuéntanos más.
Wait here for me.
Walk more slowly.
Was Tom handsome?
Was Tom involved in this?
Watch my fingers.
We accept checks.
Aced the exam.
Agree as well.
It's not true.
It's now 2:30.
It's obsolete.
It's occupied.
It's official.
It's too cold.
It's too dark.
It's too easy.
It's too fast.
It's too late.
It's too loud.
It's up to me.
It's worth it.
We left at 2:30.
We like to talk.
We love it here.
We love to help.
We pay Tom well.
We punished Tom.
We remember Tom.
We respect them.
We want it back.
We want justice.
We want to help.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¿Puede hablar más despacio?
English:  Slower.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¿Cómo se dice…?
English:  Here are the translations of the phrases you provided:

* ¿El color de su carro es negro? - What color is your car?
* ¿Tu auto es negro? - Is your car black?
* ¿Tu perro es blanco? - Is your dog white?
* ¿Está tu micro desactivado? - Is your mic muted?
* ¿Tu esposa es alta? - Is your wife tall?
* ¿No es emocionante? - Isn't it exciting?
* ¿No es patético? - Isn't it pathetic?
* ¿No es impresionante? - Isn't it stunning?
* ¿Eso no es de ellos? - Isn't that theirs?
* No se puede arreglar. - It can't be fixed.
* No puede ser cierto. - It cannot be true.
* No puede ser verdad. - It cannot be true.
* Eso no puede ser verdad. - It cannot be true.
* Cuesta demasiado caro. - It costs too much.
* Podría ser fatal. - It could be fatal.
* Lo pasó mal. - It didn't go well.
* No me queda. - It doesn't fit me.
* No es importante. - It doesn't matter.
* Eso no importa. - It doesn't matter.
* No importa. - It doesn't matter.
* Se hizo pedazos. - It fell to pieces.
* Functiona en ambos sentidos. - It goes both ways.
* Ha refrescado. - It has cooled off.
* Hay que hacerlo. - It has to be done.
* Debe de ser verdad. - It has to be true.
* ¿Puedes ir sola? - Can you go alone?
* ¿Puedes reunirte con él? - Can you meet him?
* ¿Puedes demostrarlo? - Can you prove it?
* ¿Puedes correr rápido? - Can you run fast?
* ¿Podéis verlas? - Can you see them?
* ¿Puedes verlas? - Can you see them?
* ¿Puedes verlos? - Can you see them?
* ¿Puede ver esto? - Can you see this?
* ¿Eres capaz de resolverlo? - Can you solve it?
* ¿Puedes levantarte? - Can you stand up?
* ¿Te puedes levantar? - Can you stand up?
* ¿Podéis levantaros? - Can you stand up?
* ¿Os podéis levantar? - Can you stand up?
* ¿Puedes enseñarme? - Can you teach me?
* ¿Me puedes enseñar? - Can you teach me?
* ¿No podemos solamente ir? - Can't we just go?
* Verifique sus hechos. - Check your facts.
* Verifique sus datos. - Check your facts.
* Revisa tu carpeta de entrada. - Check your inbox.
* Comprueba tu buzón. - Check your inbox.
* Verifique su orden. - Check your order.
* Las cerezas son rojas. - Cherries are red.
* Elige sabiamente. - Choose carefully.
* Elige con cuidado. - Choose carefully.
* Elige con prudencia. - Choose carefully.
* Vive un poco. - Live a little.
* ¡Traba la puerta! - Lock the door!
* ¡Ponle llave a la puerta! - Lock the door!
* Cierra la entrada. - Lock the gate.
* Cierra la cancela. - Lock the gate.
* Mira éstos. - Look at these.
* Fíjate en éstos. - Look at these.
* Mira aquéllos. - Look at those.
* Fíjate en ésos. - Look at those.
* Mira allí. - Look in there.
* Busca allí. - Look in there.
* Mira ahí. - Look in there.
* El amor es ciego. - Love is blind.
* El amor es una locura. - Love is crazy.
* Haz una oferta. - Make an offer.
* Sé breve. - Make it brief.
* Hazlo rápido. - Make it quick.
* Resume. - Make it short.
* Hazme feliz. - Make me happy.
* Haz tu cama. - Make your bed.
* El hombre es mortal. - Man is mortal.
* María es muy chula. - Mary is a fox.
* Mary es mamá. - Mary is a mom.
* María es rara. - Mary is weird.
* Mary chilló. - Mary shrieked.
* ¿Puedo preguntar por qué? - May I ask why?
* ¿Puedo entrar? - May I come in?
* ¿Puedo irme a casa? - May I go home?
* ¿Me puedo ir a mi casa? - May I go home?
* ¿Puedo verlo? - May I see him?
* ¿Podemos irnos ahora? - May we go now?
* Lo hice bien. - I've done OK.
* Lo he perdido. - I've lost it.
* Lo he visto. - I've seen it.
* El hielo es sólido. - Ice is solid.
* El hierro es duro. - Iron is hard.
* ¿Está bien el lunes? - Is Monday OK?
* ¿Tom está despierto? - Is Tom awake?
* ¿Tom está loco? - Is Tom crazy?
* ¿Tom está curado? - Is Tom cured?
* ¿Tom está borracho? - Is Tom drunk?
* ¿Se está muriendo Tom? - Is Tom dying?
* ¿Tom es feliz? - Is Tom happy?
* ¿Tom es lúcido? - Is Tom lucid?
* ¿Tom está mintiendo? - Is Tom lying?
* ¿Tom está preparado? - Is Tom ready?
* ¿Tom tiene razón? - Is Tom right?
* ¿Está ahí Tom? - Is Tom there?
* ¿Eso es un ciervo? - Is it a deer?
* ¿Acasa es una trampa? - Is it a trap?
* ¿Acasa es un lobo? - Is it a wolf?
* ¿Es un lobo? - Is it a wolf?
* ¿Eso es un alce? - Is it an elk?
* ¿Está roto? - Is it broken?
* ¿Es cáncer? - Is it cancer?
* ¿Es suficiente? - Is it enough?
* ¿Eso es amor? - Is that love?
* ¿Es mío ése? - Is that mine?
* ¿Es ése el mío? - Is that mine?
* ¿Eso es nuestro? - Is that ours?
* ¿Eso es nieve? - Is it snow?
* ¿Es verdad? - Is it true?

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¿Qué es esto?
English:  This is a list of 20 Spanish phrases and their English translations.

1. ¿El color de su carro es negro? - Is your car black?
2. ¿Tu auto es negro? - Is your car black?
3. ¿Tu perro es blanco? - Is your dog white?
4. ¿Está tu micro desactivado? - Is your mic muted?
5. ¿Tu esposa es alta? - Is your wife tall?
6. ¿No es emocionante? - Isn't it exciting?
7. ¿No es patético? - Isn't it pathetic?
8. ¿No es impresionante? - Isn't it stunning?
9. ¿Eso no es de ellos? - Isn't that theirs?
10. No se puede arreglar. - It can't be fixed.
11. No puede ser cierto. - It can't be true.
12. No puede ser verdad. - It can't be true.
13. Eso no puede ser verdad. - It can't be true.
14. Cuesta demasiado caro. - It costs too much.
15. Podría ser fatal. - It could be fatal.
16. Lo pasó mal. - It didn't go well.
17. No me queda. - It doesn't fit me.
18. No es importante. - It doesn't matter.
19. Eso no importa. - It doesn't matter.
20. No importa. - It doesn't matter.

Note: Some of the phrases in the list may have multiple translations or nuances depending on the context in which they are used.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¿Verdad (que sí)?
English:  True.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Estoy de acuerdo.
English:  I agree.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Por supuesto.
English:  Is your car black? - ¿El color de su carro es negro?
Is your dog white? - ¿Tu perro es blanco?
Isn't it exciting? - ¿No es emocionante?
Isn't it pathetic? - ¿No es patético?
Isn't it stunning? - ¿No es impresionante?
That's not theirs - Eso no es de ellos.
It can't be fixed - No se puede arreglar.
It can't be true - No puede ser cierto.
It can't be true - No puede ser verdad.
It can't be true - Eso no puede ser verdad.
It costs too much - Cuesta demasiado caro.
It could be fatal - Lo pasó mal.
Take a break - Descanse ahora.
Study harder - Estudia más.
Take control - Toma el control.
Take it easy - ¡Relajate!
Take it home - Llévanos a casa.
Tell Tom why - Dígnos más.
Cuéntame more - Dime más.
Tell us more - Díganos más.
Tell us more - Dígannos más.
Go slower - Trata de ir más despacio.
Turn off the gas - Corta el gas.
Wait here for me - Espera por mí aquí.
Walk more slowly - Camina más despacio.
Was Tom handsome? - ¿Tom era guapo?
Was Tom involved in this? - ¿Tom estaba involucrado en esto?
Watch my fingers - Mirá mis dedos.
Be careful - Tengan cuidado.
Water the plants - Riega las plantas.
We accept checks - Aceptamos cheques.
We aced the exam - Sacamos un sobresaliente en el examen.
We agree too - Estamos de acuerdo también.
Stay focused - Concentraos.
Stay with me - Quédense aquí con nosotros.
Stay with us - Quédate aquí con nosotros.
Stop arguing - Deja de discutir.
Stop gawking - Deja de mirar.
Stop pushing - Deja de empujar.
Stop reading - Deja de leer.
Stop smoking - Deja de fumar.
Stop staring - Deja de mirarme.
Stop talking - Cállate.
Stop the car - Pará el coche.
Stop whining - Deja de quejarte.
That's not theirs - Eso no es de ellos.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Llámame cuando llegues.
English:  Call me when you arrive.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¿Estás listo?
English:  Ready.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Te amo.
English:  "I love you."

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Te quiero.
English:  I love you.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Todo está bien.
English:  Everything is fine.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Tengo hambre.
English:  I have hunger.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Tengo sed.
English:  I have thirst.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Una mesa para dos, por favor.
English:  A table for two, please.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: ¿Tiene…?
English:  Here are the translations for the phrases you provided:

* ¿Tiene…? - Do you have...?
* Él me devolvió el golpe. - He hit me back.
* Él es médico. - He is a doctor.
* Es médico. - He is a doctor.
* Él es un genio. - He is a genius.
* Es un genio. - He is a genius.
* Él es golfista. - He is a golfer.
* Él es escritor. - He is a writer.
* Él es actor. - He is an actor.
* Él está arruinado. - He is bankrupt.
* Él es un sin techo. - He is homeless.
* Él es mi tío. - He is my uncle.
* Él no es tonto. - He is not dumb.
* No está aquí. - He is not here.
* Él es extrovertido. - He is outgoing.
* Él aprende rápido. - He learns fast.
* Le gusta la gelatina. - He likes jelly.
* Le gusta el dinero. - He likes money.
* Él vive solo. - He lives alone.
* Él miró hacia otro lado. - He looked away.
* Él miró hacia atrás. - He looked back.
* Él tenía buen aspecto. - He looked well.
* Él parece aburrido. - He looks bored.
* Él se ve joven. - He looks young.
* Adora la música. - He loves music.
* A él le encanta la música. - He loves music.
* Él juega allí. - He plays there.
* Él me respeta. - He respects me.
* También lo vio. - He also saw it.
* La retó. - He scolded her.
* Tienes un aspecto horrible. - You look awful.
* Tienes muy mala cara. - You look awful.
* Pareces aburrido. - You look bored.
* Te ves genial. - You look great.
* Te ves contento. - You look happy.
* Parece usted feliz. - You look happy.
* Se le ve feliz. - You look happy.
* Pareces listo. - You look sharp.
* Pareces espabilado. - You look sharp.
* Pareces cansado. - You look tired.
* Pareces cansada. - You look tired.
* Usted se ve cansado. - You look tired.
* Tienes cara de sueño. - You look tired.
* Pareces molesto. - You look upset.
* Ahora puedes irte. - You may go now.
* Ahora puede irse. - You may go now.
* Puedes negarte. - You may refuse.
* Quizá vuelva. - You may return.
* Quizá vuelvan. - You may return.
* Quizá vuelvas. - You may return.
* Quizá volváis. - You may return.
* Puedes que vuelvas. - You may return.
* Puedes que volváis. - You may return.
* Puedes que vuelva. - You may return.
* Puedes que volvan. - You may return.
* Tienes que hacerlo. - You must do it.
* Debes hacérselo. - You must do it.
* Tienes que irte. - You must leave.
* ¿Han ido? - Have they gone?
* ¿Han salido? - Have they gone?
* ¿Has comido? - Have you eaten?
* ¿Comiste? - Have you eaten?
* ¿Ya comiste? - Have you eaten?
* ¿Has dormido? - Have you slept?
* ¿Habéis dormido? - Have you slept?
* ¿Ha dormido usted? - Has he slept?
* Él aceleró. - He accelerated.
* Él también lo vio. - He also saw it.
* Él se ha hecho rico. - He became rich.
* Él se mordió el labio. - He bit his lip.
* Ha venido en autobús. - He came by bus.
* Él vino en carro. - He came by car.
* Él no sabe contar. - He can't count.
* Él se lo merecía. - He deserved it.
* Desapareció. - He disappeared.
* Me tiene antipatía. - He dislikes me.
* Él no miente. - He doesn't lie.
* Él no corre. - He doesn't run.
* Él no se pone moreno. - He doesn't tan.
* Él elevó un volantín. - He flew a kite.
* Él tiene 12 hijos. - He has 12 sons.
* Él tiene barba. - He has a beard.

Note: Some of the phrases may have multiple translations or variations depending on the context and style guide.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Me gustaría…
English:  * Me gustaría ir de picnic.
* Me gustaría los rompecabezas.
* Me gustaría mucho leer.
* Me gustaría el sashimi.
* Me gustaría los mariscos.
* Me gustaría cantar.
* Me gustaría las historias.
* Me gustaría hablar.
* Me gustaría el perro.
* Me gustaría cocinar.
* Me gustaría dibujar.
* Me gustaría mucho leer.
* Me gustaría cantar.
* Me gustaría nadar.
* Me gustaría hablar.
* Me gustaría caminar.
* Me gustaría trabajar.
* Me gustaría las tortugas.
* Me gustaría caminar.
* Me gustaría trabajar.
* Me gustaría escribir.
* Me gustaría la escritura.
* Me gustaría los animales.
* Me gustaría este reloj de pulsera.
* Me gustaría estar aquí.
* Me gustaría la sandía.
* Me gustaría tu caballo.
* Me gustaría tu casa.
* Me gustaría tu casa.
* Me gustan tus ideas.
* Me gusta tu teléfono.
* Me gusta tu bufanda.
* Me gusta tu camisa.
* Me gusta tu estilo.
* Me gusta tu camión.
* Me gusta tu voz.
* La película me gustó.
* Vivo aquí solo.
* Viví en Boston.
* He bloqueado la puerta.
* He trancado la puerta.
* Perdí un arete.
* Yo perdí un arete.
* He perdido un arete.
* Yo he perdido un arete.
* Lo he perdido todo.
* Lo perdí todo.
* Yo sé cosas.
* Yo dejo a Tom ganar.
* Yo dejé a Tom ganar.
* Yo lo dejo caer.
* Yo lo dejé caer.
* Yo los dejo ir.
* Yo los dejé ir.
* Yo te dejo ganar.
* Yo le mentí a Tom.
* Te mentí.
* Les mentí.
* Me gusta el francés.
* Me encanta el francés.
* Me gustan las manzanas.
* Me gustan los camellos.
* Me gusta el queso.
* Me gustan los relojes.
* Me gusta el café.
* Me gustan los caballos.
* Me gustan las películas.
* Me gusta mi trabajo.
* Me gusta la escuela.
* Me gusta coser.
* Me gusta esquiar.
* Me gusta las cucharas.
* Me gusta el deporte.
* Me gusta el tenis.
* Me gusta comer.
* Me gustan los trenes.
* Sencillamente me rendí.
* Acabo de encontrar con él.
* Acabo de gritar.
* Acabo de venderlo.
* Simplemente lo quiero.
* Lo quiero ya.
* Lo quiero y ya está.
* Mantuve mi palabra.
* Lo sé bien.
* Conozco al chico.
* Me gusta el inglés.
* Me gustan los castillos.
* Me gusta el pollo.
* Me gustan las galletas.
* Me gusta cocinar.
* Me gusta dibujar.
* Me gusta la pesca.
* Me gusta la historia.
* Me gusta planchar.
* Me gusta trotar.
* Me gusta la lechuga.
* Me gusta el mahjong.
* Me gusta mi vida.
* Me gusta mi nombre.
* Me gustan los fideos.
* Me gustan los tallarines.

HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

Original: Quisiera…
English:  Here are the translations for "Quisiera..." in different contexts:

* Quisiera...: I want... (e.g. Quisiera ir al cine.)
* Quiero...: I want... (e.g. Quiero un helado.)
* Lo quiero...: I want... (e.g. Lo quiero todo.)
* Tengo ganas de...: I want to... (e.g. Tengo ganas de llorar.)
* Quiero morir: I want to die.
* Quiero comer: I want to eat.
* Quiero correr: I want to run.
* Quiero intentarlo: I want to try.
* Quiero ganar: I want to win.

Note: Some of these phrases may have different translations depending on the context and the tone used. These are some common translations, but it's important to consider the context and the intended meaning when translating.

In [32]:
bleu = sacrebleu.corpus_bleu(my_rag_translations, my_english_text)
chrf = sacrebleu.corpus_chrf(my_rag_translations, my_english_text)

print(f"BLEU Score: {bleu.score:.2f}")
print(f"chrF Score: {chrf.score:.2f}")

BLEU Score: 0.16
chrF Score: 3.10

In [33]:
# 1. Setup your data
# 'src' = original Spanish, 'mt' = your Ollama output, 'ref' = ground truth
data = [
    {
        "src": src,
        "mt": mt,
        "ref": ref
    }
    for src, mt, ref in zip(my_spanish_text, my_rag_translations, my_english_text)
]

print(f"CUDA Available: {torch.cuda.is_available()}")

# 2. Load the pre-trained model
# 'wmt22-comet-da' is a standard high-performing version

# 3. Calculate scores
model_output = model.predict(data, batch_size=8, gpus=1) # Set gpus=1 if you have a GPU

# 4. Access the results
print(f"System Score: {model_output.system_score}") 
# Individual scores are in model_output.scores

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]

CUDA Available: True

/home/jovyan/.conda/lib/python3.13/site-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
Predicting DataLoader 0: 100%|██████████| 14/14 [00:03<00:00,  3.84it/s]

System Score: 0.6971353648437394

In [34]:
my_QLoRA_RAG_translations = []

for text in my_spanish_text:
    # 1. Retrieve context relative to the Spanish snippet
    docs = retriever.invoke(text)
    context = "\n".join([doc.page_content for doc in docs])

    # 2. Integrate context into your specific QLoRA prompt template
    # We place the context BEFORE the translation task so the model "reads" it first
    prompt = (
        f"Context: {context}\n"
        f"Spanish: {text}\n"
        "English:"
    )

    # 3. Generate using your fine-tuned model
    response = ollama.generate(
        model='qlorallamatranslator',      
        prompt=prompt,
        options={
            'temperature': 0,
            'stop': ["Spanish:", "\n", "English:", "Context:"] # Added "Context:" as a stop sequence
        }
    )
    
    translation = response['response'].strip()

    print(f"Original: {text}")
    print(f"English:  {translation}\n")
    my_QLoRA_RAG_translations.append(translation)

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Buenos días.
English:  Good morning.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Buenas tardes.
English:  Señora Presidenta, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Comisaria, Señora Com

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Buenas noches.
English:  Goodnight.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Hola.
English:  Señora Presidenta, Señora Comisaria, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta, Señora Comisaria, Señora Presidenta

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Cómo estás?
English:  How are you?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Bien, gracias. ¿Y tú?
English:  Thank you.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Qué pasa?
English:  What is the matter?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Qué tal?
English:

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Qué haces?
English:  What are you doing?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Cómo te va?
English:  How are you?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Muy bien.
English:

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Todo bien.
English:

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Más o menos.
English:

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Así, así.
English:  So, so.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: No muy bien.
English:  No, not very well.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Adiós!
English:  Goodbye.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Hasta mañana.
English:  Until tomorrow.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Hasta luego.
English:

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Hasta pronto.
English:  Until tomorrow.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Nos vemos.
English:  We are in the process of selling fruit.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Gracias.
English:  Thank you.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Por favor.
English:  Please.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: De nada.
English:

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Lo siento.
English:

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Perdón.
English:

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Disculpe.
English:

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Con permiso.
English:

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Salud!
English:

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Buen provecho.
English:  A buena estrategia.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Buena suerte!
English:  Good luck!

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Cuídate.
English:  You must be careful.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Cómo te llamas?
English:  What is your name?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Cuál es tu nombre?
English:  What is your name?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Me llamo Michael.
English:  I am Michael.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Mucho gusto.
English:  Muchas gracias.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Un placer.
English:  A pleasure.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: El placer es mío.
English:  I am pleased.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Encantado/Encantada
English:

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿De dónde eres?
English:  Where are you from?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Soy de los Estados Unidos.
English:  I am from America.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Qué edad tienes?
English:  What age are you?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Cuántos años tienes?
English:  How old are you?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Cuándo es tu cumpleaños?
English:  When is your birthday?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿A qué te dedicas?
English:  What is your job?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Soy astronauta.
English:  Soy astronauta.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿En qué trabajas?
English:  What is your job?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Trabajo en NASA
English:  I work for NASA

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Qué te gusta hacer?
English:  What do you like to do?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Me gusta leer.
English:  I like reading.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Me encanta comer.
English:  I am a food-lover.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Qué haces en tu tiempo libre?
English:  What do you do in your free time?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Cuáles son tus pasatiempos?
English:  What are your hobbies?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Cuál es tu banda favorita?
English:  What is your favourite band?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Mi (libro, película, banda) favorito(a) es…
English:  My (book, film, band) favourite is…

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Qué haces aquí?
English:  What are you doing here?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Quién eres?
English:  Who are you?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Cuánto cuesta?
English:  How much does it cost?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Dónde está el baño?
English:  Where is the bath?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Quieres tomar algo?
English:  Do you want to take anything?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Qué hora es?
English:  What time is it?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Qué día es hoy?
English:  What day is today?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Habla inglés?
English:

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Puedo pasar?
English:  I can go.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Pasa algo malo?
English:  Something is wrong.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Feliz cumpleaños!
English:

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Feliz navidad!
English:

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Feliz año nuevo!
English:

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Felicidades!
English:

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Enhorabuena!
English:

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Salud!
English:

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Bienvenida!
English:  Welcome!

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Buen viaje!
English:

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Cuánto tiempo sin verte!
English:  You have not seen us for a long time.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Bien hecho!
English:

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Diviértete!
English:  Do not despair.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Que te diviertas!
English:  You should be amused.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: No te preocupes.
English:  You will not be concerned.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Lamento interrumpir.
English:  I am sorry to have to interrupt.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Es una lástima.
English:  It is a shame.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: No sé. / No lo sé.
English:

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: No hay problema.
English:  There is no problem.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Necesito ayuda.
English:  I need help.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Necesito ir a…
English:  I need to go to…

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¡Dios mío!
English:

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Lo entiendes?
English:  You will understand.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: No entiendo. / No lo entiendo.
English:

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Me voy a casa.
English:  I am going home.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Cómo llego a…?
English:  How can I, for example, be in the car?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: No tengo idea.
English:  I do not know.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Me puede traer (la carta, una bebida, etc.)?
English:  Can you bring me (the letter, a drink, etc.)?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: La cuenta por favor.
English:  We want to see the accounts.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Puede hablar más despacio?
English:  Can you speak more slowly?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Cómo se dice…?
English:

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Qué es esto?
English:  What is this?

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Verdad (que sí)?
English:  (

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Estoy de acuerdo.
English:

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Por supuesto.
English:

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Llámame cuando llegues.
English:  Call me when you arrive.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Estás listo?
English:  Señora Presidenta, espero que nos haga el Sr. Presidente del Consejo, Sr. Presidenta, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el Sr Presidente del Consejo, Sr Presidente, que nos haga el

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Te amo.
English:  I love you.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Te quiero.
English:  I want to see you.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Todo está bien.
English:  All is well.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Tengo hambre.
English:  I am hungry.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Tengo sed.
English:  I am thirsty.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Una mesa para dos, por favor.
English:  A table for two, please.

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: ¿Tiene…?
English:  Señora Presidenta, eso es lo que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr. Prodi, que nos ha dicho el Sr. Presidente del Consejo, Sr

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Me gustaría…
English:  I would like to…

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"

Original: Quisiera…
English:  I would like to…

In [35]:
bleu = sacrebleu.corpus_bleu(my_QLoRA_RAG_translations, my_english_text)
chrf = sacrebleu.corpus_chrf(my_QLoRA_RAG_translations, my_english_text)

print(f"BLEU Score: {bleu.score:.2f}")
print(f"chrF Score: {chrf.score:.2f}")

BLEU Score: 0.02
chrF Score: 0.26

In [36]:
# 1. Setup your data
# 'src' = original Spanish, 'mt' = your Ollama output, 'ref' = ground truth
data = [
    {
        "src": src,
        "mt": mt,
        "ref": ref
    }
    for src, mt, ref in zip(my_spanish_text, my_QLoRA_RAG_translations, my_english_text)
]

print(f"CUDA Available: {torch.cuda.is_available()}")

# 2. Load the pre-trained model
# 'wmt22-comet-da' is a standard high-performing version

# 3. Calculate scores
model_output = model.predict(data, batch_size=8, gpus=1) # Set gpus=1 if you have a GPU

# 4. Access the results
print(f"System Score: {model_output.system_score}") 
# Individual scores are in model_output.scores

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]

CUDA Available: True

/home/jovyan/.conda/lib/python3.13/site-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
Predicting DataLoader 0: 100%|██████████| 14/14 [00:01<00:00,  7.83it/s]

System Score: 0.7600210339382842